// Myconids in Planar Sphere //////////////

IF
  Global("Iacreature","AR0419",0)
THEN
   RESPONSE #100
     SetGlobal("Iacreature","AR0419",1)
     CreateCreature("S!otyugh",[747.609],14) //
     ActionOverride("Container 1",CreateItem("potn07",0,0,0)) //
     ActionOverride("Container 1",CreateItem("S!scrl07",0,0,0)) //
     ActionOverride("Container 1",CreateItem("MISC29",0,0,0)) //
END