//Level 4 in Watchers Keep //////////////

IF
   Global("Iaitem","AR3017",0)
THEN
   RESPONSE #100
      SetGlobal("Iaitem","AR3017",1)
      ActionOverride("Container 3",CreateItem("S!misc09",0,0,0)) //
END

IF
   Global("Iaitem2","AR3017",0)
   !Class(Player1,MAGE_ALL)
THEN
   RESPONSE #100
      SetGlobal("Iaitem2","AR3017",1)
      ActionOverride("Container 3",CreateItem("belt02",0,0,0)) //
END
