// update and patch IDS tables //

COPY ~ImprovedAnvil\ids\stats.ids~ ~override/stats.ids~

ACTION_IF GAME_IS ~tob~ THEN BEGIN
  // a copy of stats.ids for the compiler
  COPY ~ImprovedAnvil\ids\stats.ids~ ~script compiler/stats.ids~
END

// SPELL.IDS //

APPEND ~SPELL.IDS~ ~1418 CLERIC_ACID_SHIELD~

// for BG2EE append a missing Ice Golem animation that is present in vanilla ToB //

ACTION_IF GAME_IS ~BG2EE~ THEN BEGIN
  APPEND ~animate.ids~ ~0xE0F0 IC_ICE_GOLEM~ UNLESS ~\bIC_ICE_GOLEM\b~
END