/// Copy new creatures, assign names ///

COPY ~ImprovedAnvil/resources/creatures/new/S!djinn.cre~         ~override/S!djinn.cre~
  SAY NAME1     @400
  SAY NAME2     @400

COPY ~ImprovedAnvil/resources/creatures/new/S!berser.cre~         ~override/S!berser.cre~
  SAY NAME1     @403
  SAY NAME2     @403

COPY ~ImprovedAnvil/resources/creatures/new/S!gem.cre~         ~override/S!gem.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gem2.cre~         ~override/S!gem2.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gem3.cre~         ~override/S!gem3.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gems.cre~         ~override/S!gems.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemt.cre~         ~override/S!gemt.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!geml.cre~         ~override/S!geml.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!roegol.cre~         ~override/S!roegol.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemc.cre~         ~override/S!gemc.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemg.cre~         ~override/S!gemg.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemw.cre~         ~override/S!gemw.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemgy.cre~         ~override/S!gemgy.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemhel.cre~         ~override/S!gemhel.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemwi.cre~         ~override/S!gemwi.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!ggem.cre~         ~override/S!ggem.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemran.cre~         ~override/S!gemran.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!gemrnd.cre~         ~override/S!gemrnd.cre~
  SAY NAME1     @407
  SAY NAME2     @407

COPY ~ImprovedAnvil/resources/creatures/new/S!elegol.cre~         ~override/S!elegol.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elego1.cre~         ~override/S!elego1.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elego2.cre~         ~override/S!elego2.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elego3.cre~         ~override/S!elego3.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elego4.cre~         ~override/S!elego4.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elego5.cre~         ~override/S!elego5.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elego6.cre~         ~override/S!elego6.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elego7.cre~         ~override/S!elego7.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elegob.cre~         ~override/S!elegob.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elegoe.cre~         ~override/S!elegoe.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elegog.cre~         ~override/S!elegog.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elegoh.cre~         ~override/S!elegoh.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elegow.cre~         ~override/S!elegow.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elegra.cre~         ~override/S!elegra.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elegwi.cre~         ~override/S!elegwi.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!elernd.cre~         ~override/S!elernd.cre~
  SAY NAME1     @409
  SAY NAME2     @409

COPY ~ImprovedAnvil/resources/creatures/new/S!coin.cre~         ~override/S!coin.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coin2.cre~         ~override/S!coin2.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coin3.cre~         ~override/S!coin3.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coinb.cre~         ~override/S!coinb.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coinc.cre~         ~override/S!coinc.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coinco.cre~         ~override/S!coinco.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coing.cre~         ~override/S!coing.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coinw.cre~         ~override/S!coinw.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coinwi.cre~         ~override/S!coinwi.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coingy.cre~         ~override/S!coingy.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coinhe.cre~         ~override/S!coinhe.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coinra.cre~         ~override/S!coinra.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coins.cre~         ~override/S!coins.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!coirnd.cre~         ~override/S!coirnd.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!gcoin.cre~         ~override/S!gcoin.cre~
  SAY NAME1     @410
  SAY NAME2     @410

COPY ~ImprovedAnvil/resources/creatures/new/S!skel.cre~         ~override/S!skel.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skel2.cre~         ~override/S!skel2.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skel3.cre~         ~override/S!skel3.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skeld.cre~         ~override/S!skeld.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skell1.cre~         ~override/S!skell1.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skell2.cre~         ~override/S!skell2.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skell3.cre~         ~override/S!skell3.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skell4.cre~         ~override/S!skell4.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skell5.cre~         ~override/S!skell5.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skelpp.cre~         ~override/S!skelpp.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skelr2.cre~         ~override/S!skelr2.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skels.cre~         ~override/S!skels.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!skelsu.cre~         ~override/S!skelsu.cre~
  SAY NAME1     @411
  SAY NAME2     @411
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_ANIMATED_PLATE_BRONZE~))

COPY ~ImprovedAnvil/resources/creatures/new/S!dlord.cre~         ~override/S!dlord.cre~
  SAY NAME1     @412
  SAY NAME2     @412

COPY ~ImprovedAnvil/resources/creatures/new/S!phound.cre~         ~override/S!phound.cre~
  SAY NAME1     @413
  SAY NAME2     @413

COPY ~ImprovedAnvil/resources/creatures/new/S!phoun3.cre~         ~override/S!phoun3.cre~
  SAY NAME1     @413
  SAY NAME2     @413

COPY ~ImprovedAnvil/resources/creatures/new/S!vlord.cre~         ~override/S!vlord.cre~
  SAY NAME1     @415
  SAY NAME2     @415

COPY ~ImprovedAnvil/resources/creatures/new/S!demgod.cre~         ~override/S!demgod.cre~
  SAY NAME1     @416
  SAY NAME2     @416

COPY ~ImprovedAnvil/resources/creatures/new/S!minion.cre~         ~override/S!minion.cre~
  SAY NAME1     @417
  SAY NAME2     @417

COPY ~ImprovedAnvil/resources/creatures/new/S!minhel.cre~         ~override/S!minhel.cre~
  SAY NAME1     @417
  SAY NAME2     @417

COPY ~ImprovedAnvil/resources/creatures/new/S!elemmu.cre~         ~override/S!elemmu.cre~
  SAY NAME1     @418
  SAY NAME2     @418

COPY ~ImprovedAnvil/resources/creatures/new/S!otyugh.cre~         ~override/S!otyugh.cre~
  SAY NAME1     @419
  SAY NAME2     @419

COPY ~ImprovedAnvil/resources/creatures/new/S!otyugd.cre~         ~override/S!otyugd.cre~
  SAY NAME1     @419
  SAY NAME2     @419

COPY ~ImprovedAnvil/resources/creatures/new/S!otyug2.cre~         ~override/S!otyug2.cre~
  SAY NAME1     @419
  SAY NAME2     @419

COPY ~ImprovedAnvil/resources/creatures/new/S!dryad.cre~         ~override/S!dryad.cre~
  SAY NAME1     @420
  SAY NAME2     @420

COPY ~ImprovedAnvil/resources/creatures/new/S!spider.cre~         ~override/S!spider.cre~
  SAY NAME1     @421
  SAY NAME2     @421

COPY ~ImprovedAnvil/resources/creatures/new/S!spgrov.cre~         ~override/S!spgrov.cre~
  SAY NAME1     @421
  SAY NAME2     @421

COPY ~ImprovedAnvil/resources/creatures/new/S!spidrh.cre~         ~override/S!spidrh.cre~
  SAY NAME1     @421
  SAY NAME2     @421

COPY ~ImprovedAnvil/resources/creatures/new/S!spide2.cre~         ~override/S!spide2.cre~
  SAY NAME1     @422
  SAY NAME2     @422

COPY ~ImprovedAnvil/resources/creatures/new/S!spid2h.cre~         ~override/S!spid2h.cre~
  SAY NAME1     @422
  SAY NAME2     @422

COPY ~ImprovedAnvil/resources/creatures/new/S!spide3.cre~         ~override/S!spide3.cre~
  SAY NAME1     @423
  SAY NAME2     @423

COPY ~ImprovedAnvil/resources/creatures/new/S!cat1.cre~         ~override/S!cat1.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat2.cre~         ~override/S!cat2.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat3.cre~         ~override/S!cat3.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat4.cre~         ~override/S!cat4.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat5.cre~         ~override/S!cat5.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat6.cre~         ~override/S!cat6.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat7.cre~         ~override/S!cat7.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat8.cre~         ~override/S!cat8.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!cat9.cre~         ~override/S!cat9.cre~
  SAY NAME1     @424
  SAY NAME2     @424

COPY ~ImprovedAnvil/resources/creatures/new/S!slave.cre~         ~override/S!slave.cre~
  SAY NAME1     @425
  SAY NAME2     @425

COPY ~ImprovedAnvil/resources/creatures/new/S!spideq.cre~         ~override/S!spideq.cre~
  SAY NAME1     @426
  SAY NAME2     @426

COPY ~ImprovedAnvil/resources/creatures/new/S!spidsu.cre~         ~override/S!spidsu.cre~
  SAY NAME1     @427
  SAY NAME2     @427

COPY ~ImprovedAnvil/resources/creatures/new/S!palad.cre~         ~override/S!palad.cre~
  SAY NAME1     @428
  SAY NAME2     @428

COPY ~ImprovedAnvil/resources/creatures/new/S!rune1.cre~         ~override/S!rune1.cre~
  SAY NAME1     @429
  SAY NAME2     @429

COPY ~ImprovedAnvil/resources/creatures/new/S!rune2.cre~         ~override/S!rune2.cre~
  SAY NAME1     @430
  SAY NAME2     @430

COPY ~ImprovedAnvil/resources/creatures/new/S!runef2.cre~         ~override/S!runef2.cre~
  SAY NAME1     @430
  SAY NAME2     @430

COPY ~ImprovedAnvil/resources/creatures/new/S!rune3.cre~         ~override/S!rune3.cre~
  SAY NAME1     @431
  SAY NAME2     @431

COPY ~ImprovedAnvil/resources/creatures/new/S!runef3.cre~         ~override/S!runef3.cre~
  SAY NAME1     @431
  SAY NAME2     @431

COPY ~ImprovedAnvil/resources/creatures/new/S!vipe3.cre~         ~override/S!vipe3.cre~
  SAY NAME1     @432
  SAY NAME2     @432

COPY ~ImprovedAnvil/resources/creatures/new/S!vipe2.cre~         ~override/S!vipe2.cre~
  SAY NAME1     @433
  SAY NAME2     @433

COPY ~ImprovedAnvil/resources/creatures/new/S!vipe1.cre~         ~override/S!vipe1.cre~
  SAY NAME1     @434
  SAY NAME2     @434

COPY ~ImprovedAnvil/resources/creatures/new/S!gypsy.cre~         ~override/S!gypsy.cre~
  SAY NAME1     @435
  SAY NAME2     @435

COPY ~ImprovedAnvil/resources/creatures/new/S!gypgod.cre~         ~override/S!gypgod.cre~
  SAY NAME1     @435
  SAY NAME2     @435

COPY ~ImprovedAnvil/resources/creatures/new/S!rak2.cre~         ~override/S!rak2.cre~
  SAY NAME1     @436
  SAY NAME2     @436

COPY ~ImprovedAnvil/resources/creatures/new/S!rak2g.cre~         ~override/S!rak2g.cre~
  SAY NAME1     @436
  SAY NAME2     @436

COPY ~ImprovedAnvil/resources/creatures/new/S!rak2r.cre~         ~override/S!rak2r.cre~
  SAY NAME1     @436
  SAY NAME2     @436

COPY ~ImprovedAnvil/resources/creatures/new/S!rakgy2.cre~         ~override/S!rakgy2.cre~
  SAY NAME1     @436
  SAY NAME2     @436

COPY ~ImprovedAnvil/resources/creatures/new/S!rak1.cre~         ~override/S!rak1.cre~
  SAY NAME1     @437
  SAY NAME2     @437

COPY ~ImprovedAnvil/resources/creatures/new/S!rak1s.cre~         ~override/S!rak1s.cre~
  SAY NAME1     @437
  SAY NAME2     @437

COPY ~ImprovedAnvil/resources/creatures/new/S!rakgyp.cre~         ~override/S!rakgyp.cre~
  SAY NAME1     @437
  SAY NAME2     @437

COPY ~ImprovedAnvil/resources/creatures/new/S!nrak.cre~         ~override/S!nrak.cre~
  SAY NAME1     @437
  SAY NAME2     @437

COPY ~ImprovedAnvil/resources/creatures/new/S!order.cre~         ~override/S!order.cre~
  SAY NAME1     @438
  SAY NAME2     @438

COPY ~ImprovedAnvil/resources/creatures/new/S!lady1.cre~         ~override/S!lady1.cre~
  SAY NAME1     @439
  SAY NAME2     @439

COPY ~ImprovedAnvil/resources/creatures/new/S!lady2.cre~         ~override/S!lady2.cre~
  SAY NAME1     @440
  SAY NAME2     @440

COPY ~ImprovedAnvil/resources/creatures/new/S!ladygy.cre~         ~override/S!ladygy.cre~
  SAY NAME1     @440
  SAY NAME2     @440

COPY ~ImprovedAnvil/resources/creatures/new/S!ladyde.cre~         ~override/S!ladyde.cre~
  SAY NAME1     @440
  SAY NAME2     @440

COPY ~ImprovedAnvil/resources/creatures/new/S!ladyhe.cre~         ~override/S!ladyhe.cre~
  SAY NAME1     @440
  SAY NAME2     @440

COPY ~ImprovedAnvil/resources/creatures/new/S!ladyud.cre~         ~override/S!ladyud.cre~
  SAY NAME1     @440
  SAY NAME2     @440

COPY ~ImprovedAnvil/resources/creatures/new/S!lady3.cre~         ~override/S!lady3.cre~
  SAY NAME1     @441
  SAY NAME2     @441

COPY ~ImprovedAnvil/resources/creatures/new/S!lady4.cre~         ~override/S!lady4.cre~
  SAY NAME1     @441
  SAY NAME2     @441

COPY ~ImprovedAnvil/resources/creatures/new/S!lady5.cre~         ~override/S!lady5.cre~
  SAY NAME1     @441
  SAY NAME2     @441

COPY ~ImprovedAnvil/resources/creatures/new/S!hlady3.cre~         ~override/S!hlady3.cre~
  SAY NAME1     @441
  SAY NAME2     @441

COPY ~ImprovedAnvil/resources/creatures/new/S!spidbo.cre~         ~override/S!spidbo.cre~
  SAY NAME1     @442
  SAY NAME2     @442

COPY ~ImprovedAnvil/resources/creatures/new/S!spided.cre~         ~override/S!spided.cre~
  SAY NAME1     @442
  SAY NAME2     @442

COPY ~ImprovedAnvil/resources/creatures/new/S!spidet.cre~         ~override/S!spidet.cre~
  SAY NAME1     @442
  SAY NAME2     @442

COPY ~ImprovedAnvil/resources/creatures/new/S!spideg.cre~         ~override/S!spideg.cre~
  SAY NAME1     @442
  SAY NAME2     @442

COPY ~ImprovedAnvil/resources/creatures/new/S!senspi.cre~         ~override/S!senspi.cre~
  SAY NAME1     @442
  SAY NAME2     @442

COPY ~ImprovedAnvil/resources/creatures/new/S!spideh.cre~         ~override/S!spideh.cre~
  SAY NAME1     @442
  SAY NAME2     @442

COPY ~ImprovedAnvil/resources/creatures/new/S!spidgr.cre~         ~override/S!spidgr.cre~
  SAY NAME1     @442
  SAY NAME2     @442

COPY ~ImprovedAnvil/resources/creatures/new/S!pasha.cre~         ~override/S!pasha.cre~
  SAY NAME1     @443
  SAY NAME2     @443

COPY ~ImprovedAnvil/resources/creatures/new/S!pasha2.cre~         ~override/S!pasha2.cre~
  SAY NAME1     @443
  SAY NAME2     @443

COPY ~ImprovedAnvil/resources/creatures/new/S!limak.cre~         ~override/S!limak.cre~
  SAY NAME1     @444
  SAY NAME2     @444

COPY ~ImprovedAnvil/resources/creatures/new/S!nishru.cre~         ~override/S!nishru.cre~
  SAY NAME1     @445
  SAY NAME2     @445

COPY ~ImprovedAnvil/resources/creatures/new/S!efreet.cre~         ~override/S!efreet.cre~
  SAY NAME1     @446
  SAY NAME2     @446

COPY ~ImprovedAnvil/resources/creatures/new/S!efree2.cre~         ~override/S!efree2.cre~
  SAY NAME1     @446
  SAY NAME2     @446

COPY ~ImprovedAnvil/resources/creatures/new/S!roshan.cre~         ~override/S!roshan.cre~
  SAY NAME1     @447
  SAY NAME2     @447

COPY ~ImprovedAnvil/resources/creatures/new/S!rosha2.cre~         ~override/S!rosha2.cre~
  SAY NAME1     @447
  SAY NAME2     @447

COPY ~ImprovedAnvil/resources/creatures/new/S!trollk.cre~         ~override/S!trollk.cre~
  SAY NAME1     @448
  SAY NAME2     @448

COPY ~ImprovedAnvil/resources/creatures/new/S!trollq.cre~         ~override/S!trollq.cre~
  SAY NAME1     @449
  SAY NAME2     @449

COPY ~ImprovedAnvil/resources/creatures/new/S!auriel.cre~         ~override/S!auriel.cre~
  SAY NAME1     @450
  SAY NAME2     @450

COPY ~ImprovedAnvil/resources/creatures/new/S!aurie2.cre~         ~override/S!aurie2.cre~
  SAY NAME1     @450
  SAY NAME2     @450

COPY ~ImprovedAnvil/resources/creatures/new/S!aurie3.cre~         ~override/S!aurie3.cre~
  SAY NAME1     @450
  SAY NAME2     @450

COPY ~ImprovedAnvil/resources/creatures/new/S!dopple.cre~         ~override/S!dopple.cre~
  SAY NAME1     @451
  SAY NAME2     @451

COPY ~ImprovedAnvil/resources/creatures/new/S!domran.cre~         ~override/S!domran.cre~
  SAY NAME1     @452
  SAY NAME2     @452

COPY ~ImprovedAnvil/resources/creatures/new/S!dompal.cre~         ~override/S!dompal.cre~
  SAY NAME1     @453
  SAY NAME2     @453

COPY ~ImprovedAnvil/resources/creatures/new/S!killer.cre~         ~override/S!killer.cre~
  SAY NAME1     @454
  SAY NAME2     @454

COPY ~ImprovedAnvil/resources/creatures/new/S!illgol.cre~         ~override/S!illgol.cre~
  SAY NAME1     @455
  SAY NAME2     @455

COPY ~ImprovedAnvil/resources/creatures/new/S!illvam.cre~         ~override/S!illvam.cre~
  SAY NAME1     @456
  SAY NAME2     @456

COPY ~ImprovedAnvil/resources/creatures/new/S!runef.cre~         ~override/S!runef.cre~
  SAY NAME1     @457
  SAY NAME2     @457

COPY ~ImprovedAnvil/resources/creatures/new/S!amarie.cre~         ~override/S!amarie.cre~
  SAY NAME1     @458
  SAY NAME2     @458

COPY ~ImprovedAnvil/resources/creatures/new/S!amari2.cre~         ~override/S!amari2.cre~
  SAY NAME1     @458
  SAY NAME2     @458

COPY ~ImprovedAnvil/resources/creatures/new/S!ammar.cre~         ~override/S!ammar.cre~
  SAY NAME1     @459
  SAY NAME2     @459

COPY ~ImprovedAnvil/resources/creatures/new/S!ammar2.cre~         ~override/S!ammar2.cre~
  SAY NAME1     @460
  SAY NAME2     @460

COPY ~ImprovedAnvil/resources/creatures/new/S!senpet.cre~         ~override/S!senpet.cre~
  SAY NAME1     @461
  SAY NAME2     @461

COPY ~ImprovedAnvil/resources/creatures/new/S!salam.cre~         ~override/S!salam.cre~
  SAY NAME1     @462
  SAY NAME2     @462

COPY ~ImprovedAnvil/resources/creatures/new/S!salam2.cre~         ~override/S!salam2.cre~
  SAY NAME1     @462
  SAY NAME2     @462

COPY ~ImprovedAnvil/resources/creatures/new/S!salam3.cre~         ~override/S!salam3.cre~
  SAY NAME1     @462
  SAY NAME2     @462

COPY ~ImprovedAnvil/resources/creatures/new/S!salam4.cre~         ~override/S!salam4.cre~
  SAY NAME1     @462
  SAY NAME2     @462

COPY ~ImprovedAnvil/resources/creatures/new/S!ultgg1.cre~         ~override/S!ultgg1.cre~
  SAY NAME1     @463
  SAY NAME2     @463

COPY ~ImprovedAnvil/resources/creatures/new/S!ultgg2.cre~         ~override/S!ultgg2.cre~
  SAY NAME1     @463
  SAY NAME2     @463

COPY ~ImprovedAnvil/resources/creatures/new/S!ultgol.cre~         ~override/S!ultgol.cre~
  SAY NAME1     @463
  SAY NAME2     @463

COPY ~ImprovedAnvil/resources/creatures/new/S!ultgoa.cre~         ~override/S!ultgoa.cre~
  SAY NAME1     @463
  SAY NAME2     @463

COPY ~ImprovedAnvil/resources/creatures/new/S!ultgod.cre~         ~override/S!ultgod.cre~
  SAY NAME1     @463
  SAY NAME2     @463

COPY ~ImprovedAnvil/resources/creatures/new/S!mitgol.cre~         ~override/S!mitgol.cre~
  SAY NAME1     @464
  SAY NAME2     @464

COPY ~ImprovedAnvil/resources/creatures/new/S!spidwh.cre~         ~override/S!spidwh.cre~
  SAY NAME1     @466
  SAY NAME2     @466

COPY ~ImprovedAnvil/resources/creatures/new/S!spidwf.cre~         ~override/S!spidwf.cre~
  SAY NAME1     @466
  SAY NAME2     @466

COPY ~ImprovedAnvil/resources/creatures/new/S!spidwd.cre~         ~override/S!spidwd.cre~
  SAY NAME1     @466
  SAY NAME2     @466

COPY ~ImprovedAnvil/resources/creatures/new/S!spidwr.cre~         ~override/S!spidwr.cre~
  SAY NAME1     @466
  SAY NAME2     @466

COPY ~ImprovedAnvil/resources/creatures/new/S!spiwd2.cre~         ~override/S!spiwd2.cre~
  SAY NAME1     @466
  SAY NAME2     @466

COPY ~ImprovedAnvil/resources/creatures/new/S!spiwd3.cre~         ~override/S!spiwd3.cre~
  SAY NAME1     @466
  SAY NAME2     @466

COPY ~ImprovedAnvil/resources/creatures/new/S!spidpp.cre~         ~override/S!spidpp.cre~
  SAY NAME1     @466
  SAY NAME2     @466

COPY ~ImprovedAnvil/resources/creatures/new/S!gormis.cre~         ~override/S!gormis.cre~
  SAY NAME1     @467
  SAY NAME2     @467

COPY ~ImprovedAnvil/resources/creatures/new/S!amber.cre~         ~override/S!amber.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!amber2.cre~         ~override/S!amber2.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!amber3.cre~         ~override/S!amber3.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!amber4.cre~         ~override/S!amber4.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!amberd.cre~         ~override/S!amberd.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!amberg.cre~         ~override/S!amberg.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!ambers.cre~         ~override/S!ambers.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!amberl.cre~         ~override/S!amberl.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!ambere.cre~         ~override/S!ambere.cre~
  SAY NAME1     @468
  SAY NAME2     @468

COPY ~ImprovedAnvil/resources/creatures/new/S!slasp1.cre~         ~override/S!slasp1.cre~
  SAY NAME1     @469
  SAY NAME2     @469

COPY ~ImprovedAnvil/resources/creatures/new/S!slasp2.cre~         ~override/S!slasp2.cre~
  SAY NAME1     @469
  SAY NAME2     @469

COPY ~ImprovedAnvil/resources/creatures/new/S!bdevil.cre~         ~override/S!bdevil.cre~
  SAY NAME1     @470
  SAY NAME2     @470

COPY ~ImprovedAnvil/resources/creatures/new/S!bdevit.cre~         ~override/S!bdevit.cre~
  SAY NAME1     @470
  SAY NAME2     @470

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch1.cre~         ~override/S!grlch1.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch2.cre~         ~override/S!grlch2.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch3.cre~         ~override/S!grlch3.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch4.cre~         ~override/S!grlch4.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch5.cre~         ~override/S!grlch5.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch6.cre~         ~override/S!grlch6.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch7.cre~         ~override/S!grlch7.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!grlch8.cre~         ~override/S!grlch8.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!glchra.cre~         ~override/S!glchra.cre~
  SAY NAME1     @471
  SAY NAME2     @471

COPY ~ImprovedAnvil/resources/creatures/new/S!mlar.cre~         ~override/S!mlar.cre~
  SAY NAME1     @472
  SAY NAME2     @472

COPY ~ImprovedAnvil/resources/creatures/new/S!hrack.cre~         ~override/S!hrack.cre~
  SAY NAME1     @473
  SAY NAME2     @473

COPY ~ImprovedAnvil/resources/creatures/new/S!runewa.cre~         ~override/S!runewa.cre~
  SAY NAME1     @475
  SAY NAME2     @475

COPY ~ImprovedAnvil/resources/creatures/new/S!phoun2.cre~         ~override/S!phoun2.cre~
  SAY NAME1     @477
  SAY NAME2     @477

COPY ~ImprovedAnvil/resources/creatures/new/S!rakp.cre~         ~override/S!rakp.cre~
  SAY NAME1     @478
  SAY NAME2     @478

COPY ~ImprovedAnvil/resources/creatures/new/S!orcus.cre~         ~override/S!orcus.cre~
  SAY NAME1     @479
  SAY NAME2     @479

COPY ~ImprovedAnvil/resources/creatures/new/S!supgol.cre~         ~override/S!supgol.cre~
  SAY NAME1     @480
  SAY NAME2     @480

COPY ~ImprovedAnvil/resources/creatures/new/S!supgow.cre~         ~override/S!supgow.cre~
  SAY NAME1     @480
  SAY NAME2     @480

COPY ~ImprovedAnvil/resources/creatures/new/S!tanthf.cre~         ~override/S!tanthf.cre~
  SAY NAME1     @481
  SAY NAME2     @481

COPY ~ImprovedAnvil/resources/creatures/new/S!ancest.cre~         ~override/S!ancest.cre~
  SAY NAME1     @484
  SAY NAME2     @484

COPY ~ImprovedAnvil/resources/creatures/new/S!spy2.cre~         ~override/S!spy2.cre~
  SAY NAME1     @485
  SAY NAME2     @485

COPY ~ImprovedAnvil/resources/creatures/new/S!cghost.cre~         ~override/S!cghost.cre~
  SAY NAME1     @486
  SAY NAME2     @486

COPY ~ImprovedAnvil/resources/creatures/new/S!cghos2.cre~         ~override/S!cghos2.cre~
  SAY NAME1     @486
  SAY NAME2     @486

COPY ~ImprovedAnvil/resources/creatures/new/S!dracol.cre~         ~override/S!dracol.cre~
  SAY NAME1     @487
  SAY NAME2     @487
  WRITE_LONG 0x28 IDS_OF_SYMBOL (animate MO_DRACOLICH_NWN)

COPY ~ImprovedAnvil/resources/creatures/new/S!shadow.cre~         ~override/S!shadow.cre~
  SAY NAME1     @488
  SAY NAME2     @488

COPY ~ImprovedAnvil/resources/creatures/new/S!shado2.cre~         ~override/S!shado2.cre~
  SAY NAME1     @488
  SAY NAME2     @488

COPY ~ImprovedAnvil/resources/creatures/new/S!gghost.cre~         ~override/S!gghost.cre~
  SAY NAME1     @489
  SAY NAME2     @489

COPY ~ImprovedAnvil/resources/creatures/new/S!kpvipe.cre~         ~override/S!kpvipe.cre~
  SAY NAME1     @490
  SAY NAME2     @490

COPY ~ImprovedAnvil/resources/creatures/new/S!swansu.cre~         ~override/S!swansu.cre~
  SAY NAME1     @491
  SAY NAME2     @491

COPY ~ImprovedAnvil/resources/creatures/new/S!swanme.cre~         ~override/S!swanme.cre~
  SAY NAME1     @491
  SAY NAME2     @491

COPY ~ImprovedAnvil/resources/creatures/new/S!draggr.cre~         ~override/S!draggr.cre~
  SAY NAME1     @492
  SAY NAME2     @492

COPY ~ImprovedAnvil/resources/creatures/new/S!rat1.cre~         ~override/S!rat1.cre~
  SAY NAME1     @494
  SAY NAME2     @494

COPY ~ImprovedAnvil/resources/creatures/new/S!rat2.cre~         ~override/S!rat2.cre~
  SAY NAME1     @495
  SAY NAME2     @495

COPY ~ImprovedAnvil/resources/creatures/new/S!shados.cre~         ~override/S!shados.cre~
  SAY NAME1     @496
  SAY NAME2     @496

COPY ~ImprovedAnvil/resources/creatures/new/S!gswan.cre~         ~override/S!gswan.cre~
  SAY NAME1     @497
  SAY NAME2     @497

COPY ~ImprovedAnvil/resources/creatures/new/S!swanq.cre~         ~override/S!swanq.cre~
  SAY NAME1     @498
  SAY NAME2     @498

COPY ~ImprovedAnvil/resources/creatures/new/S!twist1.cre~         ~override/S!twist1.cre~
  SAY NAME1     @499
  SAY NAME2     @499

COPY ~ImprovedAnvil/resources/creatures/new/S!twist2.cre~         ~override/S!twist2.cre~
  SAY NAME1     @499
  SAY NAME2     @499

COPY ~ImprovedAnvil/resources/creatures/new/S!twist3.cre~         ~override/S!twist3.cre~
  SAY NAME1     @499
  SAY NAME2     @499

COPY ~ImprovedAnvil/resources/creatures/new/S!twist4.cre~         ~override/S!twist4.cre~
  SAY NAME1     @499
  SAY NAME2     @499

COPY ~ImprovedAnvil/resources/creatures/new/S!twist5.cre~         ~override/S!twist5.cre~
  SAY NAME1     @499
  SAY NAME2     @499

COPY ~ImprovedAnvil/resources/creatures/new/S!twist6.cre~         ~override/S!twist6.cre~
  SAY NAME1     @499
  SAY NAME2     @499

COPY ~ImprovedAnvil/resources/creatures/new/S!malbar.cre~         ~override/S!malbar.cre~
  SAY NAME1     @11000
  SAY NAME2     @11000

COPY ~ImprovedAnvil/resources/creatures/new/S!malba2.cre~         ~override/S!malba2.cre~
  SAY NAME1     @11000
  SAY NAME2     @11000

COPY ~ImprovedAnvil/resources/creatures/new/S!elegos.cre~         ~override/S!elegos.cre~
  SAY NAME1     @11001
  SAY NAME2     @11001

COPY ~ImprovedAnvil/resources/creatures/new/S!gelego.cre~         ~override/S!gelego.cre~
  SAY NAME1     @11001
  SAY NAME2     @11001

COPY ~ImprovedAnvil/resources/creatures/new/S!gelegs.cre~         ~override/S!gelegs.cre~
  SAY NAME1     @11001
  SAY NAME2     @11001

COPY ~ImprovedAnvil/resources/creatures/new/S!elegoa.cre~         ~override/S!elegoa.cre~
  SAY NAME1     @11001
  SAY NAME2     @11001

COPY ~ImprovedAnvil/resources/creatures/new/S!orvam.cre~         ~override/S!orvam.cre~
  SAY NAME1     @11002
  SAY NAME2     @11002

COPY ~ImprovedAnvil/resources/creatures/new/S!masvam.cre~         ~override/S!masvam.cre~
  SAY NAME1     @11002
  SAY NAME2     @11002

COPY ~ImprovedAnvil/resources/creatures/new/S!nevm1.cre~         ~override/S!nevm1.cre~
  SAY NAME1     @11003
  SAY NAME2     @11003

COPY ~ImprovedAnvil/resources/creatures/new/S!vamwis.cre~         ~override/S!vamwis.cre~
  SAY NAME1     @11003
  SAY NAME2     @11003

COPY ~ImprovedAnvil/resources/creatures/new/S!gempp.cre~         ~override/S!gempp.cre~
  SAY NAME1     @11004
  SAY NAME2     @11004

COPY ~ImprovedAnvil/resources/creatures/new/S!skelg1.cre~         ~override/S!skelg1.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelg2.cre~         ~override/S!skelg2.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelg3.cre~         ~override/S!skelg3.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelg4.cre~         ~override/S!skelg4.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelg5.cre~         ~override/S!skelg5.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelg6.cre~         ~override/S!skelg6.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelgr.cre~         ~override/S!skelgr.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo1.cre~         ~override/S!skelo1.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo2.cre~         ~override/S!skelo2.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo3.cre~         ~override/S!skelo3.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo4.cre~         ~override/S!skelo4.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo5.cre~         ~override/S!skelo5.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo6.cre~         ~override/S!skelo6.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo7.cre~         ~override/S!skelo7.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelo8.cre~         ~override/S!skelo8.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!skelre.cre~         ~override/S!skelre.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!bongof.cre~         ~override/S!bongof.cre~
  SAY NAME1     @11007
  SAY NAME2     @11007

COPY ~ImprovedAnvil/resources/creatures/new/S!bongol.cre~         ~override/S!bongol.cre~
  SAY NAME1     @11007
  SAY NAME2     @11007

COPY ~ImprovedAnvil/resources/creatures/new/S!bonrnd.cre~         ~override/S!bonrnd.cre~
  SAY NAME1     @11007
  SAY NAME2     @11007

COPY ~ImprovedAnvil/resources/creatures/new/S!cangua.cre~         ~override/S!cangua.cre~
  SAY NAME1     @11008
  SAY NAME2     @11008

COPY ~ImprovedAnvil/resources/creatures/new/S!belgua.cre~         ~override/S!belgua.cre~
  SAY NAME1     @11008
  SAY NAME2     @11008

COPY ~ImprovedAnvil/resources/creatures/new/S!sahvip.cre~         ~override/S!sahvip.cre~
  SAY NAME1     @11009
  SAY NAME2     @11009

COPY ~ImprovedAnvil/resources/creatures/new/S!crypt.cre~         ~override/S!crypt.cre~
  SAY NAME1     @11010
  SAY NAME2     @11010

COPY ~ImprovedAnvil/resources/creatures/new/S!bolich.cre~         ~override/S!bolich.cre~
  SAY NAME1     @11011
  SAY NAME2     @11011

COPY ~ImprovedAnvil/resources/creatures/new/S!bomin1.cre~         ~override/S!bomin1.cre~
  SAY NAME1     @11012
  SAY NAME2     @11012

COPY ~ImprovedAnvil/resources/creatures/new/S!bomin2.cre~         ~override/S!bomin2.cre~
  SAY NAME1     @11013
  SAY NAME2     @11013

COPY ~ImprovedAnvil/resources/creatures/new/S!spy3.cre~         ~override/S!spy3.cre~
  SAY NAME1     @11014
  SAY NAME2     @11014

COPY ~ImprovedAnvil/resources/creatures/new/S!skelwl.cre~         ~override/S!skelwl.cre~
  SAY NAME1     @11015
  SAY NAME2     @11015

COPY ~ImprovedAnvil/resources/creatures/new/S!skelfi.cre~         ~override/S!skelfi.cre~
  SAY NAME1     @11015
  SAY NAME2     @11015

COPY ~ImprovedAnvil/resources/creatures/new/S!skelw2.cre~         ~override/S!skelw2.cre~
  SAY NAME1     @11015
  SAY NAME2     @11015

COPY ~ImprovedAnvil/resources/creatures/new/S!gtwist.cre~         ~override/S!gtwist.cre~
  SAY NAME1     @11017
  SAY NAME2     @11017

COPY ~ImprovedAnvil/resources/creatures/new/S!oldone.cre~         ~override/S!oldone.cre~
  SAY NAME1     @11020
  SAY NAME2     @11020

COPY ~ImprovedAnvil/resources/creatures/new/S!oldon2.cre~         ~override/S!oldon2.cre~
  SAY NAME1     @11021
  SAY NAME2     @11021

COPY ~ImprovedAnvil/resources/creatures/new/S!squi02.cre~         ~override/S!squi02.cre~
  SAY NAME1     @11022
  SAY NAME2     @11022

COPY ~ImprovedAnvil/resources/creatures/new/S!squi03.cre~         ~override/S!squi03.cre~
  SAY NAME1     @11023
  SAY NAME2     @11023

COPY ~ImprovedAnvil/resources/creatures/new/S!squi04.cre~         ~override/S!squi04.cre~
  SAY NAME1     @11023
  SAY NAME2     @11023

COPY ~ImprovedAnvil/resources/creatures/new/S!sqassa.cre~         ~override/S!sqassa.cre~
  SAY NAME1     @11024
  SAY NAME2     @11024

COPY ~ImprovedAnvil/resources/creatures/new/S!sqass2.cre~         ~override/S!sqass2.cre~
  SAY NAME1     @11024
  SAY NAME2     @11024

COPY ~ImprovedAnvil/resources/creatures/new/S!sqass3.cre~         ~override/S!sqass3.cre~
  SAY NAME1     @11024
  SAY NAME2     @11024

COPY ~ImprovedAnvil/resources/creatures/new/S!sqass4.cre~         ~override/S!sqass4.cre~
  SAY NAME1     @11024
  SAY NAME2     @11024

COPY ~ImprovedAnvil/resources/creatures/new/S!sqass5.cre~         ~override/S!sqass5.cre~
  SAY NAME1     @11024
  SAY NAME2     @11024

COPY ~ImprovedAnvil/resources/creatures/new/S!demarc.cre~         ~override/S!demarc.cre~
  SAY NAME1     @11025
  SAY NAME2     @11025

COPY ~ImprovedAnvil/resources/creatures/new/S!morid1.cre~         ~override/S!morid1.cre~
  SAY NAME1     @11026
  SAY NAME2     @11026

COPY ~ImprovedAnvil/resources/creatures/new/S!morid2.cre~         ~override/S!morid2.cre~
  SAY NAME1     @11026
  SAY NAME2     @11026

COPY ~ImprovedAnvil/resources/creatures/new/S!force1.cre~         ~override/S!force1.cre~
  SAY NAME1     @11027
  SAY NAME2     @11027

COPY ~ImprovedAnvil/resources/creatures/new/S!force2.cre~         ~override/S!force2.cre~
  SAY NAME1     @11027
  SAY NAME2     @11027

COPY ~ImprovedAnvil/resources/creatures/new/S!woogol.cre~         ~override/S!woogol.cre~
  SAY NAME1     @11028
  SAY NAME2     @11028

COPY ~ImprovedAnvil/resources/creatures/new/S!woogo1.cre~         ~override/S!woogo1.cre~
  SAY NAME1     @11028
  SAY NAME2     @11028

COPY ~ImprovedAnvil/resources/creatures/new/S!woogo2.cre~         ~override/S!woogo2.cre~
  SAY NAME1     @11028
  SAY NAME2     @11028

COPY ~ImprovedAnvil/resources/creatures/new/S!woogo3.cre~         ~override/S!woogo3.cre~
  SAY NAME1     @11028
  SAY NAME2     @11028

COPY ~ImprovedAnvil/resources/creatures/new/S!woogo4.cre~         ~override/S!woogo4.cre~
  SAY NAME1     @11028
  SAY NAME2     @11028

COPY ~ImprovedAnvil/resources/creatures/new/S!spy4.cre~         ~override/S!spy4.cre~
  SAY NAME1     @11029
  SAY NAME2     @11029

COPY ~ImprovedAnvil/resources/creatures/new/S!ntroll.cre~         ~override/S!ntroll.cre~
  SAY NAME1     @11031
  SAY NAME2     @11031

COPY ~ImprovedAnvil/resources/creatures/new/S!ntrol2.cre~         ~override/S!ntrol2.cre~
  SAY NAME1     @11031
  SAY NAME2     @11031

COPY ~ImprovedAnvil/resources/creatures/new/S!kuoduk.cre~         ~override/S!kuoduk.cre~
  SAY NAME1     @11034
  SAY NAME2     @11034

COPY ~ImprovedAnvil/resources/creatures/new/S!kuodu2.cre~         ~override/S!kuodu2.cre~
  SAY NAME1     @11034
  SAY NAME2     @11034

COPY ~ImprovedAnvil/resources/creatures/new/S!trolsu.cre~         ~override/S!trolsu.cre~
  SAY NAME1     @11035
  SAY NAME2     @11035

COPY ~ImprovedAnvil/resources/creatures/new/S!anacsu.cre~         ~override/S!anacsu.cre~
  SAY NAME1     @11036
  SAY NAME2     @11036

COPY ~ImprovedAnvil/resources/creatures/new/S!smilsu.cre~         ~override/S!smilsu.cre~
  SAY NAME1     @11037
  SAY NAME2     @11037

COPY ~ImprovedAnvil/resources/creatures/new/S!swanfa.cre~         ~override/S!swanfa.cre~
  SAY NAME1     @11038
  SAY NAME2     @11038

COPY ~ImprovedAnvil/resources/creatures/new/S!rngspi.cre~         ~override/S!rngspi.cre~
  SAY NAME1     @11039
  SAY NAME2     @11039

COPY ~ImprovedAnvil/resources/creatures/new/S!wetlan.cre~         ~override/S!wetlan.cre~
  SAY NAME1     @11039
  SAY NAME2     @11039

COPY ~ImprovedAnvil/resources/creatures/new/S!vipmir.cre~         ~override/S!vipmir.cre~
  SAY NAME1     @11040
  SAY NAME2     @11040

COPY ~ImprovedAnvil/resources/creatures/new/S!vipmi1.cre~         ~override/S!vipmi1.cre~
  SAY NAME1     @11040
  SAY NAME2     @11040

COPY ~ImprovedAnvil/resources/creatures/new/S!windm1.cre~         ~override/S!windm1.cre~
  SAY NAME1     @11041
  SAY NAME2     @11041

COPY ~ImprovedAnvil/resources/creatures/new/S!windmi.cre~         ~override/S!windmi.cre~
  SAY NAME1     @11042
  SAY NAME2     @11042

COPY ~ImprovedAnvil/resources/creatures/new/S!spidmi.cre~         ~override/S!spidmi.cre~
  SAY NAME1     @11043
  SAY NAME2     @11043

COPY ~ImprovedAnvil/resources/creatures/new/S!skelmi.cre~         ~override/S!skelmi.cre~
  SAY NAME1     @11044
  SAY NAME2     @11044

COPY ~ImprovedAnvil/resources/creatures/new/S!spidwm.cre~         ~override/S!spidwm.cre~
  SAY NAME1     @11045
  SAY NAME2     @11045

COPY ~ImprovedAnvil/resources/creatures/new/S!mircre.cre~         ~override/S!mircre.cre~
  SAY NAME1     @11046
  SAY NAME2     @11046

COPY ~ImprovedAnvil/resources/creatures/new/S!poncre.cre~         ~override/S!poncre.cre~
  SAY NAME1     @11047
  SAY NAME2     @11047

COPY ~ImprovedAnvil/resources/creatures/new/S!shadm1.cre~         ~override/S!shadm1.cre~
  SAY NAME1     @11048
  SAY NAME2     @11048

COPY ~ImprovedAnvil/resources/creatures/new/S!shadmi.cre~         ~override/S!shadmi.cre~
  SAY NAME1     @11048
  SAY NAME2     @11048

COPY ~ImprovedAnvil/resources/creatures/new/S!gelem1.cre~         ~override/S!gelem1.cre~
  SAY NAME1     @11049
  SAY NAME2     @11049

COPY ~ImprovedAnvil/resources/creatures/new/S!mircha.cre~         ~override/S!mircha.cre~
  SAY NAME1     @11050
  SAY NAME2     @11050

COPY ~ImprovedAnvil/resources/creatures/new/S!mirrng.cre~         ~override/S!mirrng.cre~
  SAY NAME1     @11051
  SAY NAME2     @11051

COPY ~ImprovedAnvil/resources/creatures/new/S!drsoul.cre~         ~override/S!drsoul.cre~
  SAY NAME1     @11052
  SAY NAME2     @11052

COPY ~ImprovedAnvil/resources/creatures/new/S!mom.cre~         ~override/S!mom.cre~
  SAY NAME1     @11053
  SAY NAME2     @11053

COPY ~ImprovedAnvil/resources/creatures/new/S!momd.cre~         ~override/S!momd.cre~
  SAY NAME1     @11053
  SAY NAME2     @11053

COPY ~ImprovedAnvil/resources/creatures/new/S!inqui1.cre~         ~override/S!inqui1.cre~
  SAY NAME1     @11054
  SAY NAME2     @11054

COPY ~ImprovedAnvil/resources/creatures/new/S!inqui2.cre~         ~override/S!inqui2.cre~
  SAY NAME1     @11054
  SAY NAME2     @11054

COPY ~ImprovedAnvil/resources/creatures/new/S!inqui3.cre~         ~override/S!inqui3.cre~
  SAY NAME1     @11054
  SAY NAME2     @11054

COPY ~ImprovedAnvil/resources/creatures/new/S!inqui4.cre~         ~override/S!inqui4.cre~
  SAY NAME1     @11054
  SAY NAME2     @11054

COPY ~ImprovedAnvil/resources/creatures/new/S!sencoi.cre~         ~override/S!sencoi.cre~
  SAY NAME1     @11055
  SAY NAME2     @11055

COPY ~ImprovedAnvil/resources/creatures/new/S!sengem.cre~         ~override/S!sengem.cre~
  SAY NAME1     @11055
  SAY NAME2     @11055

COPY ~ImprovedAnvil/resources/creatures/new/S!edeswa.cre~         ~override/S!edeswa.cre~
  SAY NAME1     @11056
  SAY NAME2     @11056

COPY ~ImprovedAnvil/resources/creatures/new/s!libmag.cre~         ~override/s!libmag.cre~
  SAY NAME1     @11111
  SAY NAME2     @11111

COPY ~ImprovedAnvil/resources/creatures/new/s!iguard.cre~         ~override/s!iguard.cre~
  SAY NAME1     @11113
  SAY NAME2     @11113

COPY ~ImprovedAnvil/resources/creatures/new/S!beggar.cre~         ~override/S!beggar.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!icego1.cre~         ~override/S!icego1.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!icego2.cre~         ~override/S!icego2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!icegol.cre~         ~override/S!icegol.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!icegoa.cre~         ~override/S!icegoa.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!icegor.cre~         ~override/S!icegor.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!delon1.cre~         ~override/S!delon1.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!delon2.cre~         ~override/S!delon2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!delon3.cre~         ~override/S!delon3.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!delon4.cre~         ~override/S!delon4.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!girl1.cre~         ~override/S!girl1.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!girl2.cre~         ~override/S!girl2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!knight.cre~         ~override/S!knight.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!knigh2.cre~         ~override/S!knigh2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!knigh3.cre~         ~override/S!knigh3.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!enchan.cre~         ~override/S!enchan.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!illusi.cre~         ~override/S!illusi.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!dwarf.cre~         ~override/S!dwarf.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!spy1.cre~         ~override/S!spy1.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!mageco.cre~         ~override/S!mageco.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!balor.cre~         ~override/S!balor.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!gclay.cre~         ~override/S!gclay.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!gstone.cre~         ~override/S!gstone.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!messen.cre~         ~override/S!messen.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!block.cre~         ~override/S!block.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!block2.cre~         ~override/S!block2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!block3.cre~         ~override/S!block3.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!blockd.cre~         ~override/S!blockd.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!slassa.cre~         ~override/S!slassa.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!looker.cre~         ~override/S!looker.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!looke2.cre~         ~override/S!looke2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!mekear.cre~         ~override/S!mekear.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!shlich.cre~         ~override/S!shlich.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!pirmur.cre~         ~override/S!pirmur.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!droww.cre~         ~override/S!droww.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!mistho.cre~         ~override/S!mistho.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!blocko.cre~         ~override/S!blocko.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!avatar.cre~         ~override/S!avatar.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!acton2.cre~         ~override/S!acton2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!timemf.cre~         ~override/S!timemf.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!timema.cre~         ~override/S!timema.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!youngb.cre~         ~override/S!youngb.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!youngl.cre~         ~override/S!youngl.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!balor2.cre~         ~override/S!balor2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!balorf.cre~         ~override/S!balorf.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!balorh.cre~         ~override/S!balorh.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!trolic.cre~         ~override/S!trolic.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!trolr.cre~         ~override/S!trolr.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!yuansu.cre~         ~override/S!yuansu.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!salasu.cre~         ~override/S!salasu.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!minosu.cre~         ~override/S!minosu.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!spy5.cre~         ~override/S!spy5.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!icbonr.cre~         ~override/S!icbonr.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!drofo4.cre~         ~override/S!drofo4.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!drofo3.cre~         ~override/S!drofo3.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!spyran.cre~         ~override/S!spyran.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!spy6.cre~         ~override/S!spy6.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!squi05.cre~         ~override/S!squi05.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!spy7.cre~         ~override/S!spy7.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!blockm.cre~         ~override/S!blockm.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!spy8.cre~         ~override/S!spy8.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!belch.cre~         ~override/S!belch.cre~
  SAY NAME1     @10242
  SAY NAME2     @10242

COPY ~ImprovedAnvil/resources/creatures/new/S!kazuul.cre~         ~override/S!kazuul.cre~
  SAY NAME1     @10253
  SAY NAME2     @10253

COPY ~ImprovedAnvil/resources/creatures/new/S!kargot.cre~         ~override/S!kargot.cre~
  SAY NAME1     @10254
  SAY NAME2     @10254

COPY ~ImprovedAnvil/resources/creatures/new/S!varg.cre~         ~override/S!varg.cre~
  SAY NAME1     @10255
  SAY NAME2     @10255

COPY ~ImprovedAnvil/resources/creatures/new/S!dembom.cre~         ~override/S!dembom.cre~
  SAY NAME1     @10276
  SAY NAME2     @10276

COPY ~ImprovedAnvil/resources/creatures/new/S!rozvan.cre~         ~override/S!rozvan.cre~
  SAY NAME1     @10256
  SAY NAME2     @10256
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~ANVIL_GHOUL_QUEEN~))

COPY ~ImprovedAnvil/resources/creatures/new/S!nulong.cre~         ~override/S!nulong.cre~
  SAY NAME1     @10257
  SAY NAME2     @10257

COPY ~ImprovedAnvil/resources/creatures/new/S!clhun1.cre~ ~override/S!clhun1.cre~
     ~ImprovedAnvil/resources/creatures/new/S!clhun2.cre~ ~override/S!clhun2.cre~
     ~ImprovedAnvil/resources/creatures/new/S!clhun3.cre~ ~override/S!clhun3.cre~
     ~ImprovedAnvil/resources/creatures/new/S!clhun4.cre~ ~override/S!clhun4.cre~
  SAY NAME1     @10240
  SAY NAME2     @10240
  WRITE_ASCII 0x248 ~S!CLHUN~ #8

COPY ~ImprovedAnvil/resources/creatures/new/S!tanncr.cre~         ~override/S!tanncr.cre~
  SAY NAME1     @10249
  SAY NAME2     @10249

COPY ~ImprovedAnvil/resources/creatures/new/S!helma1.cre~         ~override/S!helma1.cre~
  SAY NAME1     @10289
  SAY NAME2     @10289

COPY ~ImprovedAnvil/resources/creatures/new/S!xp.cre~ ~override/S!xp.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!roec01.cre~ ~override/S!roec01.cre~
  SAY NAME1     @5214
  SAY NAME2     @5214

COPY ~ImprovedAnvil/resources/creatures/new/S!mflich.cre~ ~override/S!mflich.cre~
  SAY NAME1     @5215
  SAY NAME2     @5215

COPY ~ImprovedAnvil/resources/creatures/new/S!mfvamp.cre~ ~override/S!mfvamp.cre~
  SAY NAME1     @5216
  SAY NAME2     @5216

COPY ~ImprovedAnvil/resources/creatures/new/S!crogua.cre~ ~override/S!crogua.cre~
  SAY NAME1     @5217
  SAY NAME2     @5217

COPY ~ImprovedAnvil/resources/creatures/new/S!weagua.cre~ ~override/S!weagua.cre~
  SAY NAME1     @5218
  SAY NAME2     @5218

COPY ~ImprovedAnvil/resources/creatures/new/S!lvarg.cre~ ~override/S!lvarg.cre~
  SAY NAME1     @11108
  SAY NAME2     @11108

COPY ~ImprovedAnvil/resources/creatures/new/S!devag.cre~ ~override/S!devag.cre~
  SAY NAME1     @11138
  SAY NAME2     @11138

COPY ~ImprovedAnvil/resources/creatures/new/S!devae.cre~ ~override/S!devae.cre~
  SAY NAME1     @11139
  SAY NAME2     @11139

COPY ~ImprovedAnvil/resources/creatures/new/S!sskelm.cre~ ~override/S!sskelm.cre~
  SAY NAME1     @11005
  SAY NAME2     @11005

COPY ~ImprovedAnvil/resources/creatures/new/S!smgol1.cre~ ~override/S!smgol1.cre~
  SAY NAME1     @11156
  SAY NAME2     @11156

COPY ~ImprovedAnvil/resources/creatures/new/S!smgol2.cre~ ~override/S!smgol2.cre~
  SAY NAME1     @11156
  SAY NAME2     @11156

COPY ~ImprovedAnvil/resources/creatures/new/S!smtg1.cre~ ~override/S!smtg1.cre~
  SAY NAME1     @11157
  SAY NAME2     @11157

COPY ~ImprovedAnvil/resources/creatures/new/S!smtg2.cre~ ~override/S!smtg2.cre~
  SAY NAME1     @11157
  SAY NAME2     @11157

COPY ~ImprovedAnvil/resources/creatures/new/S!dracof.cre~ ~override/S!dracof.cre~
  SAY NAME1     @11018
  SAY NAME2     @11018

COPY ~ImprovedAnvil/resources/creatures/new/S!wer01.cre~ ~override/S!wer01.cre~
  SAY NAME1     @12050
  SAY NAME2     @12050

COPY ~ImprovedAnvil/resources/creatures/new/S!wer02.cre~ ~override/S!wer02.cre~
  SAY NAME1     @12051
  SAY NAME2     @12051

COPY ~ImprovedAnvil/resources/creatures/new/S!wer03.cre~ ~override/S!wer03.cre~
  SAY NAME1     @12051
  SAY NAME2     @12051

COPY ~ImprovedAnvil/resources/creatures/new/S!wer04.cre~ ~override/S!wer04.cre~
  SAY NAME1     @12068
  SAY NAME2     @12068

COPY ~ImprovedAnvil/resources/creatures/new/S!wer05.cre~ ~override/S!wer05.cre~
  SAY NAME1     @12068
  SAY NAME2     @12068

COPY ~ImprovedAnvil/resources/creatures/new/S!vert01.cre~ ~override/S!vert01.cre~
  SAY NAME1     @12052
  SAY NAME2     @12052

COPY ~ImprovedAnvil/resources/creatures/new/S!trgu01.cre~ ~override/S!trgu01.cre~
  SAY NAME1     @12057
  SAY NAME2     @12057

COPY ~ImprovedAnvil/resources/creatures/new/S!trgu02.cre~ ~override/S!trgu02.cre~
  SAY NAME1     @12057
  SAY NAME2     @12057

  WRITE_ASCII 0x248 ~S!trgua~ #8 // override script
  WRITE_ASCII 0x280 ~s!trgu02~ #32 // death variable

COPY ~ImprovedAnvil/resources/creatures/new/S!jagdu.cre~ ~override/S!jagdu.cre~
  SAY NAME1     @12058
  SAY NAME2     @12058

  WRITE_ASCII 0x248 ~MAGE16A~ #8 // override script

COPY ~ImprovedAnvil/resources/creatures/new/S!gdru01.cre~ ~override/S!gdru01.cre~
  SAY NAME1     @12059
  SAY NAME2     @12059

  WRITE_ASCII 0x2cc ~iagdru01~ #8 // dialogue

COPY ~ImprovedAnvil/resources/creatures/new/S!gdru02.cre~ ~override/S!gdru02.cre~
  SAY NAME1     @12059
  SAY NAME2     @12059

  WRITE_ASCII 0x248 ~S!GDRU02~ #8 // override script

COPY ~ImprovedAnvil/resources/creatures/new/S!gdru03.cre~ ~override/S!gdru03.cre~
  SAY NAME1     @12059
  SAY NAME2     @12059

  WRITE_ASCII 0x248 ~S!GDRU03~ #8 // override script

COPY ~ImprovedAnvil/resources/creatures/new/S!gdru04.cre~ ~override/S!gdru04.cre~
  SAY NAME1     @12059
  SAY NAME2     @12059

COPY ~ImprovedAnvil/resources/creatures/new/S!tslead.cre~ ~override/S!tslead.cre~
  SAY NAME1     @12060
  SAY NAME2     @12060

  WRITE_ASCII 0x248 ~S!tslead~ #8 // override script
  WRITE_ASCII 0x2cc ~iatslead~ #8 // dialogue

COPY ~ImprovedAnvil/resources/creatures/new/S!drudiv.cre~ ~override/S!drudiv.cre~
  SAY NAME1     @12083
  SAY NAME2     @12083

COPY ~ImprovedAnvil/resources/creatures/new/S!ferr01.cre~ ~override/S!ferr01.cre~
  SAY NAME1     @12070
  SAY NAME2     @12070

  ADD_CRE_ITEM ~minhp1~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~AMULET~

  WRITE_ASCII 0x2cc ~iaferr01~ #8 // dialogue

COPY ~ImprovedAnvil/resources/creatures/new/S!ferr02.cre~ ~override/S!ferr02.cre~
  SAY NAME1     @12070
  SAY NAME2     @12070

  ADD_CRE_ITEM ~minhp1~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~AMULET~

  WRITE_ASCII 0x2cc ~iaferr02~ #8 // dialogue

COPY ~ImprovedAnvil/resources/creatures/new/S!ferele.cre~ ~override/S!ferele.cre~
  SAY NAME1     @12070
  SAY NAME2     @12070

  WRITE_ASCII 0x248 ~S!ferele~ #8 // override script

COPY ~ImprovedAnvil/resources/creatures/new/S!tshun1.cre~ ~override/S!tshun1.cre~
     ~ImprovedAnvil/resources/creatures/new/S!tshun2.cre~ ~override/S!tshun2.cre~
  SAY NAME1     @12089
  SAY NAME2     @12089

COPY ~ImprovedAnvil/resources/creatures/new/S!drume1.cre~ ~override/S!drume1.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!drume2.cre~ ~override/S!drume2.cre~

COPY ~ImprovedAnvil/resources/creatures/new/S!dabred.cre~ ~override/S!dabred.cre~
  SAY NAME1     @12097
  SAY NAME2     @12097

COPY ~ImprovedAnvil/resources/creatures/new/S!dabwhi.cre~ ~override/S!dabwhi.cre~
  SAY NAME1     @12098
  SAY NAME2     @12098

COPY ~ImprovedAnvil/resources/creatures/new/S!dabblu.cre~ ~override/S!dabblu.cre~
  SAY NAME1     @12099
  SAY NAME2     @12099

COPY ~ImprovedAnvil/resources/creatures/new/S!dabgre.cre~ ~override/S!dabgre.cre~
  SAY NAME1     @12100
  SAY NAME2     @12100

COPY ~ImprovedAnvil/resources/creatures/new/S!dabbla.cre~ ~override/S!dabbla.cre~
  SAY NAME1     @12101
  SAY NAME2     @12101

COPY ~ImprovedAnvil/resources/creatures/new/S!smiede.cre~ ~override/S!smiede.cre~
  SAY NAME1     @12103
  SAY NAME2     @12103

COPY ~ImprovedAnvil/resources/creatures/new/S!spiede.cre~ ~override/S!spiede.cre~