// Pirate Coordinator //
// 22nd level mage //
// First level Spells (5): Magic missile x5 //
// Second level Spells (5): Vocalize, Melf acid arrow x2, Mirror Image x2//
// Third level Spells (5): Remove magic x3, Slow, Flame arrow //
// Fourth level Spells (5): StoneSkin, Imp invisibility, Greater Malison //
//                          Minor Globe of invulnerability, Fire Shield //
// Fifth level Spells (5): spell immunity, Lower Res, Chaos, Animate Dead x2 //
// Sixth level Spells (6): Protection magic energy, True sight, Death spell x3 //
//                         Chain Lightning//
// Seventh level Spells (5): Mordenkainen's sword x2, FoD, Ruby Ray x2 //
// Eight level Spells (5): Protection energy, Abi dalzim's horrid wilting x3, tpt //
// Ninth level Spells (3): Dragon's breath, Comet, power word kill //
// Scrolls: Absolute Immunity x4, Emotion x4, Breach x4, spellstrike //

IF
  Heard("pirsea01",ALERT)
  !Detect([PC])
  !Detect([GOODCUTOFF])
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
END

IF
  OR(2)
   Detect([PC])
   Detect([GOODCUTOFF])
  Global("Iapirsm01","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm01","LOCALS",1)
    SetGlobalTimer("Iatpt","LOCALS",66)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_ENERGY)
    ReallyForceSpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_ENERGY)
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_MIRROR_IMAGE)
    ReallyForceSpellRES("SPWII41",Myself)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    ReallyForceSpellRES("SPWI804",Myself) //
    ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  Global("Iapirsm01","LOCALS",1)
  HasItem("bhaalhp1",Myself)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    ReallyForceSpellRES("SPWII07",Myself)
    DestroyItem("bhaalhp1")
    SetInterrupt(TRUE)
END

IF
  Allegiance(Myself,ENEMY)
  OR(2)
   Detect([PC])
   Detect([GOODCUTOFF])
  Global("partyfled","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("partyfled","LOCALS",0)
END

IF
  Global("Iapcastts","GLOBAL",1)
  Global("Iatsinvulner","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatsinvulner","LOCALS",1)
    ApplySpellRES("SPINI70",Myself)
END

IF
  Global("Iapcastts","GLOBAL",0)
  Global("Iatsinvulner","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iatsinvulner","LOCALS",0)
    ApplySpellRES("SPINI71",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  !StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Myself,STATE_HELPLESS)
  !StateCheck(Myself,STATE_STUNNED)
  Global("Iainvis","LOCALS",0)
  Global("Iapirsm01","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iainvis","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39969)  // ~Spell Sequencer - Fired~
    ReallyForceSpellRES("SPWII41",Myself)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    ReallyForceSpell(Myself,WIZARD_BLUR)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  Global("Iapirsm01","LOCALS",1)
  CheckStatLT(Myself,1,STONESKINS)
  Global("Iacontin","LOCALS",0)
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iacontin","LOCALS",1)
    DisplayString(Myself,29736) // Contingency - Stoneskin
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  OR(4)
   CheckStatGT(Myself,0,SCRIPTINGSTATE9)
   StateCheck(Myself,STATE_HELPLESS)
   StateCheck(Myself,STATE_STUNNED)
   Global("Iapcastts","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  HPPercentLT(Myself,75)
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),49,RESISTELECTRICITY)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  Global("Iapirsm02","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm02","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39968) // Spell Trigger- Fired
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  OR(2)
   !GlobalTimerNotExpired("absolute","LOCALS")
   CheckStat(Myself,0,SCRIPTINGSTATE6)
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),5)
  GlobalLT("Iapirsm25","LOCALS",4)
  HasItem("scrl9p",Myself) //
THEN
  RESPONSE #100
    SetGlobalTimer("absolute","LOCALS",24)
    IncrementGlobal("Iapirsm25","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9p",Myself) //
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_VOCALIZE)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",0)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE7)
   CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE7)
   CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE7)
   CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE7)
   CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE7)
   CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE7)
   CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",2)
  CheckStatGT(Player1,0,SCRIPTINGSTATE7)
  CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",2)
  CheckStatGT(Player2,0,SCRIPTINGSTATE7)
  CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",2)
  CheckStatGT(Player3,0,SCRIPTINGSTATE7)
  CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",2)
  CheckStatGT(Player4,0,SCRIPTINGSTATE7)
  CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",2)
  CheckStatGT(Player5,0,SCRIPTINGSTATE7)
  CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapirsm10","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",2)
  CheckStatGT(Player6,0,SCRIPTINGSTATE7)
  CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm10","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player1)
  Class(Player1,MAGE_ALL)
  !CheckStat(Player1,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !StateCheck(Player1,STATE_MIRRORIMAGE)
  CheckStatLT(Player1,51,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE3)
  CheckStatGT(Player1,8,SAVEVSSPELL)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",0)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player2)
  Class(Player2,MAGE_ALL)
  !CheckStat(Player2,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !StateCheck(Player2,STATE_MIRRORIMAGE)
  CheckStatLT(Player2,51,RESISTMAGIC)
  !CheckStat(Player2,2,SCRIPTINGSTATE3)
  CheckStatGT(Player2,8,SAVEVSSPELL)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",0)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player3)
  Class(Player3,MAGE_ALL)
  !CheckStat(Player3,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !StateCheck(Player3,STATE_MIRRORIMAGE)
  CheckStatLT(Player3,51,RESISTMAGIC)
  !CheckStat(Player3,2,SCRIPTINGSTATE3)
  CheckStatGT(Player3,8,SAVEVSSPELL)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",0)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player4)
  Class(Player4,MAGE_ALL)
  !CheckStat(Player4,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !StateCheck(Player4,STATE_MIRRORIMAGE)
  CheckStatLT(Player4,51,RESISTMAGIC)
  !CheckStat(Player4,2,SCRIPTINGSTATE3)
  CheckStatGT(Player4,8,SAVEVSSPELL)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",0)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player5)
  Class(Player5,MAGE_ALL)
  !CheckStat(Player5,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !StateCheck(Player5,STATE_MIRRORIMAGE)
  CheckStatLT(Player5,51,RESISTMAGIC)
  !CheckStat(Player5,2,SCRIPTINGSTATE3)
  CheckStatGT(Player5,8,SAVEVSSPELL)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",0)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player6)
  Class(Player6,MAGE_ALL)
  !CheckStat(Player6,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !StateCheck(Player6,STATE_MIRRORIMAGE)
  CheckStatLT(Player6,51,RESISTMAGIC)
  !CheckStat(Player6,2,SCRIPTINGSTATE3)
  CheckStatGT(Player6,8,SAVEVSSPELL)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",0)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player1)
  Class(Player1,MAGE_ALL)
  !CheckStat(Player1,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !StateCheck(Player1,STATE_MIRRORIMAGE)
  CheckStatLT(Player1,51,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE3)
  CheckStatGT(Player1,8,SAVEVSSPELL)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE7)
   CheckStatGT(Player1,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player2)
  Class(Player2,MAGE_ALL)
  !CheckStat(Player2,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !StateCheck(Player2,STATE_MIRRORIMAGE)
  CheckStatLT(Player2,51,RESISTMAGIC)
  !CheckStat(Player2,2,SCRIPTINGSTATE3)
  CheckStatGT(Player2,8,SAVEVSSPELL)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE7)
   CheckStatGT(Player2,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player3)
  Class(Player3,MAGE_ALL)
  !CheckStat(Player3,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !StateCheck(Player3,STATE_MIRRORIMAGE)
  CheckStatLT(Player3,51,RESISTMAGIC)
  !CheckStat(Player3,2,SCRIPTINGSTATE3)
  CheckStatGT(Player3,8,SAVEVSSPELL)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE7)
   CheckStatGT(Player3,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player4)
  Class(Player4,MAGE_ALL)
  !CheckStat(Player4,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !StateCheck(Player4,STATE_MIRRORIMAGE)
  CheckStatLT(Player4,51,RESISTMAGIC)
  !CheckStat(Player4,2,SCRIPTINGSTATE3)
  CheckStatGT(Player4,8,SAVEVSSPELL)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE7)
   CheckStatGT(Player4,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player5)
  Class(Player5,MAGE_ALL)
  !CheckStat(Player5,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !StateCheck(Player5,STATE_MIRRORIMAGE)
  CheckStatLT(Player5,51,RESISTMAGIC)
  !CheckStat(Player5,2,SCRIPTINGSTATE3)
  CheckStatGT(Player5,8,SAVEVSSPELL)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE7)
   CheckStatGT(Player5,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player6)
  Class(Player6,MAGE_ALL)
  !CheckStat(Player6,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !StateCheck(Player6,STATE_MIRRORIMAGE)
  CheckStatLT(Player6,51,RESISTMAGIC)
  !CheckStat(Player6,2,SCRIPTINGSTATE3)
  CheckStatGT(Player6,8,SAVEVSSPELL)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE7)
   CheckStatGT(Player6,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player1)
  Class(Player1,MAGE_ALL)
  !CheckStat(Player1,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !StateCheck(Player1,STATE_MIRRORIMAGE)
  CheckStatLT(Player1,51,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE3)
  CheckStatGT(Player1,8,SAVEVSSPELL)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",2)
  CheckStatGT(Player1,0,SCRIPTINGSTATE7)
  CheckStatGT(Player1,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player1,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player2)
  Class(Player2,MAGE_ALL)
  !CheckStat(Player2,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !StateCheck(Player2,STATE_MIRRORIMAGE)
  CheckStatLT(Player2,51,RESISTMAGIC)
  !CheckStat(Player2,2,SCRIPTINGSTATE3)
  CheckStatGT(Player2,8,SAVEVSSPELL)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",2)
  CheckStatGT(Player2,0,SCRIPTINGSTATE7)
  CheckStatGT(Player2,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player2,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player3)
  Class(Player3,MAGE_ALL)
  !CheckStat(Player3,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !StateCheck(Player3,STATE_MIRRORIMAGE)
  CheckStatLT(Player3,51,RESISTMAGIC)
  !CheckStat(Player3,2,SCRIPTINGSTATE3)
  CheckStatGT(Player3,8,SAVEVSSPELL)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",2)
  CheckStatGT(Player3,0,SCRIPTINGSTATE7)
  CheckStatGT(Player3,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player3,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player4)
  Class(Player4,MAGE_ALL)
  !CheckStat(Player4,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !StateCheck(Player4,STATE_MIRRORIMAGE)
  CheckStatLT(Player4,51,RESISTMAGIC)
  !CheckStat(Player4,2,SCRIPTINGSTATE3)
  CheckStatGT(Player4,8,SAVEVSSPELL)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",2)
  CheckStatGT(Player4,0,SCRIPTINGSTATE7)
  CheckStatGT(Player4,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player4,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player5)
  Class(Player5,MAGE_ALL)
  !CheckStat(Player5,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !StateCheck(Player5,STATE_MIRRORIMAGE)
  CheckStatLT(Player5,51,RESISTMAGIC)
  !CheckStat(Player5,2,SCRIPTINGSTATE3)
  CheckStatGT(Player5,8,SAVEVSSPELL)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",2)
  CheckStatGT(Player5,0,SCRIPTINGSTATE7)
  CheckStatGT(Player5,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player5,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(Player6)
  Class(Player6,MAGE_ALL)
  !CheckStat(Player6,5,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !StateCheck(Player6,STATE_MIRRORIMAGE)
  CheckStatLT(Player6,51,RESISTMAGIC)
  !CheckStat(Player6,2,SCRIPTINGSTATE3)
  CheckStatGT(Player6,8,SAVEVSSPELL)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",2)
  CheckStatGT(Player6,0,SCRIPTINGSTATE7)
  CheckStatGT(Player6,0,MINORGLOBE)
  Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm09","LOCALS",1)
    DisplayString(Myself,26328)  //
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
    ReallyForceSpell(Player6,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  AreaCheck("AR0310")
  Detect([PC])
  Global("Iatreasure","LOCALS",0)
  Global("Iabeltplace","GLOBAL",3)
  Global("Iapcastts","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iabeltplace","GLOBAL",5)
    SetGlobal("Iatreasure","LOCALS",1)
    GiveItemCreate("belt10",Myself,0,0,0) //
END

IF
  Allegiance(Myself,ENEMY)
  AreaCheck("AR0310")
  Detect([PC])
  Global("Iatreasure2","LOCALS",0)
  Global("Iabookplace","GLOBAL",1)
  Global("Iawhichbook","GLOBAL",1)
  Global("Iapcastts","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iatreasure2","LOCALS",1)
    SetGlobal("Iabookplace","LOCALS",3)
    GiveItemCreate("misc3a",Myself,0,0,0) //
END

IF
  Allegiance(Myself,ENEMY)
  AreaCheck("AR0310")
  Detect([PC])
  Global("Iatreasure2","LOCALS",0)
  Global("Iabookplace","GLOBAL",1)
  Global("Iawhichbook","GLOBAL",2)
  Global("Iapcastts","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iatreasure2","LOCALS",1)
    SetGlobal("Iabookplace","LOCALS",3)
    GiveItemCreate("S!misc42",Myself,0,0,0) //
END

IF
  Allegiance(Myself,ENEMY)
  AreaCheck("AR0310")
  ActionListEmpty()
  See(Player1)
  Global("Iatreasure3","LOCALS",0)
  Class(Player1,MAGE_ALL)
  !Class(Player1,FIGHTER_ALL)
  !Class(Player1,CLERIC_ALL)
  !Class(Player1,THIEF_ALL)
  Kit(Player1,MAGESCHOOL_NECROMANCER)
  Global("Iapcastts","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iatreasure3","LOCALS",1)
    GiveItemCreate("S!scrl23",Myself,0,0,0) //
END

IF
  Allegiance(Myself,ENEMY)
  AreaCheck("AR0310")
  ActionListEmpty()
  See(Player1)
  Global("Iatreasure4","LOCALS",0)
  OR(2)
   !Class(Player1,MAGE_ALL)
   !Class(Player1,FIGHTER_ALL)
  Global("Iapcastts","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iatreasure4","LOCALS",1)
    GiveItemCreate("scrl6s",Myself,0,0,0) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !StateCheck(Myself,STATE_MIRRORIMAGE)
  See(NearestEnemyOf(Myself))
  Global("Iapirsm21","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm21","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_MIRROR_IMAGE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalTimerExpired("Iatpt","LOCALS")
  See(NearestEnemyOf(Myself))
  Global("Iatenser","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatenser","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl8z") //
    DisplayStringHead(Myself,46153) //
    ForceSpellRES("SPWI804",Myself) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_HELPLESS)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_HELPLESS)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_HELPLESS)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  !GlobalTimerNotExpired("truesight","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Detect([PC])
  OR(2)
    !See([PC])
    !See([GOODCUTOFF])
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap1nr","GLOBAL",1)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap1nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player1,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",2)
  GlobalGT("Iap1nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iap1nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  HasItem("scrl6u",Myself)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap1nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE6)
   CheckStat(Player1,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm10","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player1)
  HPLT(Player1,60)
  CheckStatGT(Player1,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm09","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,5,SCRIPTINGSTATE7)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  !StateCheck(Player1,STATE_MIRRORIMAGE)
  CheckStatLT(Player1,51,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE3)
  !HasBounceEffects(Player1)
  Class(Player1,MAGE_ALL)
  CheckStatGT(Player1,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap2nr","GLOBAL",1)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap2nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player2,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",2)
  GlobalGT("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iap2nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  HasItem("scrl6u",Myself)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap2nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE6)
   CheckStat(Player2,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm10","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  CheckStatLT(Player2,25,RESISTMAGIC)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player2)
  HPLT(Player2,60)
  CheckStatGT(Player2,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm09","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,5,SCRIPTINGSTATE7)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  !StateCheck(Player2,STATE_MIRRORIMAGE)
  CheckStatLT(Player2,51,RESISTMAGIC)
  !CheckStat(Player2,2,SCRIPTINGSTATE3)
  !HasBounceEffects(Player2)
  Class(Player2,MAGE_ALL)
  CheckStatGT(Player2,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap3nr","GLOBAL",1)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap3nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player3,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",2)
  GlobalGT("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iap3nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  HasItem("scrl6u",Myself)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap3nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE6)
   CheckStat(Player3,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm10","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  CheckStatLT(Player3,25,RESISTMAGIC)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player3)
  HPLT(Player3,60)
  CheckStatGT(Player3,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm09","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,5,SCRIPTINGSTATE7)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  !StateCheck(Player3,STATE_MIRRORIMAGE)
  CheckStatLT(Player3,51,RESISTMAGIC)
  !CheckStat(Player3,2,SCRIPTINGSTATE3)
  !HasBounceEffects(Player3)
  Class(Player3,MAGE_ALL)
  CheckStatGT(Player3,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap4nr","GLOBAL",1)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap4nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player4,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",2)
  GlobalGT("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iap4nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  HasItem("scrl6u",Myself)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap4nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE6)
   CheckStat(Player4,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm10","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  CheckStatLT(Player4,25,RESISTMAGIC)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player4)
  HPLT(Player4,60)
  CheckStatGT(Player4,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm09","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,5,SCRIPTINGSTATE7)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  !StateCheck(Player4,STATE_MIRRORIMAGE)
  CheckStatLT(Player4,51,RESISTMAGIC)
  !CheckStat(Player4,2,SCRIPTINGSTATE3)
  !HasBounceEffects(Player4)
  Class(Player4,MAGE_ALL)
  CheckStatGT(Player4,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap5nr","GLOBAL",1)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap5nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player5,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",2)
  GlobalGT("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iap5nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  HasItem("scrl6u",Myself)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap5nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE6)
   CheckStat(Player5,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm10","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  CheckStatLT(Player5,25,RESISTMAGIC)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player5)
  HPLT(Player5,60)
  CheckStatGT(Player5,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm09","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,5,SCRIPTINGSTATE7)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  !StateCheck(Player5,STATE_MIRRORIMAGE)
  CheckStatLT(Player5,51,RESISTMAGIC)
  !CheckStat(Player5,2,SCRIPTINGSTATE3)
  !HasBounceEffects(Player5)
  Class(Player5,MAGE_ALL)
  CheckStatGT(Player5,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap6nr","GLOBAL",1)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap6nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player6,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",2)
  GlobalGT("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iap6nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  HasItem("scrl6u",Myself)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap6nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE6)
   CheckStat(Player6,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm10","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  CheckStatLT(Player6,25,RESISTMAGIC)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player6)
  HPLT(Player6,60)
  CheckStatGT(Player6,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iapirsm09","LOCALS",0)
  HasItem("scrl6u",Myself)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,5,SCRIPTINGSTATE7)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  !StateCheck(Player6,STATE_MIRRORIMAGE)
  CheckStatLT(Player6,51,RESISTMAGIC)
  !CheckStat(Player6,2,SCRIPTINGSTATE3)
  !HasBounceEffects(Player6)
  Class(Player6,MAGE_ALL)
  CheckStatGT(Player6,0,SCRIPTINGSTATE2)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  OR(4)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
   CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
   CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("RemoveMagic","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("RemoveMagic","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !HasBounceEffects(LastSeenBy(Myself))
  HPLT(LastSeenBy(Myself),60)
  Global("Ianoward","LOCALS",0)
  Global("Iapirsm10","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !HasBounceEffects(LastSeenBy(Myself))
  HPLT(LastSeenBy(Myself),60)
  Global("Ianoward","LOCALS",0)
  Global("Iapirsm10","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !HasBounceEffects(LastSeenBy(Myself))
  HPLT(LastSeenBy(Myself),60)
  Global("Ianoward","LOCALS",0)
  Global("Iapirsm10","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(FourthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !HasBounceEffects(LastSeenBy(Myself))
  HPLT(LastSeenBy(Myself),60)
  Global("Ianoward","LOCALS",0)
  Global("Iapirsm10","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(FifthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !HasBounceEffects(LastSeenBy(Myself))
  HPLT(LastSeenBy(Myself),60)
  Global("Ianoward","LOCALS",0)
  Global("Iapirsm10","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SixthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !HasBounceEffects(LastSeenBy(Myself))
  HPLT(LastSeenBy(Myself),60)
  Global("Ianoward","LOCALS",0)
  Global("Iapirsm10","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp1fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp1t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp1t","LOCALS")
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp1fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp2fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp2t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp2t","LOCALS")
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp2fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp3fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp3t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp3t","LOCALS")
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp3fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp4fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp4t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp4t","LOCALS")
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp4fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp5fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp5t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp5t","LOCALS")
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp5fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp6fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp6t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",3)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp6t","LOCALS")
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp6fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("truesight","LOCALS")
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
  Global("Iaremove","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iaremove","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iapirsm16","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm16","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iapirsm16","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm16","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iapirsm16","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm16","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("Iapirsm26","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm26","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("Iapirsm26","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm26","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("Iapirsm26","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm26","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iapirsm16","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm16","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iapirsm16","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm16","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iapirsm16","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm16","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  Global("Iapirsm03","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm03","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  Global("Iapirsm03","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm03","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iapirsm19","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm19","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iapirsm19","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm19","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("DispelMagic","LOCALS",0)
  OR(2)
   Global("Iapirsm19","LOCALS",0)
   Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("DispelMagic","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("DispelMagic","LOCALS",0)
  OR(2)
   Global("Iapirsm19","LOCALS",0)
   Global("Iapirsm09","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("DispelMagic","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  Global("Iapirsm18","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm18","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  Global("Iapirsm18","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm18","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  OR(2)
   CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("DispelMagic2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("DispelMagic2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  OR(2)
   CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("DispelMagic2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("DispelMagic2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  OR(2)
   CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE8)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("DispelMagic2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("DispelMagic2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  Global("Iapirsm12","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm12","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  Global("Iapirsm12","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm12","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  Global("Iapirsm12","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm12","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
  OR(3)
   LevelGT(LastSeenBy(Myself),8)
   CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
   CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
  GlobalLT("Iapirsm04","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iapirsm04","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  Global("Iapirsm11","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm11","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaemotscrl","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  GlobalLT("Iaemotion","LOCALS",4)
  HasItem("scrl5h",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iaemotion","LOCALS",1)
    SetGlobalTimer("Iaemotscrl","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl5h",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaemotscrl","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  GlobalLT("Iaemotion","LOCALS",4)
  HasItem("scrl5h",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iaemotion","LOCALS",1)
    SetGlobalTimer("Iaemotscrl","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl5h",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaemotscrl","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  GlobalLT("Iaemotion","LOCALS",4)
  HasItem("scrl5h",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iaemotion","LOCALS",1)
    SetGlobalTimer("Iaemotscrl","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl5h",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  Global("Iapirsm15","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm15","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_ANIMATE_DEAD)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  Global("Iapirsm20","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm20","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  Global("Iapirsm11","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm11","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",3)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",3)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  Global("Iapirsm06","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm06","LOCALS",3)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  Global("Iapirsm15","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm15","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_ANIMATE_DEAD)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Iapirsm22","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm22","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Iapirsm22","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm22","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Iapirsm22","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm22","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iapirsm23","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iapirsm23","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iapirsm23","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iapirsm23","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iapirsm23","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iapirsm23","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  GlobalLT("Iapirsm24","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iapirsm24","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  GlobalLT("Iapirsm24","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iapirsm24","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  GlobalLT("Iapirsm24","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iapirsm24","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  Global("partyfled","LOCALS",0)
  Allegiance(Myself,ENEMY)
  GlobalGT("Iapirsm01","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobalTimer("chase","LOCALS",60)
    SetGlobal("partyfled","LOCALS",1)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  Global("partyfled","LOCALS",1)
  GlobalTimerNotExpired("chase","LOCALS")
  InMyArea(Player1)
  Allegiance(Myself,ENEMY)
  GlobalGT("Iapirsm01","LOCALS",0)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  GlobalTimerExpired("chase","LOCALS")
  Global("partyfled","LOCALS",1)
  GlobalGT("Iapirsm01","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iapirsm01","LOCALS",0)
    SetGlobal("Iapirsm02","LOCALS",0)
    SetGlobal("Iapirsm03","LOCALS",0)
    SetGlobal("Iapirsm04","LOCALS",0)
    SetGlobal("Iapirsm06","LOCALS",0)
    SetGlobal("Iapirsm09","LOCALS",0)
    SetGlobal("Iapirsm10","LOCALS",0)
    SetGlobal("Iapirsm11","LOCALS",0)
    SetGlobal("Iapirsm12","LOCALS",0)
    SetGlobal("Iapirsm15","LOCALS",0)
    SetGlobal("Iapirsm16","LOCALS",0)
    SetGlobal("Iapirsm18","LOCALS",0)
    SetGlobal("Iapirsm19","LOCALS",0)
    SetGlobal("Iapirsm20","LOCALS",0)
    SetGlobal("Iapirsm21","LOCALS",0)
    SetGlobal("Iapirsm22","LOCALS",0)
    SetGlobal("Iapirsm23","LOCALS",0)
    SetGlobal("Iapirsm24","LOCALS",0)
    SetGlobal("Iapirsm26","LOCALS",0)
    SetGlobal("RemoveMagic","LOCALS",0)
    SetGlobal("Iainvis","LOCALS",0)
    SetGlobal("Iareversal","LOCALS",0)
    SetGlobal("Ianoward","LOCALS",0)
    SetGlobal("Iadispelpot","LOCALS",0)
    ReallyForceSpellRES("SPWII07",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  HasItem("bull03",Myself)
  See(NearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE10)
  !Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipRanged()
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  HasItem("bull03",Myself)
  See(SecondNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE10)
  !Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipRanged()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  HasItem("bull03",Myself)
  See(ThirdNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE10)
  !Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipRanged()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(ThirdNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  HasItem("bull03",Myself)
  See(FourthNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE10)
  !Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipRanged()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  HasItem("bull03",Myself)
  See(FifthNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE10)
  !Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipRanged()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  HasItem("bull03",Myself)
  See(SixthNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),100,RESISTMISSILE)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE10)
  !Range(LastSeenBy(Myself),3)
THEN
  RESPONSE #100
    EquipRanged()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  See(ThirdNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackOneRound(LastSeenBy(Myself))
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  InMyArea(Player1)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END