// Cleric Mage levels 26 22 //
// Mage Spells: //
// First level spells (5): MM x5 //
// Second level spells (5): Blur, Melf Acid Arrow x4 //
// Third level spells (5): remove magic x5 //
// Fourth level spells (5): Stoneskin x3, Fire Shield, Minor Globe //
// Fifth level spells (5): spell immunity, Lower res x3, Chaos //
// Sixth level spells (6): PfMW x4, Death Spell x2 //
// Seventh level spells (5): Spell Turning, Pw stun x3, Mordenkainen's sword //
// Eight level spells (5): ADHW x5 //
// Ninth level spells (3): Dragons Breath, Comet, pw kill //
// Clerical spells: //
// First level spells (11): Armor of faith //
// Second level spells (11): Hold Person x9//
// Third level spells (10): zone of sweet air x3, dispel magic x4, Rigid Thinking x3 //
// Fourth level spells (10): CSW //
// Fifth level spells (9): True Seeing, G command x5, Slay living, CCW, Flame S //
// Sixth level spells (6): physical M, Blade B, Aerial S, Bolt of G x3 //
// Seventh level spells (3): Globe of blades, Aura of FD, Storm of V //
// Scrolls: Ruby Ray x4, Breach x4, spellstrike //

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  Global("Iabattle","AR1904",0)
THEN
  RESPONSE #100
    SetGlobal("Iabattle","AR1904",1)
END

IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_BLUR)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)
    ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)
    ReallyForceSpell(Myself,NPC_BLADE_BARRIER)
    ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)
    ReallyForceSpell(Myself,CLERIC_GLOBE_OF_BLADES)
    ReallyForceSpell(Myself,CLERIC_AERIAL_SERVANT)
    ReallyForceSpell(Myself,WIZARD_MINOR_GLOBE_OF_INVULNERABILITY)
    ReallyForceSpell(Myself,CLERIC_AURA_OF_FLAMING_DEATH)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
END

IF
  Allegiance(Myself,ENEMY)
  OR(2)
   Detect([PC])
   Detect([GOODCUTOFF])
  Global("partyfled","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("partyfled","LOCALS",0)
END

IF
  Allegiance(Myself,ENEMY)
  OR(2)
   Detect([PC])
   Global("Iabattle","AR1904",1)
  Global("Iantrolls","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iantrolls","LOCALS",1)
    CreateCreatureObject("S!ntroll",Myself,0,0,0) //
    CreateCreatureObject("S!ntroll",Myself,0,0,0) //
    CreateCreatureObject("S!ntroll",Myself,0,0,0) //
    CreateCreatureObject("S!ntroll",Myself,0,0,0) //
END

IF
  ActionListEmpty()
  Allegiance(Myself,ENEMY)
  HPPercentLT(Myself,50)
  See([PC])
  CheckStatLT(LastSeenBy(Myself),75,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  Global("Iachain","LOCALS",0)
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iachain","LOCALS",1)
    DisplayString(Myself,26328) //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",0)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE7)
   CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE7)
   CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE7)
   CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE7)
   CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE7)
   CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE7)
   CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",2)
  CheckStatGT(Player1,0,SCRIPTINGSTATE7)
  CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player2)
  Global("Iap2nr","GLOBAL",2)
  CheckStatGT(Player2,0,SCRIPTINGSTATE7)
  CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player3)
  Global("Iap3nr","GLOBAL",2)
  CheckStatGT(Player3,0,SCRIPTINGSTATE7)
  CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player4)
  Global("Iap4nr","GLOBAL",2)
  CheckStatGT(Player4,0,SCRIPTINGSTATE7)
  CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player5)
  Global("Iap5nr","GLOBAL",2)
  CheckStatGT(Player5,0,SCRIPTINGSTATE7)
  CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapword","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  !HasBounceEffects(Player6)
  Global("Iap6nr","GLOBAL",2)
  CheckStatGT(Player6,0,SCRIPTINGSTATE7)
  CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iapword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",0)
  HPLT(Player1,90)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player2)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player3)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player4)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player5)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player6)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player1)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
  Global("Iap1nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE7)
   CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,90)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player2)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE7)
   CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player3)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE7)
   CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player4)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE7)
   CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player5)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE7)
   CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player6)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE7)
   CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player1)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
  Global("Iap1nr","GLOBAL",2)
  CheckStatGT(Player1,0,SCRIPTINGSTATE7)
  CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,90)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player2)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",2)
  CheckStatGT(Player2,0,SCRIPTINGSTATE7)
  CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player3)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",2)
  CheckStatGT(Player3,0,SCRIPTINGSTATE7)
  CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player4)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",2)
  CheckStatGT(Player4,0,SCRIPTINGSTATE7)
  CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player5)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",2)
  CheckStatGT(Player5,0,SCRIPTINGSTATE7)
  CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iastun","LOCALS",3)
  Global("Iaremove","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player6)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",2)
  CheckStatGT(Player6,0,SCRIPTINGSTATE7)
  CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  OR(3)
   Range(LastSeenBy(Myself),4)
   AttackedBy(LastSeenBy(Myself),MELEE)
   AttackedBy(LastSeenBy(Myself),RANGED)
  OR(2)
   !GlobalTimerNotExpired("pfmw","LOCALS")
   CheckStat(Myself,0,SCRIPTINGSTATE6)
  GlobalLT("Iatrollq02","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iatrollq02","LOCALS",1)
    SetGlobalTimer("pfmw","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  InMyArea(Player1)
  GlobalLT("Iazone","LOCALS",3)
  Global("Iapccloud","AR1904",1)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("Iapccloud","AR1904",0)
    Wait(2)
    IncrementGlobal("Iazone","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_ZONE_OF_SWEET_AIR)
    SetInterrupt(TRUE)
    MoveToObject(Player1)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  CheckStatLT(Myself,1,STONESKINS)
  See(NearestEnemyOf(Myself))
  GlobalLT("Iaskin","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Iaskin","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_STONE_SKIN)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  HPPercentLT(Myself,60)
  HasItem("potn55",Myself)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46150)//quaffs a potion
    UseItem("potn55",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  CheckStatLT(Myself,1,STONESKINS)
  See(NearestEnemyOf(Myself))
  Global("Iaskin","LOCALS",2)
  Global("Iatrollq01","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq01","LOCALS",1)
    DisplayString(Myself,29736) // Contingency - Stoneskin
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  HPPercentLT(Myself,75)
  !HPLT(Myself,1)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  Global("Iatrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrigger","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39968) // ~Spell Trigger- Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  OR(4)
   See(NearestEnemyOfType([PC.0.0.BARD_ALL]))
   See(NearestEnemyOfType([PC.0.0.DRUID_ALL]))
   See(NearestEnemyOfType([PC.0.0.CLERIC_ALL]))
   See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  Global("Iastorm","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iastorm","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_STORM_OF_VENGEANCE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  Global("Iapcastts","GLOBAL",0)
  See(Player1)
  LevelLT(Player1,24)
  Class(Player1,PALADIN_ALL)
  Range(Player1,12)
  !StateCheck(Player1,STATE_PANIC)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_CHARMED)
  !HasItemEquiped("hamm11",Player1)
  !HasItemEquiped("sw1h32",Player1)
  !HasItemEquiped("S!sw04",Player1)
  !HasItemEquiped("S!sw11",Player1)
  !HasItemEquiped("S!halb01",Player1)
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66",Player1)
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  Global("Iapcastts","GLOBAL",0)
  See("keldorn")
  !Dead("keldorn")
  LevelLT("keldorn",24)
  Class("keldorn",PALADIN_ALL)
  Range("keldorn",12)
  !StateCheck("keldorn",STATE_PANIC)
  !StateCheck("keldorn",STATE_CONFUSED)
  !StateCheck("keldorn",STATE_HELPLESS)
  !StateCheck("keldorn",STATE_STUNNED)
  !HasItemEquiped("hamm11","keldorn")
  !HasItemEquiped("sw1h32","keldorn")
  !HasItemEquiped("S!sw04","keldorn")
  !HasItemEquiped("S!sw11","keldorn")
  !HasItemEquiped("S!halb01","keldorn")
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66","keldorn")
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  Global("Iapcastts","GLOBAL",0)
  See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
  LevelLT(LastSeenBy(Myself),24)
  Range(LastSeenBy(Myself),12)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
  !HasItemEquiped("hamm11",LastSeenBy(Myself))
  !HasItemEquiped("sw1h32",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66",LastSeenBy(Myself))
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  Global("Iapcastts","GLOBAL",0)
  See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
  LevelLT(LastSeenBy(Myself),24)
  Range(LastSeenBy(Myself),12)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
  !HasItemEquiped("hamm11",LastSeenBy(Myself))
  !HasItemEquiped("sw1h32",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66",LastSeenBy(Myself))
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  Range(LastSeenBy(Myself),12)
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  Range(LastSeenBy(Myself),12)
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iaturning","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaturntime","LOCALS",24)
    SetGlobal("Iaturning","LOCALS",0)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(2)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(2)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(2)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpell(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  CheckStatGT(Myself,0,SCRIPTINGSTATE6)
  !HasBounceEffects(Myself)
  See(NearestEnemyOf(Myself))
  HPPercentLT(Myself,75)
  Global("Iatrollq05","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq05","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_CURE_CRITICAL_WOUNDS)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  CheckStatGT(Myself,0,SCRIPTINGSTATE6)
  !HasBounceEffects(Myself)
  !CheckStatGT(Myself,0,MINORGLOBE)
  See(NearestEnemyOf(Myself))
  HPPercentLT(Myself,75)
  Global("Iatrollq05","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq05","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_CURE_SERIOUS_WOUNDS)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap1nr","GLOBAL",1)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap1nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player1,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  GlobalGT("Iap1nr","GLOBAL",0)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iap1nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  HasItem("scrl6u",Myself)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap1nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player1,2,SCRIPTINGSTATE6)
   CheckStat(Player1,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap2nr","GLOBAL",1)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap2nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player2,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  GlobalGT("Iap2nr","GLOBAL",0)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iap2nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  HasItem("scrl6u",Myself)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap2nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player2,2,SCRIPTINGSTATE6)
   CheckStat(Player2,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap3nr","GLOBAL",1)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap3nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player3,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  GlobalGT("Iap3nr","GLOBAL",0)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iap3nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  HasItem("scrl6u",Myself)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap3nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player3,2,SCRIPTINGSTATE6)
   CheckStat(Player3,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap4nr","GLOBAL",1)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap4nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player4,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  GlobalGT("Iap4nr","GLOBAL",0)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iap4nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  HasItem("scrl6u",Myself)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap4nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player4,2,SCRIPTINGSTATE6)
   CheckStat(Player4,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap5nr","GLOBAL",1)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap5nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player5,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  GlobalGT("Iap5nr","GLOBAL",0)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iap5nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  HasItem("scrl6u",Myself)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap5nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player5,2,SCRIPTINGSTATE6)
   CheckStat(Player5,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  Global("Iaspellstrike","LOCALS",0)
  GlobalGT("Iap6nr","GLOBAL",1)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap6nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DestroyItem("scrl9m") //
    DisplayStringHead(Myself,46153) //
    ForceSpell(Player6,WIZARD_SPELL_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  GlobalGT("Iap6nr","GLOBAL",0)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iap6nr","GLOBAL",-1)
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  HasItem("scrl6u",Myself)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap6nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  HasItem("scrl6u",Myself)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  OR(2)
   CheckStatGT(Player6,2,SCRIPTINGSTATE6)
   CheckStat(Player6,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6u",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iaremove","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaremove","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iaremove","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaremove","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iaremove","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaremove","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(3)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,STONESKINS)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iatorgal03","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iatorgal03","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  !HasItemEquiped("S!boot01",LastSeenBy(Myself))
  !HasItemEquiped("S!boot02",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iatorgal03","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iatorgal03","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  !HasItemEquiped("S!boot01",LastSeenBy(Myself))
  !HasItemEquiped("S!boot02",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iatorgal03","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iatorgal03","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp1fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp1t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp1t","LOCALS")
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp1fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp2fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp2t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp2t","LOCALS")
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp2fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp3fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp3t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp3t","LOCALS")
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp3fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp4fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp4t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp4t","LOCALS")
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp4fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp5fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp5t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp5t","LOCALS")
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp5fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp6fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp6t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",4)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp6t","LOCALS")
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
  HasItem("scrl8g",Myself)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp6fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl8g",Player6) //
END

IF
  !GlobalTimerNotExpired("truesight","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
  Global("Iadispel","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispel","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iabreath","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iabreath","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iabreath","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iabreath","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iabreath","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iabreath","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iadeath","LOCALS",2)
  See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
  !Class(LastSeenBy(Myself),SKELETON)
  !Class(LastSeenBy(Myself),SKELETON_WARRIOR)
  OR(3)
   CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
   CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
   CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
THEN
  RESPONSE #100
    IncrementGlobal("Iadeath","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Ialower","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Ialower","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Ialower","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Ialower","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),19,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Ialower","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Ialower","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iapword","LOCALS",0)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iapword","LOCALS",0)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iapword","LOCALS",0)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(FourthNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iapword","LOCALS",0)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(FifthNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iapword","LOCALS",0)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SixthNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iapword","LOCALS",0)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iabreath","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iabreath","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iabreath","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iabreath","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  Global("Iabreath","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iabreath","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iatrollq04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq04","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39969)  // ~Spell Sequencer - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iatrollq04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq04","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39969)  // ~Spell Sequencer - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iatrollq04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq04","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39969)  // ~Spell Sequencer - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  Global("Iasword","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasword","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_MORDENKAINENS_SWORD)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(SixthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iabolt","LOCALS",3)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iabolt","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(FifthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iabolt","LOCALS",3)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iabolt","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(FourthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iabolt","LOCALS",3)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iabolt","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iabolt","LOCALS",3)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iabolt","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iabolt","LOCALS",3)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iabolt","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iabolt","LOCALS",3)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iabolt","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  Range(LastSeenBy(Myself),3)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Iaslay","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaslay","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),ENEMY_CLERIC_SLAY_LIVING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagcommand","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iatrollq09","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iatrollq09","LOCALS",1)
    SetGlobalTimer("Iagcommand","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagcommand","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iatrollq09","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iatrollq09","LOCALS",1)
    SetGlobalTimer("Iagcommand","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagcommand","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iatrollq09","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iatrollq09","LOCALS",1)
    SetGlobalTimer("Iagcommand","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  GlobalLT("Iahorrid","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  GlobalLT("Iahorrid","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  GlobalLT("Iahorrid","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaholdp","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE1)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE1)
  GlobalLT("Iahperson","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iahperson","LOCALS",1)
    SetGlobalTimer("Iaholdp","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaholdp","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE1)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE1)
  GlobalLT("Iahperson","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iahperson","LOCALS",1)
    SetGlobalTimer("Iaholdp","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaholdp","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE1)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE1)
  GlobalLT("Iahperson","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iahperson","LOCALS",1)
    SetGlobalTimer("Iaholdp","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iahperson","LOCALS",9)
  Global("Ianoward4","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward4","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iahperson","LOCALS",9)
  Global("Ianoward4","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward4","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iahperson","LOCALS",9)
  Global("Ianoward4","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward4","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iatrollq07","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq07","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iatrollq07","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq07","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iatrollq07","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrollq07","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAOS)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iathinking","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iarigid","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iarigid","LOCALS",1)
    SetGlobalTimer("Iathinking","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iathinking","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iarigid","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iarigid","LOCALS",1)
    SetGlobalTimer("Iathinking","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iathinking","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iarigid","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iarigid","LOCALS",1)
    SetGlobalTimer("Iathinking","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  OR(3)
   GlobalLT("Iatrollq09","LOCALS",5)
   Global("Iatrollq07","LOCALS",0)
   GlobalLT("Iarigid","LOCALS",3)
  GlobalLT("Ianoward3","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Ianoward3","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  OR(3)
   GlobalLT("Iatrollq09","LOCALS",5)
   Global("Iatrollq07","LOCALS",0)
   GlobalLT("Iarigid","LOCALS",3)
  GlobalLT("Ianoward3","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Ianoward3","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  OR(3)
   GlobalLT("Iatrollq09","LOCALS",5)
   Global("Iatrollq07","LOCALS",0)
   GlobalLT("Iarigid","LOCALS",3)
  GlobalLT("Ianoward3","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Ianoward3","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Iaflame","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaflame","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Iaflame","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaflame","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Iaflame","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iaflame","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_FLAME_STRIKE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iamissile","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iamissile","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iamissile","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iamissile","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iamissile","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iamissile","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  InMyArea(Player1)
  Allegiance(Myself,ENEMY)
  Global("Prep","LOCALS",1)
  Global("partyfled","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("partyfled","LOCALS",1)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  InMyArea(Player1)
  Allegiance(Myself,ENEMY)
  Global("Prep","LOCALS",1)
  Global("partyfled","LOCALS",1)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  InMyArea(Player1)
  Allegiance(Myself,ENEMY)
  OR(3)
   Global("Iabattle","AR1904",1)
   AttackedBy([GOODCUTOFF],DEFAULT)
   HPPercentLT(Myself,100)
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
  RandomNumGT(6,4)
  Range(LastSeenBy(Myself),2)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,23)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",23)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),23)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END