IF
  See([PC])
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",0)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iaonepurge","LOCALS",1)
    SetGlobalTimer("Iapurge","LOCALS",24)
    SetGlobalTimer("Iawingbuffet","LOCALS",6)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(SecondNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",0)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iaonepurge","LOCALS",1)
    SetGlobalTimer("Iapurge","LOCALS",24)
    SetGlobalTimer("Iawingbuffet","LOCALS",6)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(ThirdNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",0)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iaonepurge","LOCALS",1)
    SetGlobalTimer("Iapurge","LOCALS",24)
    SetGlobalTimer("Iawingbuffet","LOCALS",6)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(FourthNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",0)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iaonepurge","LOCALS",1)
    SetGlobalTimer("Iapurge","LOCALS",24)
    SetGlobalTimer("Iawingbuffet","LOCALS",6)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(FifthNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",0)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iaonepurge","LOCALS",1)
    SetGlobalTimer("Iapurge","LOCALS",24)
    SetGlobalTimer("Iawingbuffet","LOCALS",6)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(SixthNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",0)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iaonepurge","LOCALS",1)
    SetGlobalTimer("Iapurge","LOCALS",24)
    SetGlobalTimer("Iawingbuffet","LOCALS",6)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See([PC])
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",1)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iapurge","LOCALS",24)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(SecondNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",1)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iapurge","LOCALS",24)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(ThirdNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",1)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iapurge","LOCALS",24)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(FourthNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",1)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iapurge","LOCALS",24)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(FifthNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",1)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iapurge","LOCALS",24)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  See(SixthNearest([PC]))
  OR(4)
   CheckStatGT(LastSeenBy(Myself),1,STONESKINS)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
   CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
   CheckStatGT(LastSeenBy(Myself),0,IMPROVEDHASTE)
  Global("Iaonepurge","LOCALS",1)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iapurge","LOCALS")
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iapurge","LOCALS",24)
    ReallyForceSpellRES("SPINI29",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  See([PC])
  Range(LastSeenBy(Myself),11)
  GlobalLT("Iaonewing","LOCALS",3)
  !GlobalTimerNotExpired("Iawingbuffet","LOCALS")
THEN
  RESPONSE #100
    IncrementGlobal("Iaonewing","LOCALS",1)
    SetGlobalTimer("Iawingbuffet","LOCALS",18)
    SetInterrupt(FALSE)
    ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)
    Wait(1)
    //CreateCreatureObject("S!coin2",Myself,0,0,0) //
    //CreateCreatureObject("S!coin2",Myself,0,0,0) //
    //CreateCreatureObject("S!gem2",Myself,0,0,0) //
    //CreateCreatureObject("S!gem2",Myself,0,0,0) //
    SetInterrupt(TRUE)
END

IF
  Allegiance(Myself,ENEMY)
  See([PC])
  Range(LastSeenBy(Myself),11)
  Global("Iaonewing","LOCALS",3)
  !GlobalTimerNotExpired("Iawingbuffet","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("Iawingbuffet","LOCALS",18)
    ForceSpell(LastSeenBy(Myself),DRAGON_WING_BUFFET)
END

IF
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  See(ThirdNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  See(FourthNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  InMyArea(Player1)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END