// Mage Level 30 //
// First level Spells (7): Magic Missile x7//
// Second level Spells (7): Melf's Acid Arrow x7 //
// Third level Spells (7): Remove magic x3, V.T. or Flame Arrow x4 //
// Fourth level Spells (7): Fire Shield, stoneskin, Gmalison, Emotion x4 //
// Fifth level Spells (7): spell immunity, breach x6 //
// Sixth level Spells (7): Globe, True sight, chain lightning x5 //
// Seventh level Spells (8): Ruby Ray x5, Finger of death, spell turning, pwstun //
// Eight level Spells (7): ABDHW x7 //
// Ninth level Spells (6):  Wish, E Blades, Dragon's B, Comet, PWK, Ab. Immunity//
// Scrolls: Absolute Immunity x5, Death Spell x5, Lower Resistance x4 //

IF
  See([GOODCUTOFF])
  Global("Iagolems","AR2806",0)
THEN
  RESPONSE #100
    SetGlobal("Iagolems","AR2806",1)
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
  Global("Iagolems","AR2806",3)
  !HasItem("S!minhp1",Myself)
  ActionListEmpty()
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,DRAGON_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_SPELL_TURNING)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_RED)
    ReallyForceSpell(Myself,WIZARD_GLOBE_OF_INVULNERABILITY)
    ReallyForceSpell(Myself,WIZARD_ABSOLUTE_IMMUNITY)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)
    SetGlobalTimer("absolute","LOCALS",24)
    SetInterrupt(TRUE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  Global("Iagolems","AR2806",3)
  HasItem("S!minhp1",Myself)
  ActionListEmpty()
THEN
  RESPONSE #100
    DestroyItem("S!minhp1")
END

IF
  !HasItem("S!minhp1",Myself)
  Global("Iapcastts","GLOBAL",1)
  Global("Iatsinvulner","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatsinvulner","LOCALS",1)
    ApplySpellRES("SPINI70",Myself)
END

IF
  Global("Iapcastts","GLOBAL",0)
  Global("Iatsinvulner","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("Iatsinvulner","LOCALS",0)
    ApplySpellRES("SPINI71",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  ActionListEmpty()
  HPPercentLT(Myself,75)
  !HPLT(Myself,2)
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  Global("Iajon15","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon15","LOCALS",1)
    DisplayString(Myself,26328) //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
END

IF
  OR(2)
   !GlobalTimerNotExpired("absolute","LOCALS")
   CheckStat(Myself,0,SCRIPTINGSTATE6)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  HasItem("scrl9p",Myself)
  !HPLT(Myself,2)
  GlobalLT("Iajon01","LOCALS",5)
  !HasItem("S!minhp1",Myself)
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),5)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon01","LOCALS",1)
    SetGlobalTimer("absolute","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9p",Myself)  //
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  Global("Iap1nr","GLOBAL",0)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  Global("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  Global("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  Global("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  Global("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  Global("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  Global("Iap1nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE7)
   CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  Global("Iap2nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE7)
   CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  Global("Iap3nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE7)
   CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  Global("Iap4nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE7)
   CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  Global("Iap5nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE7)
   CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  Global("Iap6nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE7)
   CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player1,0,SCRIPTINGSTATE2)
  Global("Iap1nr","GLOBAL",2)
  CheckStatGT(Player1,0,SCRIPTINGSTATE7)
  CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,60)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,60)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player2,0,SCRIPTINGSTATE2)
  Global("Iap2nr","GLOBAL",2)
  CheckStatGT(Player2,0,SCRIPTINGSTATE7)
  CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,60)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player3,0,SCRIPTINGSTATE2)
  Global("Iap3nr","GLOBAL",2)
  CheckStatGT(Player3,0,SCRIPTINGSTATE7)
  CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,60)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player4,0,SCRIPTINGSTATE2)
  Global("Iap4nr","GLOBAL",2)
  CheckStatGT(Player4,0,SCRIPTINGSTATE7)
  CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,60)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player5,0,SCRIPTINGSTATE2)
  Global("Iap5nr","GLOBAL",2)
  CheckStatGT(Player5,0,SCRIPTINGSTATE7)
  CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_KILL)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,60)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !CheckStatGT(Player6,0,SCRIPTINGSTATE2)
  Global("Iap6nr","GLOBAL",2)
  CheckStatGT(Player6,0,SCRIPTINGSTATE7)
  CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    SetGlobal("Iajon17","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_KILL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  HPPercentLT(Myself,90)
  !HPLT(Myself,2)
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  Global("Iajon06","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon06","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39968)  //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  Global("Iap1nr","GLOBAL",0)
  HPLT(Player1,90)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
  Global("Iap1nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE7)
   CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,90)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE7)
   CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE7)
   CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE7)
   CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE7)
   CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE7)
   CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
  Global("Iap1nr","GLOBAL",2)
  CheckStatGT(Player1,0,SCRIPTINGSTATE7)
  CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,90)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",2)
  CheckStatGT(Player2,0,SCRIPTINGSTATE7)
  CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",2)
  CheckStatGT(Player3,0,SCRIPTINGSTATE7)
  CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",2)
  CheckStatGT(Player4,0,SCRIPTINGSTATE7)
  CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",2)
  CheckStatGT(Player5,0,SCRIPTINGSTATE7)
  CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iajon19","LOCALS",1)
  Allegiance(Myself,ENEMY)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",2)
  CheckStatGT(Player6,0,SCRIPTINGSTATE7)
  CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  ActionListEmpty()
  HasItem("eneblade",Myself)
  See([PC])
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  ActionListEmpty()
  HasItem("eneblade",Myself)
  See(SecondNearest([PC]))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  ActionListEmpty()
  HasItem("eneblade",Myself)
  See(ThirdNearest([PC]))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  ActionListEmpty()
  HasItem("eneblade",Myself)
  See(FourthNearest([PC]))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  ActionListEmpty()
  HasItem("eneblade",Myself)
  See(FifthNearest([PC]))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  ActionListEmpty()
  HasItem("eneblade",Myself)
  See(SixthNearest([PC]))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !GlobalTimerNotExpired("truesight","LOCALS")
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See([PC])
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(SecondNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(ThirdNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap1nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap1nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  GlobalLT("Iacastbreach","LOCALS",6)
  Global("Iap1nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",6)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player1,2,SCRIPTINGSTATE6)
   CheckStat(Player1,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap2nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  GlobalLT("Iacastbreach","LOCALS",6)
  Global("Iap2nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",6)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player2,2,SCRIPTINGSTATE6)
   CheckStat(Player2,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap3nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  GlobalLT("Iacastbreach","LOCALS",6)
  Global("Iap3nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",6)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player3,2,SCRIPTINGSTATE6)
   CheckStat(Player3,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap4nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  GlobalLT("Iacastbreach","LOCALS",6)
  Global("Iap4nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",6)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player4,2,SCRIPTINGSTATE6)
   CheckStat(Player4,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap5nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  GlobalLT("Iacastbreach","LOCALS",6)
  Global("Iap5nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",6)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player5,2,SCRIPTINGSTATE6)
   CheckStat(Player5,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap6nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  HasItem("eneblade",Myself)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  GlobalLT("Iacastbreach","LOCALS",6)
  Global("Iap6nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",6)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player6,2,SCRIPTINGSTATE6)
   CheckStat(Player6,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  Global("Iajon19","LOCALS",0)
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iajon19","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  Global("Iajon19","LOCALS",0)
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobal("Iajon19","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  See(FourthNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  See(FifthNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon17","LOCALS",0)
  See(SixthNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),60)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  !GlobalTimerNotExpired("truesight","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
  Global("Iaremove","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iaremove","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  Global("Iajon05","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon05","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  Global("Iajon05","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon05","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  Global("Iajon05","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon05","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp1fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp1t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp1t","LOCALS")
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp1fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp2fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp2t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp2t","LOCALS")
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp2fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp3fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp3t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp3t","LOCALS")
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp3fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp4fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp4t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp4t","LOCALS")
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp4fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp5fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp5t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp5t","LOCALS")
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp5fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp6fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp6t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp6t","LOCALS")
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp6fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  HasItem("scrl7i",Myself)
  See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
  OR(3)
   CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
   CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
   CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
  GlobalLT("Iadeath","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iadeath","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl7i",LastSeenBy(Myself))  //
END

IF
  Allegiance(Myself,ENEMY)
  HasItem("scrl6v",Myself)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Iajon11","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon11","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6v",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  HasItem("scrl6v",Myself)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Iajon11","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon11","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6v",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  HasItem("scrl6v",Myself)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  !CheckStatGT(Myself,0,AURACLEANSING)
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Iajon11","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon11","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl6v",LastSeenBy(Myself)) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  Global("Iacomet","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iacomet","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  Global("Iacomet","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iacomet","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  Global("Iacomet","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iacomet","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iajon04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon04","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iajon04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon04","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iajon04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon04","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",1)
    SetGlobalTimer("Iamytime","LOCALS",36)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpellRES("SPWII26",Myself)
    ForceSpellRES("spwish17",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",2)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(Myself,WIZARD_ENERGY_BLADES)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",1)
    SetGlobalTimer("Iamytime","LOCALS",36)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpellRES("SPWII26",Myself)
    ForceSpellRES("spwish17",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",2)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(Myself,WIZARD_ENERGY_BLADES)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",1)
    SetGlobalTimer("Iamytime","LOCALS",36)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpellRES("SPWII26",Myself)
    ForceSpellRES("spwish17",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",2)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(Myself,WIZARD_ENERGY_BLADES)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(FourthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",1)
    SetGlobalTimer("Iamytime","LOCALS",36)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpellRES("SPWII26",Myself)
    ForceSpellRES("spwish17",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  See(FourthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",2)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(Myself,WIZARD_ENERGY_BLADES)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(FifthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",1)
    SetGlobalTimer("Iamytime","LOCALS",36)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpellRES("SPWII26",Myself)
    ForceSpellRES("spwish17",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  See(FifthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",2)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(Myself,WIZARD_ENERGY_BLADES)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SixthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",1)
    SetGlobalTimer("Iamytime","LOCALS",36)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpellRES("SPWII26",Myself)
    ForceSpellRES("spwish17",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  See(SixthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  Global("TimeStop","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("TimeStop","LOCALS",2)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
    SpellNoDec(Myself,WIZARD_ENERGY_BLADES)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  Global("Iajon02","LOCALS",0)
  See([PC])
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
THEN
  RESPONSE #100
    SetGlobal("Iajon02","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39969)  //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  Global("Iajon02","LOCALS",0)
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
THEN
  RESPONSE #100
    SetGlobal("Iajon02","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39969)  //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  Global("Iajon02","LOCALS",0)
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
THEN
  RESPONSE #100
    SetGlobal("Iajon02","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39969)  //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CONFUSION)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(NearestEnemyOfType([0.0.0.MAGE_ALL]))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iajon18","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon18","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearestEnemyOfType([0.0.0.MAGE_ALL]))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iajon18","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon18","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearestEnemyOfType([0.0.0.MAGE_ALL]))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iajon18","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon18","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(FourthNearestEnemyOfType([0.0.0.MAGE_ALL]))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  Global("Iajon18","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iajon18","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon18","LOCALS",0)
  See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Ianoward","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon18","LOCALS",0)
  See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Ianoward","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon18","LOCALS",0)
  See(ThirdNearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Ianoward","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  Global("Iajon18","LOCALS",0)
  See(FourthNearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !Class(LastSeenBy(Myself),CLERIC_ALL)
  !Class(LastSeenBy(Myself),FIGHTER_ALL)
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !HasBounceEffects(LastSeenBy(Myself))
  Global("Ianoward","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DISPEL_MAGIC)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iajon20","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon20","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iajon20","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon20","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iajon20","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon20","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(FourthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iajon20","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon20","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(FifthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iajon20","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon20","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SixthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iajon20","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon20","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaelectric","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  GlobalLT("Ialightning","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon20","LOCALS",1)
    SetGlobalTimer("Iaelectric","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaemotion","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  GlobalLT("Iajon07","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon07","LOCALS",1)
    SetGlobalTimer("Iaemotion","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaemotion","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  GlobalLT("Iajon07","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon07","LOCALS",1)
    SetGlobalTimer("Iaemotion","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaemotion","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  GlobalLT("Iajon07","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iajon07","LOCALS",1)
    SetGlobalTimer("Iaemotion","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iatouch","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),4)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iafarrow","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iafarrow","LOCALS",1)
    SetGlobalTimer("Iatouch","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iatouch","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),2)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iafarrow","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iafarrow","LOCALS",1)
    SetGlobalTimer("Iatouch","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_VAMPIRIC_TOUCH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iafarrow","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iafarrow","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iafarrow","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iafarrow","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaconjspl","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaconjspl","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  !StateCheck(Myself,STATE_HELPLESS)
  !StateCheck(Myself,STATE_CONFUSED)
  !StateCheck(Myself,STATE_STUNNED)
  !StateCheck(Myself,STATE_PANIC)
  !StateCheck(Myself,STATE_CHARMED)
  !Detect([PC])
  !Detect([GOODCUTOFF])
  GlobalGT("Iagolems","AR2806",0)
  InMyArea(Player1)
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
   SetGlobalTimer("Iaspell","LOCALS",6)
   SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(FourthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(FifthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SixthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iamytime","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END