// Add the Auramaster kit //

ADD_KIT ~AURAMASTER~
~AURAMASTER 1 0 1 1 0 0 0 1~ // clasweap
~AURAMASTER 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ // weapprof
~AURAMASTER 0 0 0 12 12 15~ // abclasrq
~AURAMASTER -4 0 -4 0 0 0~ // abclsmod
~AURAMASTER 0 0 0 12 12 15~ // abdcdsrq
~AURAMASTER 0 0 0 12 12 15~ // abdcscrq
~AURAMASTER 0 0 0 0 1 0 0 0 0~ // alignmnt
~AURAMASTER 0 0 0 0 0 0~ // dualclas
~ImprovedAnvil\resources\2da\AMDK.2Da~ // clab file
~K_D_H K_D_HE~ // allowed races
~0x10000000 11~ // usability & class flags
~Dr0~ // HLA table
~* * HELM19 BAG27 RING06 RING31 CLCK02 BOOT01 AMUL21 BRAC15 BELT10 * * * POTN52,5 POTN4,2 POTN14,5 HAMM07 SW1H27 STAF08~ // starting equipment
SAY @8955
SAY @8956
SAY @8957

LAF fl#add_kit_ee // launch_action_function start
  INT_VAR
    biography = "-1"
    briefdesc = RESOLVE_STR_REF (@8957)
    fallen = 0
  STR_VAR
    kit_name = ~AURAMASTER~
    clswpbon = ~0 0 3~
    clsrcreq = ~1 0 1 0 0 0 0~
END

// assign the new kit to Cernd
COPY_EXISTING ~CERND10.cre~ ~override~
              ~CERND14.cre~ ~override~
 WRITE_SHORT 0x244 0
 WRITE_BYTE  0x246 ~%AURAMASTER%~
 WRITE_BYTE  0x247 0x40

COPY_EXISTING ~cernd10.cre~ ~Override/cernd12.cre~
COPY_EXISTING ~cernd10.cre~ ~Override/cernd13.cre~
COPY_EXISTING ~cernd10.cre~ ~Override/cernd13b.cre~