// Add the Protector kit //

ADD_KIT ~PROTECTOR~
~PROTECTOR 1 1 1 1 1 1 1 1~ // clasweap
~PROTECTOR 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ // weapprof
~PROTECTOR 13 13 14 10 14 10~ // abclasrq
~PROTECTOR 0 0 -1 0 0 0~ // abclsmod
~PROTECTOR 17 17 14 10 17 10~ // abdcdsrq
~PROTECTOR 15 15 14 10 15 10~ // abdcscrq
~PROTECTOR 1 0 0 1 0 0 1 0 0~ // alignmnt
~PROTECTOR 0 0 0 0 0 0~ // dualclas
~ImprovedAnvil\resources\2da\Protec.2Da~ // clab file
~K_R_H K_R_HE K_R_E~ // allowed races
~0x00010000 12~ // usability & class flags
~Ra0~ // HLA table
~Leat14 * HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT07 * * * POTN52,5 POTN4,2 POTN14,5 HAMM07 SW1H27 SW1H55~ // starting equipment
SAY @8961
SAY @8962
SAY @8963

LAF fl#add_kit_ee // launch_action_function start
  INT_VAR
    biography = "-1"
    briefdesc = RESOLVE_STR_REF (@8963)
    fallen = 0
  STR_VAR
    kit_name = ~PROTECTOR~
    clswpbon = ~1 0 2~
    clsrcreq = ~1 1 1 0 0 0 0~
END

// Kit assignment to Valygar lives in creatures/04_patches_joinable.tph.