// Add the Vagrant kit //

ADD_KIT ~VAGRANT~
~VAGRANT 1 1 1 1 1 1 1 1~ // clasweap
~VAGRANT 2 2 2 2 2 2 5 1 2 2 2 5 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~ // weapprof
~VAGRANT 13 13 14 0 14 12~ // abclasrq
~VAGRANT 0 0 1 0 0 0~ // abclsmod
~VAGRANT 17 17 14 0 17 12~ // abdcdsrq
~VAGRANT 15 15 14 0 15 12~ // abdcscrq
~VAGRANT 1 0 0 1 0 0 1 0 0~ // alignmnt
~VAGRANT 0 0 0 0 0 0~ // dualclas
~ImprovedAnvil\resources\2da\Vagran.2Da~ // clab file
~K_R_H K_R_HE K_R_E~ // allowed races
~0x00010000 12~ // usability & class flags
~Ra0~ // HLA table
~Leat14 * HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT07 * * * POTN52,5 POTN4,2 POTN14,5 HAMM07 SW1H27 SW1H55~ // starting equipment
SAY @8950
SAY @8951
SAY @8952

LAF fl#add_kit_ee // launch_action_function start
  INT_VAR
    biography = "-1"
    briefdesc = RESOLVE_STR_REF (@8952)
    fallen = 0
  STR_VAR
    kit_name = ~VAGRANT~
    clswpbon = ~1 0 2~
    clsrcreq = ~1 1 1 0 0 0 0~
END