/// Brand-new IA spells ///

// common innates (spells) //

COPY ~ImprovedAnvil\resources\spells\SPINI01.spl~ ~override/SPINI01.spl~
  SAY NAME1 @388

COPY ~ImprovedAnvil\resources\spells\SPINI02.spl~ ~override/SPINI02.spl~
  SAY NAME1 @396

COPY ~ImprovedAnvil\resources\spells\SPINI03.spl~ ~override/SPINI03.spl~
  SAY NAME1 @397

COPY ~ImprovedAnvil\resources\spells\SPINI04.spl~ ~override/SPINI04.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI05.spl~ ~override/SPINI05.spl~
  SAY NAME1 @359

COPY ~ImprovedAnvil\resources\spells\SPINI06.spl~ ~override/SPINI06.spl~
  SAY NAME1 @360

COPY ~ImprovedAnvil\resources\spells\SPINI07.spl~ ~override/SPINI07.spl~
  SAY NAME1 @373

COPY ~ImprovedAnvil\resources\spells\SPINI08.spl~ ~override/SPINI08.spl~
  SAY NAME1 @9502

COPY ~ImprovedAnvil\resources\spells\SPINI09.spl~ ~override/SPINI09.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI10.spl~ ~override/SPINI10.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI11.spl~ ~override/SPINI11.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI12.spl~ ~override/SPINI12.spl~
  SAY NAME1 @9508

COPY ~ImprovedAnvil\resources\spells\SPINI13.spl~ ~override/SPINI13.spl~
  SAY NAME1 @9511

COPY ~ImprovedAnvil\resources\spells\SPINI14.spl~ ~override/SPINI14.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI15.spl~ ~override/SPINI15.spl~
  SAY NAME1 @9516

COPY ~ImprovedAnvil\resources\spells\SPINI16.spl~ ~override/SPINI16.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI17.spl~ ~override/SPINI17.spl~
  SAY NAME1 @9517

COPY ~ImprovedAnvil\resources\spells\SPINI18.spl~ ~override/SPINI18.spl~
  SAY NAME1 @9518

COPY ~ImprovedAnvil\resources\spells\SPINI19.spl~ ~override/SPINI19.spl~
  SAY NAME1 @9519

COPY ~ImprovedAnvil\resources\spells\SPINI20.spl~ ~override/SPINI20.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI21.spl~ ~override/SPINI21.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI22.spl~ ~override/SPINI22.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI23.spl~ ~override/SPINI23.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI24.spl~ ~override/SPINI24.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI25.spl~ ~override/SPINI25.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI26.spl~ ~override/SPINI26.spl~
  SAY NAME1 @9521

COPY ~ImprovedAnvil\resources\spells\SPINI27.spl~ ~override/SPINI27.spl~
  SAY NAME1 @9513

COPY ~ImprovedAnvil\resources\spells\SPINI28.spl~ ~override/SPINI28.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI29.spl~ ~override/SPINI29.spl~
  SAY NAME1 @9529

COPY ~ImprovedAnvil\resources\spells\SPINI30.spl~ ~override/SPINI30.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI31.spl~ ~override/SPINI31.spl~
  SAY NAME1 @9533

COPY ~ImprovedAnvil\resources\spells\SPINI32.spl~ ~override/SPINI32.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI33.spl~ ~override/SPINI33.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI34.spl~ ~override/SPINI34.spl~
  SAY NAME1 @9535

COPY ~ImprovedAnvil\resources\spells\SPINI35.spl~ ~override/SPINI35.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI36.spl~ ~override/SPINI36.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI37.spl~ ~override/SPINI37.spl~
  SAY NAME1 @9536

COPY ~ImprovedAnvil\resources\spells\SPINI38.spl~ ~override/SPINI38.spl~
  SAY NAME1 @9536

COPY ~ImprovedAnvil\resources\spells\SPINI39.spl~ ~override/SPINI39.spl~
  SAY NAME1 @9540

COPY ~ImprovedAnvil\resources\spells\SPINI40.spl~ ~override/SPINI40.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI41.spl~ ~override/SPINI41.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI42.spl~ ~override/SPINI42.spl~
  SAY NAME1 @9541

COPY ~ImprovedAnvil\resources\spells\SPINI43.spl~ ~override/SPINI43.spl~
  SAY NAME1 @9542

COPY ~ImprovedAnvil\resources\spells\SPINI44.spl~ ~override/SPINI44.spl~
  SAY NAME1 @9549

COPY ~ImprovedAnvil\resources\spells\SPINI45.spl~ ~override/SPINI45.spl~
  SAY NAME1 @9543

COPY ~ImprovedAnvil\resources\spells\SPINI46.spl~ ~override/SPINI46.spl~
  SAY NAME1 @9544

COPY ~ImprovedAnvil\resources\spells\SPINI47.spl~ ~override/SPINI47.spl~
  SAY NAME1 @9545

COPY ~ImprovedAnvil\resources\spells\SPINI48.spl~ ~override/SPINI48.spl~
  SAY NAME1 @9546

COPY ~ImprovedAnvil\resources\spells\SPINI49.spl~ ~override/SPINI49.spl~
  SAY NAME1 @9547

COPY ~ImprovedAnvil\resources\spells\SPINI50.spl~ ~override/SPINI50.spl~
  SAY NAME1 @9548

COPY ~ImprovedAnvil\resources\spells\SPINI51.spl~ ~override/SPINI51.spl~
  SAY NAME1 @9553

COPY ~ImprovedAnvil\resources\spells\SPINI52.spl~ ~override/SPINI52.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI53.spl~ ~override/SPINI53.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI54.spl~ ~override/SPINI54.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI55.spl~ ~override/SPINI55.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI56.spl~ ~override/SPINI56.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI57.spl~ ~override/SPINI57.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI58.spl~ ~override/SPINI58.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI59.spl~ ~override/SPINI59.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI60.spl~ ~override/SPINI60.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI61.spl~ ~override/SPINI61.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI62.spl~ ~override/SPINI62.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI63.spl~ ~override/SPINI63.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI64.spl~ ~override/SPINI64.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI65.spl~ ~override/SPINI65.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI66.spl~ ~override/SPINI66.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI67.spl~ ~override/SPINI67.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI68.spl~ ~override/SPINI68.spl~
  SAY NAME1 @9564

COPY ~ImprovedAnvil\resources\spells\SPINI69.spl~ ~override/SPINI69.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI70.spl~ ~override/SPINI70.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI71.spl~ ~override/SPINI71.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI72.spl~ ~override/SPINI72.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI73.spl~ ~override/SPINI73.spl~
  SAY NAME1 @9573

COPY ~ImprovedAnvil\resources\spells\SPINI74.spl~ ~override/SPINI74.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI75.spl~ ~override/SPINI75.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI76.spl~ ~override/SPINI76.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI77.spl~ ~override/SPINI77.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI78.spl~ ~override/SPINI78.spl~
  SAY NAME1 @9579

COPY ~ImprovedAnvil\resources\spells\SPINI79.spl~ ~override/SPINI79.spl~
  SAY NAME1 @9580

COPY ~ImprovedAnvil\resources\spells\SPINI80.spl~ ~override/SPINI80.spl~
  SAY NAME1 @9581

COPY ~ImprovedAnvil\resources\spells\SPINI81.spl~ ~override/SPINI81.spl~

COPY ~ImprovedAnvil\resources\spells\SPINI87.spl~ ~override/SPINI87.spl~
  SAY NAME1 @10195

COPY ~ImprovedAnvil\resources\spells\SPINI88.spl~ ~override/SPINI88.spl~
  SAY NAME1 @10197

COPY ~ImprovedAnvil\resources\spells\spini89.spl~ ~override/spini89.spl~

COPY ~ImprovedAnvil\resources\spells\spini90.spl~ ~override/spini90.spl~
  SAY NAME1 @10230
  SAY UNIDENTIFIED_DESC @10237

  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      check_headers = 1
      match_opcode = 328
      parameter2 = ~%perform_ritual_state%~
  END

// Conjure Clan Spirit
COPY ~ImprovedAnvil\resources\spells\spini91.spl~ ~override/spini91.spl~
  SAY NAME1 @10238
  SAY NAME2 @10238
  SAY UNIDENTIFIED_DESC @10360

COPY ~ImprovedAnvil\resources\spells\spini92.spl~ ~override/spini92.spl~
  SAY NAME1 @10220
  SAY NAME2 @10220
  SAY UNIDENTIFIED_DESC @10361

COPY ~ImprovedAnvil\resources\spells\spini93.spl~ ~override/spini93.spl~
  SAY NAME1 @10274
  SAY NAME2 @10274

COPY ~ImprovedAnvil\resources\spells\spini94.spl~ ~override/spini94.spl~
     ~ImprovedAnvil\resources\spells\spini94d.spl~ ~override/spini94d.spl~
  SAY NAME1 @10275
  SAY NAME2 @10275

COPY ~ImprovedAnvil\resources\spells\spini94c.spl~ ~override/spini94c.spl~
  SAY NAME1 #54387
  SAY NAME2 #54387

COPY ~ImprovedAnvil\resources\spells\spini95.spl~ ~override/spini95.spl~
  SAY NAME1 @10277
  SAY NAME2 @10277

COPY ~ImprovedAnvil\resources\spells\spini96.spl~ ~override/spini96.spl~
  SAY NAME1 @10279
  SAY NAME2 @10279

COPY ~ImprovedAnvil\resources\spells\spini97.spl~ ~override/spini97.spl~
     ~ImprovedAnvil\resources\spells\spini97d.spl~ ~override/spini97d.spl~
  SAY NAME1 @10280
  SAY NAME2 @10280

COPY ~ImprovedAnvil\resources\spells\spini98.spl~ ~override/spini98.spl~
  SAY NAME1 @10269
  SAY UNIDENTIFIED_DESC @10362

  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      check_headers = 1
      resist_dispel = 2
  END

COPY ~ImprovedAnvil\resources\spells\spini99.spl~ ~override/spini99.spl~

COPY ~ImprovedAnvil\resources\spells\spini101.spl~ ~override/spini101.spl~
  SAY NAME1 @10359
  SAY NAME2 @10359
  SAY UNIDENTIFIED_DESC @10364

COPY ~ImprovedAnvil\resources\spells\spini104.spl~ ~override/spini104.spl~
  SAY NAME1 @12102
  SAY NAME2 @12102

  // Dynamically assign proper projectile
  LAUNCH_PATCH_FUNCTION ~ALTER_SPELL_HEADER~ INT_VAR
    header_type = 2
    projectile = ~%S!corrcl%~
  END

  // assign proper spell state
  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      check_headers = 1
      match_opcode = 328
      parameter2 = ~%corrosive_cloud_state%~
  END

// class level abilities //

COPY ~ImprovedAnvil\resources\spells\SPCLI01.spl~ ~override/SPCLI01.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI02.spl~ ~override/SPCLI02.spl~
  SAY NAME1 @9505

COPY ~ImprovedAnvil\resources\spells\SPCLI03.spl~ ~override/SPCLI03.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI04.spl~ ~override/SPCLI04.spl~
  SAY NAME1 @9522

COPY ~ImprovedAnvil\resources\spells\SPCLI05.spl~ ~override/SPCLI05.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI06.spl~ ~override/SPCLI06.spl~
  SAY NAME1 @9534

COPY ~ImprovedAnvil\resources\spells\SPCLI07.spl~ ~override/SPCLI07.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI08.spl~ ~override/SPCLI08.spl~
  SAY NAME1 @9534

COPY ~ImprovedAnvil\resources\spells\SPCLI09.spl~ ~override/SPCLI09.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI10.spl~ ~override/SPCLI10.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI11.spl~ ~override/SPCLI11.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI12.spl~ ~override/SPCLI12.spl~
  SAY NAME1 @9568
  SAY UNIDENTIFIED_DESC @9569

COPY ~ImprovedAnvil\resources\spells\SPCLI13.spl~ ~override/SPCLI13.spl~
  SAY NAME1 @9571
  SAY UNIDENTIFIED_DESC @9561

COPY ~ImprovedAnvil\resources\spells\SPCLI14.spl~ ~override/SPCLI14.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI15.spl~ ~override/SPCLI15.spl~
  SAY NAME1 @9576
  SAY UNIDENTIFIED_DESC @9577

COPY ~ImprovedAnvil\resources\spells\SPCLI16.spl~ ~override/SPCLI16.spl~
  SAY NAME1 @9583
  SAY UNIDENTIFIED_DESC @9584

COPY ~ImprovedAnvil\resources\spells\SPCLI17.spl~ ~override/SPCLI17.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI18.spl~ ~override/SPCLI18.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI19.spl~ ~override/SPCLI19.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI20.spl~ ~override/SPCLI20.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI21.spl~ ~override/SPCLI21.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI22.spl~ ~override/SPCLI22.spl~
  SAY NAME1 @11136
  SAY UNIDENTIFIED_DESC @11137

COPY ~ImprovedAnvil\resources\spells\SPCLI23.spl~ ~override/SPCLI23.spl~
  SAY NAME1 @11140
  SAY UNIDENTIFIED_DESC @11141

COPY ~ImprovedAnvil\resources\spells\SPCLI24.spl~ ~override/SPCLI24.spl~
  SAY NAME1 @11142
  SAY UNIDENTIFIED_DESC @11143

COPY ~ImprovedAnvil\resources\spells\SPCLI25.spl~ ~override/SPCLI25.spl~
  SAY NAME1 @11144
  SAY UNIDENTIFIED_DESC @11145

COPY ~ImprovedAnvil\resources\spells\SPCLI26.spl~ ~override/SPCLI26.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI27.spl~ ~override/SPCLI27.spl~
  SAY NAME1 @11154
  SAY UNIDENTIFIED_DESC @11155

COPY ~ImprovedAnvil\resources\spells\SPCLI28.spl~ ~override/SPCLI28.spl~

COPY ~ImprovedAnvil\resources\spells\SPCLI29.spl~ ~override/SPCLI29.spl~

// priest spells //

COPY ~ImprovedAnvil\resources\spells\SPPRI01.spl~ ~override/SPPRI01.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI02.spl~ ~override/SPPRI02.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI03.spl~ ~override/SPPRI03.spl~
  SAY NAME1 @371

COPY ~ImprovedAnvil\resources\spells\SPPRI04.spl~ ~override/SPPRI04.spl~
  SAY NAME1 @381

COPY ~ImprovedAnvil\resources\spells\SPPRI05.spl~ ~override/SPPRI05.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI06.spl~ ~override/SPPRI06.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI07.spl~ ~override/SPPRI07.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI08.spl~ ~override/SPPRI08.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI09.spl~ ~override/SPPRI09.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI10.spl~ ~override/SPPRI10.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI11.spl~ ~override/SPPRI11.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI12.spl~ ~override/SPPRI12.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI13.spl~ ~override/SPPRI13.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI14.spl~ ~override/SPPRI14.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI15.spl~ ~override/SPPRI15.spl~
  SAY NAME1 @9523
  SAY UNIDENTIFIED_DESC @9524

COPY ~ImprovedAnvil\resources\spells\SPPRI16.spl~ ~override/SPPRI16.spl~
  SAY NAME1 @9525
  SAY UNIDENTIFIED_DESC @9526

COPY ~ImprovedAnvil\resources\spells\SPPRI17.spl~ ~override/SPPRI17.spl~
  SAY NAME1 @9527
  SAY UNIDENTIFIED_DESC @9528

COPY ~ImprovedAnvil\resources\spells\SPPRI18.spl~ ~override/SPPRI18.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI20.spl~ ~override/SPPRI20.spl~
  SAY NAME1 @9101
  SAY UNIDENTIFIED_DESC @9102

COPY ~ImprovedAnvil\resources\spells\SPPRI21.spl~ ~override/SPPRI21.spl~
  SAY NAME1 @9103
  SAY UNIDENTIFIED_DESC @9104

COPY ~ImprovedAnvil\resources\spells\SPPRI22.spl~ ~override/SPPRI22.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI23.spl~ ~override/SPPRI23.spl~

COPY ~ImprovedAnvil\resources\spells\SPPRI24.spl~ ~override/SPPRI24.spl~
  SAY NAME1 @9578

COPY ~ImprovedAnvil\resources\spells\SPPRI25.spl~ ~override/SPPRI25.spl~
  SAY NAME1 @9525

COPY ~ImprovedAnvil\resources\spells\SPPRI26.spl~ ~override/SPPRI26.spl~
  SAY NAME1 @11147
  SAY UNIDENTIFIED_DESC @11148

COPY ~ImprovedAnvil\resources\spells\SPPRI26A.spl~ ~override/SPPRI26A.spl~
  SAY NAME1 @11147

COPY ~ImprovedAnvil\resources\spells\SPPRI27.spl~ ~override/SPPRI27.spl~
  SAY NAME1 @11149
  SAY UNIDENTIFIED_DESC @11150

COPY ~ImprovedAnvil\resources\spells\SPPRI28.spl~ ~override/SPPRI28.spl~
  SAY NAME1 @11187
  SAY UNIDENTIFIED_DESC @11188

COPY ~ImprovedAnvil\resources\spells\SPPR445.spl~ ~override/SPPR445.spl~
  SAY NAME1 @10357
  SAY UNIDENTIFIED_DESC @10358

COPY ~ImprovedAnvil\resources\spells\SPPR446.spl~ ~override/SPPR446.spl~
  SAY NAME1 #6701

COPY ~ImprovedAnvil\resources\spells\SPPR447.spl~ ~override/SPPR447.spl~
  SAY NAME1 #11052

COPY ~ImprovedAnvil\resources\spells\SPPR448.spl~ ~override/SPPR448.spl~
  SAY NAME1 #6351

COPY ~ImprovedAnvil\resources\spells\SPPR449.spl~ ~override/SPPR449.spl~
  SAY NAME1 #6350

COPY ~ImprovedAnvil\resources\spells\SPPR545.spl~ ~override/SPPR545.spl~
  SAY NAME1 @10345
  SAY UNIDENTIFIED_DESC @10346

COPY ~ImprovedAnvil\resources\spells\SPPR546.spl~ ~override/SPPR546.spl~
  SAY NAME1 @10347

COPY ~ImprovedAnvil\resources\spells\SPPR547.spl~ ~override/SPPR547.spl~
  SAY NAME1 @10348

COPY ~ImprovedAnvil\resources\spells\SPPR548.spl~ ~override/SPPR548.spl~
  SAY NAME1 @10349

COPY ~ImprovedAnvil\resources\spells\SPPR549.spl~ ~override/SPPR549.spl~
  SAY NAME1 @10350

COPY ~ImprovedAnvil\resources\spells\SPPR649.spl~ ~override/SPPR649.spl~
  SAY NAME1 @10354
  SAY UNIDENTIFIED_DESC @10355

  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      check_headers = 1
      match_opcode = 328
      parameter2 = ~%immune_fear_state%~
  END

COPY ~ImprovedAnvil\resources\spells\SPPR749.spl~ ~override/SPPR749.spl~
  SAY NAME1 @10351
  SAY UNIDENTIFIED_DESC @10352

// wizard spells //

COPY ~ImprovedAnvil\resources\spells\SPWII01.spl~ ~override/SPWII01.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII02.spl~ ~override/SPWII02.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII03.spl~ ~override/SPWII03.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII04.spl~ ~override/SPWII04.spl~
  SAY NAME1 @398

COPY ~ImprovedAnvil\resources\spells\SPWII05.spl~ ~override/SPWII05.spl~
  SAY NAME1 @398

COPY ~ImprovedAnvil\resources\spells\SPWII06.spl~ ~override/SPWII06.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII07.spl~ ~override/SPWII07.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII08.spl~ ~override/SPWII08.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII09.spl~ ~override/SPWII09.spl~
  SAY NAME1 @368

COPY ~ImprovedAnvil\resources\spells\SPWII10.spl~ ~override/SPWII10.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII11.spl~ ~override/SPWII11.spl~
  SAY NAME1 @369

COPY ~ImprovedAnvil\resources\spells\SPWII12.spl~ ~override/SPWII12.spl~
  SAY NAME1 @370

COPY ~ImprovedAnvil\resources\spells\SPWII13.spl~ ~override/SPWII13.spl~
  SAY NAME1 @9531

COPY ~ImprovedAnvil\resources\spells\SPWII14.spl~ ~override/SPWII14.spl~
  SAY NAME1 @374

COPY ~ImprovedAnvil\resources\spells\SPWII15.spl~ ~override/SPWII15.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII16.spl~ ~override/SPWII16.spl~
  SAY NAME1 @375

COPY ~ImprovedAnvil\resources\spells\SPWII17.spl~ ~override/SPWII17.spl~
  SAY NAME1 @374

COPY ~ImprovedAnvil\resources\spells\SPWII18.spl~ ~override/SPWII18.spl~
  SAY NAME1 @376

COPY ~ImprovedAnvil\resources\spells\SPWII19.spl~ ~override/SPWII19.spl~
  SAY NAME1 @377

COPY ~ImprovedAnvil\resources\spells\SPWII20.spl~ ~override/SPWII20.spl~
  SAY NAME1 @378

COPY ~ImprovedAnvil\resources\spells\SPWII21.spl~ ~override/SPWII21.spl~
  SAY NAME1 @380

COPY ~ImprovedAnvil\resources\spells\SPWII22.spl~ ~override/SPWII22.spl~
  SAY NAME1 @382

COPY ~ImprovedAnvil\resources\spells\SPWII23.spl~ ~override/SPWII23.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII24.spl~ ~override/SPWII24.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII25.spl~ ~override/SPWII25.spl~
  SAY NAME1 @383

COPY ~ImprovedAnvil\resources\spells\SPWII26.spl~ ~override/SPWII26.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII27.spl~ ~override/SPWII27.spl~
  SAY NAME1 @385

COPY ~ImprovedAnvil\resources\spells\SPWII28.spl~ ~override/SPWII28.spl~
  SAY NAME1 @386

COPY ~ImprovedAnvil\resources\spells\SPWII29.spl~ ~override/SPWII29.spl~
  SAY NAME1 @387

COPY ~ImprovedAnvil\resources\spells\SPWII30.spl~ ~override/SPWII30.spl~
  SAY NAME1 @391

COPY ~ImprovedAnvil\resources\spells\SPWII31.spl~ ~override/SPWII31.spl~
  SAY NAME1 @391

COPY ~ImprovedAnvil\resources\spells\SPWII32.spl~ ~override/SPWII32.spl~
  SAY NAME1 @9500

COPY ~ImprovedAnvil\resources\spells\SPWII33.spl~ ~override/SPWII33.spl~
  SAY NAME1 @9501

COPY ~ImprovedAnvil\resources\spells\SPWII34.spl~ ~override/SPWII34.spl~
  SAY NAME1 @9507

COPY ~ImprovedAnvil\resources\spells\SPWII35.spl~ ~override/SPWII35.spl~
  SAY NAME1 @9509

COPY ~ImprovedAnvil\resources\spells\SPWII36.spl~ ~override/SPWII36.spl~
  SAY NAME1 @9510

COPY ~ImprovedAnvil\resources\spells\SPWII37.spl~ ~override/SPWII37.spl~
  SAY NAME1 @9515

COPY ~ImprovedAnvil\resources\spells\SPWII38.spl~ ~override/SPWII38.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII39.spl~ ~override/SPWII39.spl~
  SAY NAME1 @9530

COPY ~ImprovedAnvil\resources\spells\SPWII40.spl~ ~override/SPWII40.spl~
  SAY NAME1 @9537

COPY ~ImprovedAnvil\resources\spells\SPWII41.spl~ ~override/SPWII41.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII42.spl~ ~override/SPWII42.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII43.spl~ ~override/SPWII43.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII44.spl~ ~override/SPWII44.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII45.spl~ ~override/SPWII45.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII46.spl~ ~override/SPWII46.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII47.spl~ ~override/SPWII47.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII48.spl~ ~override/SPWII48.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII49.spl~ ~override/SPWII49.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII50.spl~ ~override/SPWII50.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII51.spl~ ~override/SPWII51.spl~
  SAY NAME1 @9572

COPY ~ImprovedAnvil\resources\spells\SPWII52.spl~ ~override/SPWII52.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII53.spl~ ~override/SPWII53.spl~
  SAY NAME1 @9574

COPY ~ImprovedAnvil\resources\spells\SPWII54.spl~ ~override/SPWII54.spl~
  SAY NAME1 @9575

COPY ~ImprovedAnvil\resources\spells\SPWII55.spl~ ~override/SPWII55.spl~
  SAY NAME1 @9156

COPY ~ImprovedAnvil\resources\spells\SPWII56.spl~ ~override/SPWII56.spl~
  SAY NAME1 @9156

COPY ~ImprovedAnvil\resources\spells\SPWII58.spl~ ~override/SPWII58.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII59.spl~ ~override/SPWII59.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII60.spl~ ~override/SPWII60.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII61.spl~ ~override/SPWII61.spl~

COPY ~ImprovedAnvil\resources\spells\SPWII62.spl~ ~override/SPWII62.spl~

// spells with IA's filename prefix //

COPY ~ImprovedAnvil\resources\spells\S!chan3a.spl~ ~override/S!chan3a.spl~
  SAY NAME1 @12040
  SAY NAME2 @12040

COPY ~ImprovedAnvil\resources\spells\S!chan3b.spl~ ~override/S!chan3b.spl~
  SAY NAME1 @12041
  SAY NAME2 @12041

  LPF ALTER_SPELL_EFFECT INT_VAR
    check_headers = 1
    header_type = 1
    match_opcode = 206
    parameter1 = RESOLVE_STR_REF (@11132)
  END

COPY ~ImprovedAnvil\resources\spells\S!xp.spl~ ~override/S!xp.spl~

COPY ~ImprovedAnvil\resources\spells\S!misva1.spl~ ~override/S!misva1.spl~

COPY ~ImprovedAnvil\resources\spells\S!misva2.spl~ ~override/S!misva2.spl~

COPY ~ImprovedAnvil\resources\spells\S!helmb1.spl~ ~override/S!helmb1.spl~
  SAY NAME1 @10292
  SAY NAME2 @10292

  // Set a custom string for Display String opcode
  LPF ALTER_SPELL_EFFECT INT_VAR
    check_headers = 1
    header_type = 1
    match_opcode = 139
    parameter1 = RESOLVE_STR_REF (@10293)
  END

COPY ~ImprovedAnvil\resources\spells\S!helmb2.spl~ ~override/S!helmb2.spl~
  SAY NAME1 @10292
  SAY NAME2 @10292

  // Set a custom string for Display String opcode
  LPF ALTER_SPELL_EFFECT INT_VAR
    check_headers = 1
    header_type = 1
    match_opcode = 139
    parameter1 = RESOLVE_STR_REF (@10294)
  END

COPY ~ImprovedAnvil\resources\spells\S!helmb3.spl~ ~override/S!helmb3.spl~
  SAY NAME1 @10292
  SAY NAME2 @10292

  // Set a custom string for Display String opcode
  LPF ALTER_SPELL_EFFECT INT_VAR
    check_headers = 1
    header_type = 1
    match_opcode = 139
    parameter1 = RESOLVE_STR_REF (@10295)
  END

COPY ~ImprovedAnvil\resources\spells\S!helmb4.spl~ ~override/S!helmb4.spl~
  SAY NAME1 @10292
  SAY NAME2 @10292

  // Set a custom string for Display String opcode
  LPF ALTER_SPELL_EFFECT INT_VAR
    check_headers = 1
    header_type = 1
    match_opcode = 139
    parameter1 = RESOLVE_STR_REF (@10296)
  END

COPY ~ImprovedAnvil/resources/spells/S!dru00.spl~ ~override/S!dru00.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru01.spl~ ~override/S!dru01.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru02.spl~ ~override/S!dru02.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru03.spl~ ~override/S!dru03.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru04.spl~ ~override/S!dru04.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru05.spl~ ~override/S!dru05.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru06.spl~ ~override/S!dru06.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru07.spl~ ~override/S!dru07.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru08.spl~ ~override/S!dru08.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru09.spl~ ~override/S!dru09.spl~
  SAY NAME1 @12090

COPY ~ImprovedAnvil/resources/spells/S!dru10.spl~ ~override/S!dru10.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru11.spl~ ~override/S!dru11.spl~

COPY ~ImprovedAnvil/resources/spells/S!dru12.spl~ ~override/S!dru12.spl~
  SAY NAME1 @388

COPY ~ImprovedAnvil/resources/spells/S!dru13.spl~ ~override/S!dru13.spl~
  SAY NAME1 @397

COPY ~ImprovedAnvil/resources/spells/S!werhwl.spl~ ~override/S!werhwl.spl~
  SAY NAME1 @12072

  LPF ~ALTER_SPELL_EFFECT~
    INT_VAR
      check_globals = 1
      check_headers = 0
      match_opcode = 328
      parameter2 = ~%immune_fear_state%~
  END

COPY ~ImprovedAnvil/resources/spells/S!werrag.spl~ ~override/S!werrag.spl~
  SAY NAME1 @12073

// Troll falling to the ground
COPY ~ImprovedAnvil/resources/spells/S!trlreg.spl~ ~override/S!trlreg.spl~
  LPF ADD_SPELL_EFFECT
    INT_VAR
      opcode = 318
      target = 1
      timing = 0
      resist_dispel = 0
      duration = 0
      parameter1 = 12
      parameter2 = %hp_greater_than%
      insert_point = 0
    STR_VAR
      resource = ~S!trlreg~
  END

// Add new healing spells for the Shaman //

ACTION_PHP_EACH shaman_healing_spells AS record => int BEGIN
  // add the new spell into the game
  ADD_SPELL ~ImprovedAnvil\resources\spells\%record_0%.spl~ 1 record_1 ~%record_2%~
    SAY NAME1 (AT record_3)
    SAY NAME2 (AT record_3)
    SAY UNIDENTIFIED_DESC (AT record_4)

    // update the icon references
    WRITE_ASCIIE 0x003a ~%record_0%c~ #8
    GET_OFFSET_ARRAY headers SPL_V10_HEADERS

    PHP_EACH headers AS int => off BEGIN
      WRITE_ASCIIE 0x04 + off ~%record_0%b~ #8
    END

    // update the portrait icon
    PATCH_IF record_5 > 0 BEGIN
      LPF ALTER_SPELL_EFFECT INT_VAR
        check_headers = 1
        match_opcode = 142
        parameter2 = record_5
      END
    END

    // add the split-second aura cleansing effect
    LPF ADD_SPELL_EFFECT
      INT_VAR
        header = 2
        opcode = 146
        target = 1
        parameter2 = 1
      STR_VAR
        resource = ~SPPRI25~
    END

  // copy the spell icons
  COPY ~ImprovedAnvil\resources\bam\%record_0%b.bam~ ~override/%record_0%b.bam~
  COPY ~ImprovedAnvil\resources\bam\%record_0%c.bam~ ~override/%record_0%c.bam~

  ACTION_IF record_5 > 0 BEGIN
    COPY ~ImprovedAnvil\resources\bam\%record_0%d.bam~ ~override/%record_0%d.bam~
  END

  // create a spell that gives this mending spell when a "cure XX wounds" spell is detected
  COPY ~ImprovedAnvil/resources/intermediate/shaman_replace_spells.spl~ ~override/%record_0%r.spl~
    LPF ALTER_SPELL_HEADER
      INT_VAR
        target = 1
    END

    // resolve the new spell's resource name
    LPF RES_NAME_OF_SPELL_NUM INT_VAR spell_num = EVALUATE_BUFFER ~%record_2%~ RET spell_res END

    LPF ADD_SPELL_EFFECT
      INT_VAR
        header = 1
        opcode = 171
        target = 2
        timing = 9
      STR_VAR
        resource = EVALUATE_BUFFER "%spell_res%"
    END

  // add the new spell to a list of exclusion from automatically learnable spells
  COPY_EXISTING ~hidespl.2da~ ~override/hidespl.2da~
    COUNT_2DA_COLS ~colcount~
    COUNT_2DA_ROWS ~colcount~ ~rowcount~
    INSERT_2DA_ROW ~rowcount~ ~colcount~ ~%spell_res% 1 0 0~
    PRETTY_PRINT_2DA

  // generate code for baldur.bcs that checks and applies spell replacement when necessary
  OUTER_SPRINT OldSpellSymbolicName ~%record_6%~
  OUTER_SPRINT SpellRes ~%record_0%r~

  OUTER_FOR (PlayerNum = 6; PlayerNum > 0; PlayerNum -= 1) BEGIN
    EXTEND_TOP ~BALDUR.BCS~ ~ImprovedAnvil/resources/intermediate/shaman_replace_spells.baf~
      SET StrRef = RESOLVE_STR_REF (@11128)
      EVALUATE_BUFFER
  END
END

// testing weapons //

COPY ~ImprovedAnvil\resources\spells\SUPERSPL.spl~ ~override/SUPERSPL.spl~
  SAY NAME1 @12087

  LAUNCH_PATCH_FUNCTION ~ALTER_SPELL_HEADER~ INT_VAR
    header_type = 1
    projectile = ~%S!SUPER%~
  END

	LPF ALTER_EFFECT
		INT_VAR
			check_headers = 1
			match_target = 5
      target = 2
	END

  LPF CLONE_EFFECT
    INT_VAR
      check_globals = 0
      match_opcode = 58
      opcode = 139
      parameter1 = 14056
    STR_VAR
      insert = ~below~
  END

COPY ~ImprovedAnvil\resources\spells\SUPERDMG.spl~ ~override/SUPERDMG.spl~
  SAY NAME1 @12088

  LAUNCH_PATCH_FUNCTION ~ALTER_SPELL_HEADER~ INT_VAR
    header_type = 2
    projectile = ~%S!SUPER%~
  END
