// 1,000,000 //

IF
  CheckStatGT(Player1,7999999,44)
  CheckStatLT(LastSummonerOf(Myself),7000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,7499999,44)
  CheckStatLT(LastSummonerOf(Myself),6500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,6999999,44)
  CheckStatLT(LastSummonerOf(Myself),6000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,6499999,44)
  CheckStatLT(LastSummonerOf(Myself),5500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,5999999,44)
  CheckStatLT(LastSummonerOf(Myself),5000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,5499999,44)
  CheckStatLT(LastSummonerOf(Myself),4500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,4999999,44)
  CheckStatLT(LastSummonerOf(Myself),4000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,4499999,44)
  CheckStatLT(LastSummonerOf(Myself),3500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,3999999,44)
  CheckStatLT(LastSummonerOf(Myself),3000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,3499999,44)
  CheckStatLT(LastSummonerOf(Myself),2500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,2999999,44)
  CheckStatLT(LastSummonerOf(Myself),2000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,2499999,44)
  CheckStatLT(LastSummonerOf(Myself),1500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,1999999,44)
  CheckStatLT(LastSummonerOf(Myself),1000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

IF
  CheckStatGT(Player1,1499999,44)
  CheckStatLT(LastSummonerOf(Myself),500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),1000000)
END

// 333,000 //

IF
  CheckStatGT(Player1,3999999,44)
  CheckStatLT(LastSummonerOf(Myself),3666667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,3666666,44)
  CheckStatLT(LastSummonerOf(Myself),3333334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,3333333,44)
  CheckStatLT(LastSummonerOf(Myself),3000001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,2999999,44)
  CheckStatLT(LastSummonerOf(Myself),2666667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,2666666,44)
  CheckStatLT(LastSummonerOf(Myself),2333334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,2333333,44)
  CheckStatLT(LastSummonerOf(Myself),2000001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,1999999,44)
  CheckStatLT(LastSummonerOf(Myself),1666667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,1666666,44)
  CheckStatLT(LastSummonerOf(Myself),1333334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,1333333,44)
  CheckStatLT(LastSummonerOf(Myself),1000001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,999999,44)
  CheckStatLT(LastSummonerOf(Myself),666667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

IF
  CheckStatGT(Player1,666666,44)
  CheckStatLT(LastSummonerOf(Myself),333334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),333333)
END

// 100,000 //

IF
  CheckStatGT(Player1,2999999,44)
  CheckStatLT(LastSummonerOf(Myself),2900000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2899999,44)
  CheckStatLT(LastSummonerOf(Myself),2800000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2799999,44)
  CheckStatLT(LastSummonerOf(Myself),2700000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2699999,44)
  CheckStatLT(LastSummonerOf(Myself),2600000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2599999,44)
  CheckStatLT(LastSummonerOf(Myself),2500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2499999,44)
  CheckStatLT(LastSummonerOf(Myself),2400000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2399999,44)
  CheckStatLT(LastSummonerOf(Myself),2300000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2299999,44)
  CheckStatLT(LastSummonerOf(Myself),2200000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2199999,44)
  CheckStatLT(LastSummonerOf(Myself),2100000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,2099999,44)
  CheckStatLT(LastSummonerOf(Myself),2000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1999999,44)
  CheckStatLT(LastSummonerOf(Myself),1900000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1899999,44)
  CheckStatLT(LastSummonerOf(Myself),1800000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1799999,44)
  CheckStatLT(LastSummonerOf(Myself),1700000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1699999,44)
  CheckStatLT(LastSummonerOf(Myself),1600000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1599999,44)
  CheckStatLT(LastSummonerOf(Myself),1500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1499999,44)
  CheckStatLT(LastSummonerOf(Myself),1400000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1399999,44)
  CheckStatLT(LastSummonerOf(Myself),1300000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1299999,44)
  CheckStatLT(LastSummonerOf(Myself),1200000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1199999,44)
  CheckStatLT(LastSummonerOf(Myself),1100000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,1099999,44)
  CheckStatLT(LastSummonerOf(Myself),1000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,999999,44)
  CheckStatLT(LastSummonerOf(Myself),900000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,899999,44)
  CheckStatLT(LastSummonerOf(Myself),800000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,799999,44)
  CheckStatLT(LastSummonerOf(Myself),700000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,699999,44)
  CheckStatLT(LastSummonerOf(Myself),600000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,599999,44)
  CheckStatLT(LastSummonerOf(Myself),500000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,499999,44)
  CheckStatLT(LastSummonerOf(Myself),400000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,399999,44)
  CheckStatLT(LastSummonerOf(Myself),300000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,299999,44)
  CheckStatLT(LastSummonerOf(Myself),200000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

IF
  CheckStatGT(Player1,199999,44)
  CheckStatLT(LastSummonerOf(Myself),100000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),100000)
END

// 33,333 //

IF
  CheckStatGT(Player1,2999999,44)
  CheckStatLT(LastSummonerOf(Myself),2966667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2966666,44)
  CheckStatLT(LastSummonerOf(Myself),2933334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2933333,44)
  CheckStatLT(LastSummonerOf(Myself),2900001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2899999,44)
  CheckStatLT(LastSummonerOf(Myself),2866667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2866666,44)
  CheckStatLT(LastSummonerOf(Myself),2833334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2833333,44)
  CheckStatLT(LastSummonerOf(Myself),2800001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2799999,44)
  CheckStatLT(LastSummonerOf(Myself),2766667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2766666,44)
  CheckStatLT(LastSummonerOf(Myself),2733334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2733333,44)
  CheckStatLT(LastSummonerOf(Myself),2700001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2699999,44)
  CheckStatLT(LastSummonerOf(Myself),2666667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2666666,44)
  CheckStatLT(LastSummonerOf(Myself),2633334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2633333,44)
  CheckStatLT(LastSummonerOf(Myself),2600001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2599999,44)
  CheckStatLT(LastSummonerOf(Myself),2566667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2566666,44)
  CheckStatLT(LastSummonerOf(Myself),2533334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2533333,44)
  CheckStatLT(LastSummonerOf(Myself),2500001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2499999,44)
  CheckStatLT(LastSummonerOf(Myself),2466667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2466666,44)
  CheckStatLT(LastSummonerOf(Myself),2433334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2433333,44)
  CheckStatLT(LastSummonerOf(Myself),2400001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2399999,44)
  CheckStatLT(LastSummonerOf(Myself),2366667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2366666,44)
  CheckStatLT(LastSummonerOf(Myself),2333334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2333333,44)
  CheckStatLT(LastSummonerOf(Myself),2300001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2299999,44)
  CheckStatLT(LastSummonerOf(Myself),2266667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2266666,44)
  CheckStatLT(LastSummonerOf(Myself),2233334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2233333,44)
  CheckStatLT(LastSummonerOf(Myself),2200001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2199999,44)
  CheckStatLT(LastSummonerOf(Myself),2166667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2166666,44)
  CheckStatLT(LastSummonerOf(Myself),2133334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2133333,44)
  CheckStatLT(LastSummonerOf(Myself),2100001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2099999,44)
  CheckStatLT(LastSummonerOf(Myself),2066667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2066666,44)
  CheckStatLT(LastSummonerOf(Myself),2033334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,2033333,44)
  CheckStatLT(LastSummonerOf(Myself),2000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1999999,44)
  CheckStatLT(LastSummonerOf(Myself),1966667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1966666,44)
  CheckStatLT(LastSummonerOf(Myself),1933334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1933333,44)
  CheckStatLT(LastSummonerOf(Myself),1900001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1899999,44)
  CheckStatLT(LastSummonerOf(Myself),1866667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1866666,44)
  CheckStatLT(LastSummonerOf(Myself),1833334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1833333,44)
  CheckStatLT(LastSummonerOf(Myself),1800001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1799999,44)
  CheckStatLT(LastSummonerOf(Myself),1766667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1766666,44)
  CheckStatLT(LastSummonerOf(Myself),1733334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1733333,44)
  CheckStatLT(LastSummonerOf(Myself),1700001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1699999,44)
  CheckStatLT(LastSummonerOf(Myself),1666667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1666666,44)
  CheckStatLT(LastSummonerOf(Myself),1633334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1633333,44)
  CheckStatLT(LastSummonerOf(Myself),1600001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1599999,44)
  CheckStatLT(LastSummonerOf(Myself),1566667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1566666,44)
  CheckStatLT(LastSummonerOf(Myself),1533334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1533333,44)
  CheckStatLT(LastSummonerOf(Myself),1500001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1499999,44)
  CheckStatLT(LastSummonerOf(Myself),1466667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1466666,44)
  CheckStatLT(LastSummonerOf(Myself),1433334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1433333,44)
  CheckStatLT(LastSummonerOf(Myself),1400001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1399999,44)
  CheckStatLT(LastSummonerOf(Myself),1366667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1366666,44)
  CheckStatLT(LastSummonerOf(Myself),1333334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1333333,44)
  CheckStatLT(LastSummonerOf(Myself),1300001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1299999,44)
  CheckStatLT(LastSummonerOf(Myself),1266667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1266666,44)
  CheckStatLT(LastSummonerOf(Myself),1233334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1233333,44)
  CheckStatLT(LastSummonerOf(Myself),1200001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1199999,44)
  CheckStatLT(LastSummonerOf(Myself),1166667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1166666,44)
  CheckStatLT(LastSummonerOf(Myself),1133334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1133333,44)
  CheckStatLT(LastSummonerOf(Myself),1100001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1099999,44)
  CheckStatLT(LastSummonerOf(Myself),1066667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1066666,44)
  CheckStatLT(LastSummonerOf(Myself),1033334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,1033333,44)
  CheckStatLT(LastSummonerOf(Myself),1000000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,999999,44)
  CheckStatLT(LastSummonerOf(Myself),966667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,966666,44)
  CheckStatLT(LastSummonerOf(Myself),933334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,933333,44)
  CheckStatLT(LastSummonerOf(Myself),900001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,899999,44)
  CheckStatLT(LastSummonerOf(Myself),866667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,866666,44)
  CheckStatLT(LastSummonerOf(Myself),833334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,833333,44)
  CheckStatLT(LastSummonerOf(Myself),800001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,799999,44)
  CheckStatLT(LastSummonerOf(Myself),766667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,766666,44)
  CheckStatLT(LastSummonerOf(Myself),733334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,733333,44)
  CheckStatLT(LastSummonerOf(Myself),700001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,699999,44)
  CheckStatLT(LastSummonerOf(Myself),666667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,666666,44)
  CheckStatLT(LastSummonerOf(Myself),633334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,633333,44)
  CheckStatLT(LastSummonerOf(Myself),600001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,599999,44)
  CheckStatLT(LastSummonerOf(Myself),566667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,566666,44)
  CheckStatLT(LastSummonerOf(Myself),533334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,533333,44)
  CheckStatLT(LastSummonerOf(Myself),500001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,499999,44)
  CheckStatLT(LastSummonerOf(Myself),466667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,466666,44)
  CheckStatLT(LastSummonerOf(Myself),433334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,433333,44)
  CheckStatLT(LastSummonerOf(Myself),400001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,399999,44)
  CheckStatLT(LastSummonerOf(Myself),366667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,366666,44)
  CheckStatLT(LastSummonerOf(Myself),333334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,333333,44)
  CheckStatLT(LastSummonerOf(Myself),300001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,299999,44)
  CheckStatLT(LastSummonerOf(Myself),266667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,266666,44)
  CheckStatLT(LastSummonerOf(Myself),233334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,233333,44)
  CheckStatLT(LastSummonerOf(Myself),200001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,199999,44)
  CheckStatLT(LastSummonerOf(Myself),166667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,166666,44)
  CheckStatLT(LastSummonerOf(Myself),133334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,133333,44)
  CheckStatLT(LastSummonerOf(Myself),100001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,99999,44)
  CheckStatLT(LastSummonerOf(Myself),66667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

IF
  CheckStatGT(Player1,66666,44)
  CheckStatLT(LastSummonerOf(Myself),33334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),33333)
END

// 10,000 //

IF
  CheckStatGT(Player1,199999,44)
  CheckStatLT(LastSummonerOf(Myself),190000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,189999,44)
  CheckStatLT(LastSummonerOf(Myself),180000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,179999,44)
  CheckStatLT(LastSummonerOf(Myself),170000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,169999,44)
  CheckStatLT(LastSummonerOf(Myself),160000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,159999,44)
  CheckStatLT(LastSummonerOf(Myself),150000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,149999,44)
  CheckStatLT(LastSummonerOf(Myself),140000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,139999,44)
  CheckStatLT(LastSummonerOf(Myself),130000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,129999,44)
  CheckStatLT(LastSummonerOf(Myself),120000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,119999,44)
  CheckStatLT(LastSummonerOf(Myself),110000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,109999,44)
  CheckStatLT(LastSummonerOf(Myself),100000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,99999,44)
  CheckStatLT(LastSummonerOf(Myself),90000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,89999,44)
  CheckStatLT(LastSummonerOf(Myself),80000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,79999,44)
  CheckStatLT(LastSummonerOf(Myself),70000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,69999,44)
  CheckStatLT(LastSummonerOf(Myself),60000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,59999,44)
  CheckStatLT(LastSummonerOf(Myself),50000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,49999,44)
  CheckStatLT(LastSummonerOf(Myself),40000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,39999,44)
  CheckStatLT(LastSummonerOf(Myself),30000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,29999,44)
  CheckStatLT(LastSummonerOf(Myself),20000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

IF
  CheckStatGT(Player1,19999,44)
  CheckStatLT(LastSummonerOf(Myself),10000,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),10000)
END

// 3,333 //

IF
  CheckStatGT(Player1,99999,44)
  CheckStatLT(LastSummonerOf(Myself),96667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),3333)
END

IF
  CheckStatGT(Player1,96666,44)
  CheckStatLT(LastSummonerOf(Myself),93334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),3333)
END

IF
  CheckStatGT(Player1,93333,44)
  CheckStatLT(LastSummonerOf(Myself),90001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),3333)
END

IF
  CheckStatGT(Player1,89999,44)
  CheckStatLT(LastSummonerOf(Myself),86667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),3333)
END

IF
  CheckStatGT(Player1,86666,44)
  CheckStatLT(LastSummonerOf(Myself),83334,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),3333)
END

IF
  CheckStatGT(Player1,83333,44)
  CheckStatLT(LastSummonerOf(Myself),80001,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),3333)
END

IF
  CheckStatGT(Player1,79999,44)
  CheckStatLT(LastSummonerOf(Myself),76667,44)
THEN
  RESPONSE #100
    AddXpObject(LastSummonerOf(Myself),3333)
END

IF
  True()
THEN
  RESPONSE #100
    DestroySelf()
END
