//Ghost spider ///

IF
  Global("Iaexit","ARia06",0)
  InMyArea(Player1)
THEN
  RESPONSE #100
    SetGlobal("Iaexit","ARia06",1)
    TriggerActivation("Trania01",FALSE)
    TriggerActivation("Trania06",FALSE)
END

IF
  Global("Iaexit","ARia06",1)
  Dead("S!spided")
THEN
  RESPONSE #100
    SetGlobal("Iaexit","ARia06",2)
    TriggerActivation("Trania01",TRUE)
    TriggerActivation("Trania06",TRUE)
END