// Extended druid stronghold, the Diviner appears //

IF
  TRUE()
THEN
  RESPONSE #100
    CutSceneId(Player1)
    SetInterrupt(FALSE)

    Wait(1)

    // TODO: the Diviner teleports in via the portal

    Wait(2)

    ActionOverride("S!drudiv",DisplayStringHead(Myself,@5889))
    Wait(1)
    ActionOverride("S!drudiv",DisplayStringHead(Myself,@5890))
    Wait(1)

    ActionOverride("S!dracof",StartDialogNoSet(Player1))

    MultiPlayerSync()
    SetInterrupt(TRUE)
    EndCutSceneMode()
END