// Extended druid stronghold, Felaern arrives at the docks of Balduran's Isle //

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)

    Wait(1)
    MoveViewObject(Myself,INSTANT)
    SmallWait(1)
    CreateCreatureDoor("S!gdru02",[4200.3195],0)
    Wait(5)

    ActionOverride("s!gdru02",FaceObject(Player1))
    ActionOverride("s!gdru02",StartDialogNoSet(Player1))

    MultiPlayerSync()
    EndCutSceneMode()
END