// Fighter Mage Cleric //
// Levels 39 32 39 //
// Mage Spells: //
// First level spells (8): MM x8 //
// Second level spells (8): Melf Acid Arrow x8 //
// Third level spells (8): remove magic, Flame arrow x7 //
// Fourth level spells (8): Stoneskin x5, Imp invis, fire shield, Confusion //
// Fifth level spells (8): spell immunity, Lower res x3, Breach x4 //
// Sixth level spells (8): True Sight, PfMW x5, Death Spell x2//
// Seventh level spells (8): ruby ray x5, finger of death x2, pwstun //
// Eight level spells (7): ADHW x 7 //
// Ninth level spells (7): Dragons Breath x3, Comet x4 //
// Clerical spells: //
// First level spells (13): Armor of faith x5, Command x8//
// Second level spells (12): Hold Person x9 //
// Third level spells (10): Rigid Thinking x3, dispel magic x7 //
// Fourth level spells (11): //
// Fifth level spells (9): Greater Command x9 //
// Sixth level spells (9): Heal x2, Physical Mirror, Bolt of Glory x6 //
// Seventh level spells (9): Shield O'Arcons, Regeneration, Globe of Blades x7 //
// Scrolls: spellstrike x3 //

IF
  See(NearestEnemyOf(Myself))
  Global("Prep","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Prep","LOCALS",1)
    SetGlobalTimer("blades","LOCALS",60)
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
    ReallyForceSpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    ReallyForceSpellRES("SPWII41",Myself)
    ReallyForceSpellRES("SPPR725",Myself) //
    ReallyForceSpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)
    ReallyForceSpell(Myself,CLERIC_PHYSICAL_MIRROR)
    ReallyForceSpell(Myself,CLERIC_ARMOR_OF_FAITH)
    ReallyForceSpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  Global("Iadoonce","LOCALS",0)
  HPPercentLT(Myself,100)
THEN
  RESPONSE #100
    SetGlobal("Iadoonce","LOCALS",1)
    ReallyForceSpellRES("SPWII07",Myself)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  Global("Iadoonce","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadoonce","LOCALS",1)
END

IF
  Allegiance(Myself,ENEMY)
  OR(2)
   Detect([PC])
   Detect([GOODCUTOFF])
  Global("partyfled","LOCALS",1)
THEN
  RESPONSE #100
    SetGlobal("partyfled","LOCALS",0)
END

IF
  Allegiance(Myself,ENEMY)
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),6)
  Global("Iaskins","LOCALS",4)
  CheckStatLT(Myself,1,STONESKINS)
  HPPercentLT(Myself,100)
  !HPLT(Myself,1)
  Global("Iasendai01","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasendai01","LOCALS",1)
    DisplayString(Myself,29736) // Contingency - Stoneskin
    ReallyForceSpell(Myself,WIZARD_STONE_SKIN)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  HPPercentLT(Myself,100)
  See(NearestEnemyOf(Myself))
  Range(LastSeenBy(Myself),4)
  OR(2)
   !GlobalTimerNotExpired("pfmw","LOCALS")
   CheckStat(Myself,0,SCRIPTINGSTATE6)
  GlobalLT("Iasendai02","LOCALS",5)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai02","LOCALS",1)
    SetGlobalTimer("pfmw","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  GlobalLT("Iaskins","LOCALS",4)
  CheckStatLT(Myself,1,STONESKINS)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iaskins","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_STONE_SKIN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player1)
  Global("Iap1nr","GLOBAL",0)
  HPLT(Player1,90)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player2)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player3)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player4)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player5)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player6)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player1)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
  Global("Iap1nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player1,0,SCRIPTINGSTATE7)
   CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,90)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player2)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player2,0,SCRIPTINGSTATE7)
   CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player3)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player3,0,SCRIPTINGSTATE7)
   CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player4)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player4,0,SCRIPTINGSTATE7)
   CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player5)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player5,0,SCRIPTINGSTATE7)
   CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player6)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",1)
  OR(2)
   CheckStatGT(Player6,0,SCRIPTINGSTATE7)
   CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  CheckStatLT(Player1,25,RESISTMAGIC)
  !CheckStat(Player1,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player1)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_PANIC)
  !CheckStat(Player1,1,SCRIPTINGSTATE4)
  !CheckStat(Player1,1,SCRIPTINGSTATE5)
  Global("Iap1nr","GLOBAL",2)
  CheckStatGT(Player1,0,SCRIPTINGSTATE7)
  CheckStatGT(Player1,0,MINORGLOBE)
  HPLT(Player1,90)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  CheckStatLT(Player2,25,RESISTMAGIC)
  HPLT(Player2,90)
  !CheckStat(Player2,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player2)
  !StateCheck(Player2,STATE_STUNNED)
  !StateCheck(Player2,STATE_HELPLESS)
  !StateCheck(Player2,STATE_CONFUSED)
  !StateCheck(Player2,STATE_PANIC)
  !CheckStat(Player2,1,SCRIPTINGSTATE4)
  !CheckStat(Player2,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player2)
  Global("Iap2nr","GLOBAL",2)
  CheckStatGT(Player2,0,SCRIPTINGSTATE7)
  CheckStatGT(Player2,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  CheckStatLT(Player3,25,RESISTMAGIC)
  HPLT(Player3,90)
  !CheckStat(Player3,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player3)
  !StateCheck(Player3,STATE_STUNNED)
  !StateCheck(Player3,STATE_HELPLESS)
  !StateCheck(Player3,STATE_CONFUSED)
  !StateCheck(Player3,STATE_PANIC)
  !CheckStat(Player3,1,SCRIPTINGSTATE4)
  !CheckStat(Player3,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player3)
  Global("Iap3nr","GLOBAL",2)
  CheckStatGT(Player3,0,SCRIPTINGSTATE7)
  CheckStatGT(Player3,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  CheckStatLT(Player4,25,RESISTMAGIC)
  HPLT(Player4,90)
  !CheckStat(Player4,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player4)
  !StateCheck(Player4,STATE_STUNNED)
  !StateCheck(Player4,STATE_HELPLESS)
  !StateCheck(Player4,STATE_CONFUSED)
  !StateCheck(Player4,STATE_PANIC)
  !CheckStat(Player4,1,SCRIPTINGSTATE4)
  !CheckStat(Player4,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player4)
  Global("Iap4nr","GLOBAL",2)
  CheckStatGT(Player4,0,SCRIPTINGSTATE7)
  CheckStatGT(Player4,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  CheckStatLT(Player5,25,RESISTMAGIC)
  HPLT(Player5,90)
  !CheckStat(Player5,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player5)
  !StateCheck(Player5,STATE_STUNNED)
  !StateCheck(Player5,STATE_HELPLESS)
  !StateCheck(Player5,STATE_CONFUSED)
  !StateCheck(Player5,STATE_PANIC)
  !CheckStat(Player5,1,SCRIPTINGSTATE4)
  !CheckStat(Player5,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player5)
  Global("Iap5nr","GLOBAL",2)
  CheckStatGT(Player5,0,SCRIPTINGSTATE7)
  CheckStatGT(Player5,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_POWER_WORD_STUN)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
  Allegiance(Myself,ENEMY)
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  CheckStatLT(Player6,25,RESISTMAGIC)
  HPLT(Player6,90)
  !CheckStat(Player6,2,SCRIPTINGSTATE7)
  !HasBounceEffects(Player6)
  !StateCheck(Player6,STATE_STUNNED)
  !StateCheck(Player6,STATE_HELPLESS)
  !StateCheck(Player6,STATE_CONFUSED)
  !StateCheck(Player6,STATE_PANIC)
  !CheckStat(Player6,1,SCRIPTINGSTATE4)
  !CheckStat(Player6,1,SCRIPTINGSTATE5)
  !HasItemEquiped("S!sw02",Player6)
  Global("Iap6nr","GLOBAL",2)
  CheckStatGT(Player6,0,SCRIPTINGSTATE7)
  CheckStatGT(Player6,0,MINORGLOBE)
THEN
  RESPONSE #100
    IncrementGlobal("Iastun","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_POWER_WORD_STUN)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  Detect([PC])
  Global("Iatreasure","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatreasure","LOCALS",1)
    GiveItemCreate("S!ring08",Myself,0,0,0) //
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  Detect([PC])
  Global("Iatreasure2","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatreasure2","LOCALS",1)
    GiveItemCreate("S!scrl10",Myself,0,0,0) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("blades","LOCALS")
  GlobalLT("Iablades","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Iablades","LOCALS",1)
    SetGlobalTimer("blades","LOCALS",53)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPR725",Myself) //
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  CheckStat(Myself,0,SCRIPTINGSTATE6)
  CheckStatLT(Myself,55,RESISTSLASHING)
  See(NearestEnemyOf(Myself))
  GlobalLT("Iafaith","LOCALS",4)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    IncrementGlobal("Iafaith","LOCALS",1)
    SpellNoDec(Myself,CLERIC_ARMOR_OF_FAITH)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  CheckStatLT(Myself,86,RESISTSLASHING)
  CheckStat(Myself,0,SCRIPTINGSTATE6)
  HPPercentLT(Myself,90)
  See(NearestEnemyOf(Myself))
  GlobalLT("Iasendai06","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai06","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    ForceSpell(Myself,WARRIOR_HARDINESS)
END

IF
  ActionListEmpty()
  Allegiance(Myself,ENEMY)
  HPPercentLT(Myself,75)
  See([PC])
  CheckStatLT(LastSeenBy(Myself),75,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  Global("Iaccontin","LOCALS",0)
  !HPLT(Myself,1)
THEN
  RESPONSE #100
    SetGlobal("Iaccontin","LOCALS",1)
    DisplayString(Myself,26328) //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  HPPercentLT(Myself,75)
  !HPLT(Myself,1)
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  Global("Iatrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrigger","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39968) //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  Allegiance(Myself,ENEMY)
  ActionListEmpty()
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  HPPercentLT(Myself,75)
  !HPLT(Myself,1)
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTELECTRICITY)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  Global("Iatrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iatrigger","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayString(Myself,39968) //
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_CHAIN_LIGHTNING)
END

IF
  See(NearestEnemyOf(Myself))
  HPPercentLT(Myself,50)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  HasItem("POTN55",Myself)  // ~Potion of Superior Healing~
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46150)  // ~quaffs a potion~
    UseItem("POTN55",Myself)  // ~Potion of Superior Healing~
END

IF
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iasendai03","LOCALS",0)
  HPPercentLT(Myself,30)
THEN
  RESPONSE #100
    SetGlobal("Iasendai03","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_HEAL)
END

IF
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iasendai03","LOCALS",1)
  HPPercentLT(Myself,30)
THEN
  RESPONSE #100
    SetGlobal("Iasendai03","LOCALS",2)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_HEAL)
END

IF
  !CheckStatGT(Myself,0,SCRIPTINGSTATE9)
  See(NearestEnemyOf(Myself))
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iasendai03","LOCALS",2)
  HPPercentLT(Myself,30)
THEN
  RESPONSE #100
    SetGlobal("Iasendai03","LOCALS",3)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,CLERIC_REGENERATE)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See(Player1)
  LevelLT(Player1,37)
  Class(Player1,PALADIN_ALL)
  Range(Player1,12)
  !StateCheck(Player1,STATE_PANIC)
  !StateCheck(Player1,STATE_CONFUSED)
  !StateCheck(Player1,STATE_HELPLESS)
  !StateCheck(Player1,STATE_STUNNED)
  !StateCheck(Player1,STATE_CHARMED)
  !HasItemEquiped("hamm11",Player1)
  !HasItemEquiped("sw1h32",Player1)
  !HasItemEquiped("S!sw04",Player1)
  !HasItemEquiped("S!sw11",Player1)
  !HasItemEquiped("S!halb01",Player1)
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66",Player1)
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See("keldorn")
  !Dead("keldorn")
  LevelLT("keldorn",37)
  Class("keldorn",PALADIN_ALL)
  Range("keldorn",12)
  !StateCheck("keldorn",STATE_PANIC)
  !StateCheck("keldorn",STATE_CONFUSED)
  !StateCheck("keldorn",STATE_HELPLESS)
  !StateCheck("keldorn",STATE_STUNNED)
  !HasItemEquiped("hamm11","keldorn")
  !HasItemEquiped("sw1h32","keldorn")
  !HasItemEquiped("S!sw04","keldorn")
  !HasItemEquiped("S!sw11","keldorn")
  !HasItemEquiped("S!halb01","keldorn")
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66","keldorn")
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
  LevelLT(LastSeenBy(Myself),37)
  Range(LastSeenBy(Myself),12)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
  !HasItemEquiped("hamm11",LastSeenBy(Myself))
  !HasItemEquiped("sw1h32",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66",LastSeenBy(Myself))
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
  LevelLT(LastSeenBy(Myself),37)
  Range(LastSeenBy(Myself),12)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_CHARMED)
  !HasItemEquiped("hamm11",LastSeenBy(Myself))
  !HasItemEquiped("sw1h32",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    ApplySpellRES("SPINI66",LastSeenBy(Myself))
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  Range(LastSeenBy(Myself),12)
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iapcastts","GLOBAL",0)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaturntime","LOCALS")
  GlobalLT("Iaturning","LOCALS",2)
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  Range(LastSeenBy(Myself),12)
THEN
  RESPONSE #100
    IncrementGlobal("Iaturning","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Isturning","LOCALS",6)
    Turn()
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iaturning","LOCALS",2)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaturntime","LOCALS",24)
    SetGlobal("Iaturning","LOCALS",0)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  OR(2)
   CheckStatGT(Myself,0,SCRIPTINGSTATE9)
   Global("Iapcastts","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaspell","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  HasItem("scrl9m",Myself)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iaspellstrike","LOCALS",3)
  GlobalGT("Iap1nr","GLOBAL",1)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap1nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9m",Player1) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap1nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap1nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap1nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  !CheckStat(Player1,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player1,2,SCRIPTINGSTATE6)
   CheckStat(Player1,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap1nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  HasItem("scrl9m",Myself)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iaspellstrike","LOCALS",3)
  GlobalGT("Iap2nr","GLOBAL",1)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap2nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9m",Player2) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap2nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap2nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap2nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  !CheckStat(Player2,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player2,2,SCRIPTINGSTATE6)
   CheckStat(Player2,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap2nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  HasItem("scrl9m",Myself)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iaspellstrike","LOCALS",3)
  GlobalGT("Iap3nr","GLOBAL",1)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap3nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9m",Player3) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap3nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap3nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap3nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  !CheckStat(Player3,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player3,2,SCRIPTINGSTATE6)
   CheckStat(Player3,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap3nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  HasItem("scrl9m",Myself)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iaspellstrike","LOCALS",3)
  GlobalGT("Iap4nr","GLOBAL",1)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap4nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9m",Player4) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap4nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap4nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap4nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  !CheckStat(Player4,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player4,2,SCRIPTINGSTATE6)
   CheckStat(Player4,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap4nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  HasItem("scrl9m",Myself)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iaspellstrike","LOCALS",3)
  GlobalGT("Iap5nr","GLOBAL",1)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap5nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9m",Player5) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap5nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap5nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap5nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  !CheckStat(Player5,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player5,2,SCRIPTINGSTATE6)
   CheckStat(Player5,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap5nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  HasItem("scrl9m",Myself)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iaspellstrike","LOCALS",3)
  GlobalGT("Iap6nr","GLOBAL",1)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
THEN
  RESPONSE #100
    IncrementGlobal("Iaspellstrike","LOCALS",1)
    SetGlobal("Iap6nr","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    DisplayStringHead(Myself,46153) //
    UseItem("scrl9m",Player6) //
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  GlobalGT("Iap6nr","GLOBAL",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    IncrementGlobal("Iap6nr","GLOBAL",-1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iacastbreach","LOCALS",4)
  Global("Iap6nb","GLOBAL",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iafmbreach","LOCALS")
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iacastbreach","LOCALS",4)
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  !CheckStat(Player6,1,SCRIPTINGSTATE7)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_TURNING)
  !CheckSpellState(LastSeenBy(Myself),WIZARD_SPELL_SHIELD)
  OR(2)
   CheckStatGT(Player6,2,SCRIPTINGSTATE6)
   CheckStat(Player6,1,SCRIPTINGSTATE11)
THEN
  RESPONSE #100
    IncrementGlobal("Iacastbreach","LOCALS",1)
    SetGlobal("Iap6nb","GLOBAL",0)
    SetGlobalTimer("Iafmbreach","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_BREACH)
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iacastbreach","LOCALS",4)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iadispelpfmw","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispelpfmw","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  Global("Iacastbreach","LOCALS",4)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  GlobalLT("Iadispelpfmw","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispelpfmw","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("Iaremoves","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iaremoves","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("Iaremoves","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iaremoves","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  Global("Iaremoves","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iaremoves","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Iadispelpot","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iadispelpot","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iabreath","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  GlobalLT("Iasendai16","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai16","LOCALS",1)
    SetGlobalTimer("Iabreath","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iabreath","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  GlobalLT("Iasendai16","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai16","LOCALS",1)
    SetGlobalTimer("Iabreath","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iabreath","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  GlobalLT("Iasendai16","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai16","LOCALS",1)
    SetGlobalTimer("Iabreath","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DRAGONS_BREATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp1fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp1t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player1)
  !StateCheck(Player1,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player1,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap1nr","GLOBAL",0)
  Global("Iacheckp1fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp1t","LOCALS")
  OR(2)
   CheckStatGT(Player1,0,MINORGLOBE)
   HasBounceEffects(Player1)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp1fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player1,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp2fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp2t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player2)
  !StateCheck(Player2,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player2,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap2nr","GLOBAL",0)
  Global("Iacheckp2fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp2t","LOCALS")
  OR(2)
   CheckStatGT(Player2,0,MINORGLOBE)
   HasBounceEffects(Player2)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp2fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player2,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp3fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp3t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player3)
  !StateCheck(Player3,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player3,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap3nr","GLOBAL",0)
  Global("Iacheckp3fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp3t","LOCALS")
  OR(2)
   CheckStatGT(Player3,0,MINORGLOBE)
   HasBounceEffects(Player3)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp3fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player3,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp4fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp4t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player4)
  !StateCheck(Player4,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player4,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap4nr","GLOBAL",0)
  Global("Iacheckp4fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp4t","LOCALS")
  OR(2)
   CheckStatGT(Player4,0,MINORGLOBE)
   HasBounceEffects(Player4)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp4fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player4,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp5fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp5t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player5)
  !StateCheck(Player5,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player5,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap5nr","GLOBAL",0)
  Global("Iacheckp5fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp5t","LOCALS")
  OR(2)
   CheckStatGT(Player5,0,MINORGLOBE)
   HasBounceEffects(Player5)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp5fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player5,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",0)
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
THEN
  RESPONSE #100
    SetGlobal("Iacheckp6fr","LOCALS",1)
    SetGlobalTimer("Iarubyonp6t","LOCALS",6)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(Player6)
  !StateCheck(Player6,STATE_IMPROVEDINVISIBILITY)
  !StateCheck(Player6,STATE_INVISIBLE)
  GlobalLT("Iareversal","LOCALS",5)
  Global("Iap6nr","GLOBAL",0)
  Global("Iacheckp6fr","LOCALS",1)
  GlobalTimerExpired("Iarubyonp6t","LOCALS")
  OR(2)
   CheckStatGT(Player6,0,MINORGLOBE)
   HasBounceEffects(Player6)
THEN
  RESPONSE #100
    IncrementGlobal("Iareversal","LOCALS",1)
    SetGlobal("Iacheckp6fr","LOCALS",0)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Player6,WIZARD_RUBY_RAY_OF_REVERSAL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Ialower","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Ialower","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Ialower","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Ialower","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatGT(LastSeenBy(Myself),24,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  GlobalLT("Ialower","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Ialower","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_LOWER_RESISTANCE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iacomet","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  GlobalLT("Iasendai17","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai17","LOCALS",1)
    SetGlobalTimer("Iacomet","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iacomet","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  GlobalLT("Iasendai17","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai17","LOCALS",1)
    SetGlobalTimer("Iacomet","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iacomet","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,RESISTFIRE)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  GlobalLT("Iasendai17","LOCALS",4)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai17","LOCALS",1)
    SetGlobalTimer("Iacomet","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_COMET)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  See([PC])
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iasendai04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasendai04","LOCALS",1)
    DisplayString(Myself,39969)  // ~Spell Sequencer - Fired~
    SetGlobalTimer("Iaspell","LOCALS",6)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  Global("Iapcastts","GLOBAL",0)
  See(SecondNearest([PC]))
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  CheckStat(LastSeenBy(Myself),0,SCRIPTINGSTATE3)
  Global("Iasendai04","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasendai04","LOCALS",1)
    DisplayString(Myself,39969)  // ~Spell Sequencer - Fired~
    SetGlobalTimer("Iaspell","LOCALS",6)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_EMOTION_HOPELESSNESS)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SLOW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("truesight","LOCALS")
  See([PC])
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("truesight","LOCALS")
  See(SecondNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("truesight","LOCALS")
  See(ThirdNearest([PC]))
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaexrm","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  OR(3)
   StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
   StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
   StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
THEN
  RESPONSE #100
    SetGlobalTimer("Iaexrm","LOCALS",24)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("truesight","LOCALS")
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
  GlobalLT("Iaremove","LOCALS",4)
THEN
  RESPONSE #100
    SetGlobalTimer("truesight","LOCALS",60)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(Myself,WIZARD_TRUE_SIGHT)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY.0]))
  Global("Iaremove","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Iaremove","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  GlobalLT("Iadeath","LOCALS",3)
  See(NearestEnemyOfType([GOODCUTOFF.0.0.0.0.SUMMONED]))
  !Class(LastSeenBy(Myself),SKELETON)
  !Class(LastSeenBy(Myself),SKELETON_WARRIOR)
  OR(3)
   CheckStat(LastSeenBy(Myself),20,RESISTSLASHING)
   CheckStat(LastSeenBy(Myself),95,RESISTPIERCING)
   CheckStatGT(LastSeenBy(Myself),89,RESISTMAGIC)
THEN
  RESPONSE #100
    IncrementGlobal("Iadeath","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagww","LOCALS")
  See([PC])
  Range(LastSeenBy(Myself),5)
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
  GlobalLT("Iasendai13","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai13","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Iagww","LOCALS",18)
    ForceSpell(Myself,WARRIOR_GREATER_WHIRLWIND)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iahla","LOCALS")
  See([PC])
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
  CheckStatLT(LastSeenBy(Myself),1,STONESKINS)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  Range(LastSeenBy(Myself),5)
  GlobalLT("Iasendai14","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai14","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Iahla","LOCALS",18)
    ForceSpell(Myself,WARRIOR_CRITICAL_STRIKE)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iafinger","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Iafinger","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iafinger","LOCALS",2)
THEN
  RESPONSE #100
    IncrementGlobal("Iafinger","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FINGER_OF_DEATH)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOfType([PC.0.0.MAGE_ALL]))
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearestEnemyOfType([PC.0.0.MAGE_ALL]))
  OR(2)
   CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE2)
   CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  Global("Ianoward","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Ianoward","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SixthNearest([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),90)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  Global("Iadispel","LOCALS",0)
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispel","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(FifthNearest([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),90)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  Global("Iadispel","LOCALS",0)
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispel","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(FourthNearest([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),90)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  Global("Iadispel","LOCALS",0)
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispel","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),90)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  Global("Iadispel","LOCALS",0)
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispel","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),90)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  Global("Iadispel","LOCALS",0)
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispel","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !HasBounceEffects(LastSeenBy(Myself))
  CheckStatLT(LastSeenBy(Myself),25,RESISTMAGIC)
  HPLT(LastSeenBy(Myself),90)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  Global("Iadispel","LOCALS",0)
  Global("Iastun","LOCALS",0)
  Global("Iaremoves","LOCALS",1)
THEN
  RESPONSE #100
    IncrementGlobal("Iadispel","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagcommand","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iasendai09","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai09","LOCALS",1)
    SetGlobalTimer("Iagcommand","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagcommand","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iasendai09","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai09","LOCALS",1)
    SetGlobalTimer("Iagcommand","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagcommand","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  GlobalLT("Iasendai09","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai09","LOCALS",1)
    SetGlobalTimer("Iagcommand","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_GREATER_COMMAND)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb01",LastSeenBy(Myself))
  Global("Ianoward2","LOCALS",0)
THEN
  RESPONSE #100
    IncrementGlobal("Ianoward2","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDecRES("SPPRI02",LastSeenBy(Myself))
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(SixthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iasendai12","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai12","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(FifthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iasendai12","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai12","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(FourthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iasendai12","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai12","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iasendai12","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai12","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iasendai12","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai12","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaglory","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  CheckStatLT(LastSeenBy(Myself),90,RESISTMISSILE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  GlobalLT("Iasendai12","LOCALS",6)
THEN
  RESPONSE #100
    IncrementGlobal("Iasendai12","LOCALS",1)
    SetGlobalTimer("Iaglory","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_BOLT_OF_GLORY)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See([PC])
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),51,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iahorrid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See(SecondNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),51,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iahorrid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See(ThirdNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),51,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iahorrid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See(FourthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),51,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iahorrid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See(FifthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),51,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iahorrid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iawilting","LOCALS")
  See(SixthNearest([PC]))
  CheckStatLT(LastSeenBy(Myself),100,MAGICDAMAGERESISTANCE)
  CheckStatLT(LastSeenBy(Myself),51,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),5,SCRIPTINGSTATE7)
  !HasItemEquiped("S!halb02",LastSeenBy(Myself))
  GlobalLT("Iahorrid","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iahorrid","LOCALS",1)
    SetGlobalTimer("Iawilting","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_ABI_DALZIMS_HORRID_WILTING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  Global("Iasendai07","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasendai07","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  Global("Iasendai07","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasendai07","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  Global("Iasendai07","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasendai07","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_CONFUSION)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iagww","LOCALS")
  See([PC])
  Range(LastSeenBy(Myself),5)
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
  Global("Iasendai15","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("Iasendai15","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SetGlobalTimer("Iagww","LOCALS",18)
    ForceSpell(Myself,WARRIOR_WHIRLWIND)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaholdp","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !Kit(LastSeenBy(Myself),INQUISITOR)
  GlobalLT("Iahperson","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iahperson","LOCALS",1)
    SetGlobalTimer("Iaholdp","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaholdp","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !Kit(LastSeenBy(Myself),INQUISITOR)
  GlobalLT("Iahperson","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iahperson","LOCALS",1)
    SetGlobalTimer("Iaholdp","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaholdp","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE5)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("sw1h27",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw02",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !Kit(LastSeenBy(Myself),INQUISITOR)
  GlobalLT("Iahperson","LOCALS",9)
THEN
  RESPONSE #100
    IncrementGlobal("Iahperson","LOCALS",1)
    SetGlobalTimer("Iaholdp","LOCALS",18)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_HOLD_PERSON)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iathinking","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iarigid","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iarigid","LOCALS",1)
    SetGlobalTimer("Iathinking","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iathinking","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iarigid","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iarigid","LOCALS",1)
    SetGlobalTimer("Iathinking","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
  Allegiance(Myself,ENEMY)
  !StateCheck(Myself,STATE_SILENCED)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iathinking","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !HasItemEquiped("shld25",LastSeenBy(Myself))
  !HasItemEquiped("leat20",LastSeenBy(Myself))
  !HasItemEquiped("sw2h14",LastSeenBy(Myself))
  !HasItemEquiped("S!helm05",LastSeenBy(Myself))
  !HasItemEquiped("S!leat03",LastSeenBy(Myself))
  !HasItemEquiped("S!sw22",LastSeenBy(Myself))
  !HasItemEquiped("S!sw21",LastSeenBy(Myself))
  !HasItemEquiped("S!shld01",LastSeenBy(Myself))
  !HasItemEquiped("S!sw04",LastSeenBy(Myself))
  !HasItemEquiped("S!sw07",LastSeenBy(Myself))
  !HasItemEquiped("S!sw08",LastSeenBy(Myself))
  !HasItemEquiped("S!sw09",LastSeenBy(Myself))
  !HasItemEquiped("S!sw10",LastSeenBy(Myself))
  !HasItemEquiped("S!sw11",LastSeenBy(Myself))
  !HasItemEquiped("S!sw12",LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iarigid","LOCALS",3)
THEN
  RESPONSE #100
    IncrementGlobal("Iarigid","LOCALS",1)
    SetGlobalTimer("Iathinking","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_RIGID_THINKING)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iafarrow","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iafarrow","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iafarrow","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iafarrow","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTFIRE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iafarrow","LOCALS",7)
THEN
  RESPONSE #100
    IncrementGlobal("Iafarrow","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_FLAME_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaaarrow","LOCALS")
  See(FourthNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaaarrow","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaaarrow","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaaarrow","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaaarrow","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaaarrow","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  !GlobalTimerNotExpired("Iaaarrow","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),100,RESISTACID)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE7)
  !StateCheck(LastSeenBy(Myself),STATE_MIRRORIMAGE)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iaacid","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iaacid","LOCALS",1)
    SetGlobalTimer("Iaaarrow","LOCALS",12)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MELF_ACID_ARROW)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See([PC])
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),40,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iamissile","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iamissile","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),40,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iamissile","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iamissile","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearest([PC]))
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  CheckStatLT(LastSeenBy(Myself),40,MAGICDAMAGERESISTANCE)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStat(LastSeenBy(Myself),4,SCRIPTINGSTATE7)
  !HasBounceEffects(LastSeenBy(Myself))
  GlobalLT("Iamissile","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iamissile","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),WIZARD_MAGIC_MISSILE)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(ThirdNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
  !HasItemEquiped("ring95",LastSeenBy(Myself))
  !HasItemEquiped("S!ring09",LastSeenBy(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iacommand","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iacommand","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(SecondNearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
  !HasItemEquiped("ring95",LastSeenBy(Myself))
  !HasItemEquiped("S!ring09",LastSeenBy(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iacommand","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iacommand","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
  !GlobalTimerNotExpired("Iaspell","LOCALS")
  See(NearestEnemyOf(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_INVISIBLE)
  !StateCheck(LastSeenBy(Myself),STATE_STUNNED)
  !StateCheck(LastSeenBy(Myself),STATE_HELPLESS)
  !StateCheck(LastSeenBy(Myself),STATE_CONFUSED)
  !StateCheck(LastSeenBy(Myself),STATE_PANIC)
  CheckStatLT(LastSeenBy(Myself),75,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStat(LastSeenBy(Myself),1,SCRIPTINGSTATE4)
  !CheckStatGT(LastSeenBy(Myself),0,SCRIPTINGSTATE8)
  !CheckStat(LastSeenBy(Myself),3,SCRIPTINGSTATE7)
  !CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
  !HasItemEquiped("morsword",LastSeenBy(Myself))
  !HasItemEquiped("ring95",LastSeenBy(Myself))
  !HasItemEquiped("S!ring09",LastSeenBy(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStat(LastSeenBy(Myself),2,SCRIPTINGSTATE3)
  GlobalLT("Iacommand","LOCALS",8)
THEN
  RESPONSE #100
    IncrementGlobal("Iacommand","LOCALS",1)
    SetGlobalTimer("Iaspell","LOCALS",6)
    SpellNoDec(LastSeenBy(Myself),CLERIC_COMMAND)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  InMyArea(Player1)
  Global("partyfled","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("partyfled","LOCALS",1)
END

IF
  !Detect([PC])
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  InMyArea(Player1)
  Global("partyfled","LOCALS",1)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  Allegiance(Myself,ENEMY)
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  CheckStatLT(LastSeenBy(Myself),90,RESISTCRUSHING)
  RandomNumGT(6,4)
  Range(LastSeenBy(Myself),3)
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  !GlobalTimerNotExpired("Isturning","LOCALS")
  ActionListEmpty()
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(NearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(SecondNearestEnemyOf(Myself))
  !CheckStatGT(LastSeenBy(Myself),2,SCRIPTINGSTATE6)
THEN
  RESPONSE #100
    AttackOneRound(LastSeenBy(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  GlobalTimerNotExpired("Isturning","LOCALS")
  !See(NearestEnemyOfType([GOODCUTOFF.0.SKELETON.SKELETON.0.SUMMONED]))
  See(NearestEnemyOfType([GOODCUTOFF.0.0.SKELETON_WARRIOR.0.SUMMONED]))
  !Range(LastSeenBy(Myself),12)
  OR(9)
   !See(Player1)
   !Class(Player1,PALADIN_ALL)
   !Range(Player1,12)
   StateCheck(Player1,STATE_PANIC)
   StateCheck(Player1,STATE_CONFUSED)
   StateCheck(Player1,STATE_HELPLESS)
   StateCheck(Player1,STATE_STUNNED)
   StateCheck(Player1,STATE_CHARMED)
   LevelGT(Player1,36)
  OR(8)
   !InParty("keldorn")
   !See("keldorn")
   !Range("keldorn",12)
   StateCheck("keldorn",STATE_PANIC)
   StateCheck("keldorn",STATE_CONFUSED)
   StateCheck("keldorn",STATE_HELPLESS)
   StateCheck("keldorn",STATE_STUNNED)
   LevelGT("keldorn",36)
  OR(8)
   !See(NearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(NearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  OR(8)
   !See(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]))
   !Range(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),12)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_PANIC)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CONFUSED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_HELPLESS)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_STUNNED)
   StateCheck(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),STATE_CHARMED)
   LevelGT(SecondNearestEnemyOfType([PC.0.0.PALADIN_ALL]),36)
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackOneRound(NearestEnemyOf(Myself))
END